/**
 * Static lesson video mapping for Daoud Lamei's Bible explanations.
 * Key format: "BookName-Chapter"  →  YouTube videoId (string) or parts (string[])
 *
 * PRIMARY source — always overrides RSS results.
 * Auto-generated via scripts/fetch-playlist-videos.mjs + manual additions.
 */
export const staticLessonVideos: Record<string, string | string[]> = {

  // ──────────────────────────── يشوع ────────────────────────────
  "يشوع-1":  ["iVomctbKFi0", "PIk-uBXJrXE"],
  "يشوع-2":  ["PIk-uBXJrXE", "BEgM1FCFVD0"],
  "يشوع-3":  ["BEgM1FCFVD0", "zkTEYcfm3Dk"],
  "يشوع-4":  "zkTEYcfm3Dk",
  "يشوع-5":  "2GJxkfiUIDI",
  "يشوع-6":  ["2GJxkfiUIDI", "G6T6U3zCVv4"],
  "يشوع-7":  ["G6T6U3zCVv4", "vaI1EBMkJHg"],
  "يشوع-8":  ["vaI1EBMkJHg", "9TT3tyOSADY"],
  "يشوع-9":  "9TT3tyOSADY",
  "يشوع-10": ["6_peAx9WNTc", "DjTHuni91IU"],
  "يشوع-11": "DjTHuni91IU",
  "يشوع-12": "DjTHuni91IU",
  "يشوع-13": ["DjTHuni91IU", "tZsPd__fQTY"],
  "يشوع-14": "tZsPd__fQTY",
  "يشوع-15": "tZsPd__fQTY",
  "يشوع-16": "g2CbF4HIwqY",
  "يشوع-17": "g2CbF4HIwqY",
  "يشوع-18": "g2CbF4HIwqY",
  "يشوع-19": "g2CbF4HIwqY",
  "يشوع-20": "g2CbF4HIwqY",
  "يشوع-21": "TJGZBYNyXD0",
  "يشوع-22": "TJGZBYNyXD0",
  "يشوع-23": "GQsUuVslFfc",
  "يشوع-24": "GQsUuVslFfc",

  // ──────────────────────────── تكوين ────────────────────────────
  "تكوين-1":  ["YbwZQd7cpjU", "g1eVDttBOO0"],
  "تكوين-2":  "g1eVDttBOO0",
  "تكوين-3":  ["yLiOVybZHUA", "eJmWI5QWpAI", "vtprTE-ZXZ8"],
  "تكوين-4":  ["vtprTE-ZXZ8", "yyABXXSMRo8"],
  "تكوين-5":  ["yyABXXSMRo8", "VGUBB8pqaSM"],
  "تكوين-6":  ["VGUBB8pqaSM", "ma9_Fc6f9lA"],
  "تكوين-7":  ["F_vHHL9m6v4", "j8E8ivvO_EQ"],
  "تكوين-8":  "j8E8ivvO_EQ",
  "تكوين-9":  "j8E8ivvO_EQ",
  "تكوين-10": "x7PzEZ45Y1w",
  "تكوين-11": "x7PzEZ45Y1w",
  "تكوين-12": ["x7PzEZ45Y1w", "X9MJTtD3rO4", "9IcZWBNrxtE"],
  "تكوين-13": "9IcZWBNrxtE",
  "تكوين-14": ["9IcZWBNrxtE", "VripF1UBvYQ"],
  "تكوين-15": ["VripF1UBvYQ", "S-mwSW2zAdo"],
  "تكوين-16": ["S-mwSW2zAdo", "l1Hql6OiFHM"],
  "تكوين-17": "l1Hql6OiFHM",
  "تكوين-18": ["l1Hql6OiFHM", "ycdXACxPlhc"],
  "تكوين-19": ["ycdXACxPlhc", "u8S1Y0Dvk6U"],
  "تكوين-20": "u8S1Y0Dvk6U",
  "تكوين-21": "CNG1VbFOYQs",
  "تكوين-22": ["CNG1VbFOYQs", "_xlTcm0gz4w"],
  "تكوين-23": "_xlTcm0gz4w",
  "تكوين-24": ["_xlTcm0gz4w", "1cRQFnKEdag"],
  "تكوين-25": ["1cRQFnKEdag", "Ns-WrPjCqNk"],
  "تكوين-26": ["Ns-WrPjCqNk", "nlPEqDnwvoI"],
  "تكوين-27": ["nlPEqDnwvoI", "GvgxaoUNlfY"],
  "تكوين-28": "GvgxaoUNlfY",
  "تكوين-29": "pezRmjqzl3o",
  "تكوين-30": ["pezRmjqzl3o", "b-Vq0A2CuMM"],
  "تكوين-31": ["b-Vq0A2CuMM", "WNhC7MN0uhk"],
  "تكوين-32": ["WNhC7MN0uhk", "Vfc8ek7EBGw"],
  "تكوين-33": ["Vfc8ek7EBGw", "DUFv3jmRcjc"],
  "تكوين-34": "DUFv3jmRcjc",
  "تكوين-35": ["DUFv3jmRcjc", "HE3b7yfZkIg"],
  "تكوين-36": "HE3b7yfZkIg",
  "تكوين-37": ["HE3b7yfZkIg", "ICBUC8hnJH0"],
  "تكوين-38": "6VQm7d7J8h8",
  "تكوين-39": ["6VQm7d7J8h8", "q9vchp_D1Kc"],
  "تكوين-40": "q9vchp_D1Kc",
  "تكوين-41": ["gDFuiPxJTz8", "F3arDmAm0t4"],
  "تكوين-42": "F3arDmAm0t4",
  "تكوين-43": ["F3arDmAm0t4", "-Ccvbcaq-GQ"],
  "تكوين-44": "-Ccvbcaq-GQ",
  "تكوين-45": ["-Ccvbcaq-GQ", "6qX6BYkVsKY"],
  "تكوين-46": "6qX6BYkVsKY",
  "تكوين-47": "8lcTEOnauTE",
  "تكوين-48": "LDmcoWsPSb0",
  "تكوين-49": ["LDmcoWsPSb0", "0uHVuRkgM44", "vbFNDhEAcfw"],
  "تكوين-50": "vbFNDhEAcfw",

  // ──────────────────────────── تثنية ────────────────────────────
  "تثنية-1":  ["gbKLgO45ad4", "7BerIBlirnA", "6g13naEN5MA"],
  "تثنية-2":  ["6g13naEN5MA", "5AT0XvGd7D8"],
  "تثنية-3":  "5AT0XvGd7D8",
  "تثنية-4":  ["5AT0XvGd7D8", "lKUzg87TEH4", "J_KuqvTmLas"],
  "تثنية-5":  ["J_KuqvTmLas", "zBoHzfAzrVE"],
  "تثنية-6":  ["zBoHzfAzrVE", "lgSu71Urbvk"],
  "تثنية-7":  ["lgSu71Urbvk", "-3Iu7QSmTUw", "33eg7eMY0Ig"],
  "تثنية-8":  "33eg7eMY0Ig",
  "تثنية-9":  "Mf0-3nnw_dI",
  "تثنية-10": "oXOT9xYzmFI",
  "تثنية-11": "DyAjGc_i6NY",
  "تثنية-12": "aONnZ7BrVPI",
  "تثنية-13": "R1CPv-z1gtk",
  "تثنية-14": "7pSk7rKUqWw",
  "تثنية-15": ["7pSk7rKUqWw", "IyzDbh4M3I0"],
  "تثنية-16": ["IyzDbh4M3I0", "qLZpayoQAlo"],
  "تثنية-17": "qLZpayoQAlo",
  "تثنية-18": "7mkESNKri4U",
  "تثنية-19": "UoIcgRCgv5U",
  "تثنية-20": ["UoIcgRCgv5U", "p0wz9RNmeEw"],
  "تثنية-21": ["p0wz9RNmeEw", "SeHNgUKJiQg"],
  "تثنية-22": ["SeHNgUKJiQg", "4P6zUcmxHSg"],
  "تثنية-23": "4P6zUcmxHSg",
  "تثنية-24": "BXvabKUO69E",
  "تثنية-25": "Fj0AmJGKT_0",
  "تثنية-26": "yjeVMEGiY58",
  "تثنية-27": ["yjeVMEGiY58", "6ayFd-j9eSM"],
  "تثنية-28": ["8uxEl53MvV4", "252oVDveVao"],
  "تثنية-29": "RBz9U5NmWl4",
  "تثنية-30": "050CXqvG-iE",
  "تثنية-31": "tMrm7MBrVbg",
  "تثنية-32": "qQgjxFueNkM",
  "تثنية-33": ["Ryfeh1wHsh4", "QGxXUHpHzpY", "xsEP8xTrEGE", "MEGiAvMDlq4"],

  // ──────────────────────────── صموئيل أول ────────────────────────────
  "صموئيل أول-1":  ["BlidDmGrx-M", "XnhYxye6g6o", "J7aNHIe6aq0"],
  "صموئيل أول-2":  ["XnhYxye6g6o", "MRhKrMGFINg", "YOZzYQXHV5A"],
  "صموئيل أول-3":  ["MRhKrMGFINg", "U2-TyVQKHLM", "4jQDI-om2V8"],
  "صموئيل أول-4":  ["U2-TyVQKHLM", "4jQDI-om2V8"],
  "صموئيل أول-5":  ["U2-TyVQKHLM", "4jQDI-om2V8", "WDfxS52nyTI"],
  "صموئيل أول-6":  ["TSjMy3uGZTI", "WDfxS52nyTI", "d_92GJuUkk4"],
  "صموئيل أول-7":  ["TSjMy3uGZTI", "7oQSKdRXRkA", "d_92GJuUkk4", "YTlN4MtqyL8"],
  "صموئيل أول-8":  ["7oQSKdRXRkA", "YTlN4MtqyL8"],
  "صموئيل أول-9":  ["7oQSKdRXRkA", "N4TXOSknPpE", "1wALnvxTnek"],
  "صموئيل أول-10": ["N4TXOSknPpE", "c9YFeq5nMfk", "1wALnvxTnek"],
  "صموئيل أول-11": ["c9YFeq5nMfk", "wTzwKoXJcxk", "1wALnvxTnek", "8bEl6gcCn4E"],
  "صموئيل أول-12": ["wTzwKoXJcxk", "8bEl6gcCn4E", "3H8pRgE8TOU"],
  "صموئيل أول-13": ["wTzwKoXJcxk", "NMhpgbzM1S0", "3H8pRgE8TOU"],
  "صموئيل أول-14": ["NMhpgbzM1S0", "xaFCrXHAaFA", "ENiiBxU9xu0"],
  "صموئيل أول-15": ["xaFCrXHAaFA", "3x8-Vt_hql8", "ENiiBxU9xu0", "Errfe85ymfk"],
  "صموئيل أول-16": ["3x8-Vt_hql8", "Er43O6Z_byU", "Errfe85ymfk", "v6R-qVCclXg"],
  "صموئيل أول-17": ["Er43O6Z_byU", "qorYmlC7ods", "v6R-qVCclXg"],
  "صموئيل أول-18": ["qorYmlC7ods", "96SeEF_FoPg", "mRjkxoAor4s"],
  "صموئيل أول-19": ["96SeEF_FoPg", "KgqRVhfiIVY", "mRjkxoAor4s", "5UWOzXvKr9o"],
  "صموئيل أول-20": ["KgqRVhfiIVY", "5UWOzXvKr9o", "38rdzkTNok0"],
  "صموئيل أول-21": ["KgqRVhfiIVY", "DhktDB8w-TI", "38rdzkTNok0", "j-6KUE6gv3Y"],
  "صموئيل أول-22": ["DhktDB8w-TI", "gQU553E8hb4", "j-6KUE6gv3Y", "FKxhKqQTfDk", "WjZOWeVSuYs"],
  "صموئيل أول-23": ["gQU553E8hb4", "SxxiAFRi42A", "5x4qEuItp0Q"],
  "صموئيل أول-24": ["OIXnFKDGMn8", "leiqygcU4rQ"],
  "صموئيل أول-25": ["OIXnFKDGMn8", "BOMmPrvgxwQ", "N1mk39k3_UE"],
  "صموئيل أول-26": "N1mk39k3_UE",
  "صموئيل أول-27": "Bfi5TqPMY3w",
  "صموئيل أول-28": "Bfi5TqPMY3w",
  "صموئيل أول-29": "37c-FTyee0g",
  "صموئيل أول-30": "37c-FTyee0g",
  "صموئيل أول-31": "37c-FTyee0g",

  // ──────────────────────────── أيوب ────────────────────────────
  "أيوب-1":  ["In4Tl3KvKq4", "9lCEO-hhxUU", "zCxMqsz1FO4", "ndT58pv5EcE"],
  "أيوب-2":  ["22RphXQ4G94", "ndT58pv5EcE"],
  "أيوب-3":  "U8pO6Rf4kcs",
  "أيوب-5":  "dvrPLMMaKHU",
  "أيوب-6":  "4Ucf8FqNwWc",
  "أيوب-8":  "hzdHSw8FyYo",
  "أيوب-9":  "AwoP1Fsw-Ac",
  "أيوب-10": "LSsxVfzJzXU",
  "أيوب-12": "KWQokCr75zM",
  "أيوب-13": "JDCJ2d1Iou0",
  "أيوب-15": "lK48YvEKCpE",
  "أيوب-16": "JR6gLo0ipGg",
  "أيوب-18": "C6o8fdmyd20",
  "أيوب-20": "F1cUb0olUXk",
  "أيوب-22": "dXujzw0Iugg",
  "أيوب-24": "BUqHGQhFmaM",
  "أيوب-27": "7V0l3YOXmxk",
  "أيوب-29": "qKVaBzN1uO0",
  "أيوب-31": "hFRrNGvnISs",
  "أيوب-33": ["Z6lA1RZqwdU", "7hbY7UJ2oh0"],
  "أيوب-34": ["MmXmN62fA2Q", "7hbY7UJ2oh0", "KqAN3CatXuU"],
  "أيوب-35": ["dAlb59daWjc", "KqAN3CatXuU", "I1_JHA_ylCI"],
  "أيوب-36": "I1_JHA_ylCI",
  "أيوب-37": ["CNo8GjWfI-Q", "YYiG0pcRx5E"],
  "أيوب-38": ["XFscM-f4nBw", "YYiG0pcRx5E"],
  "أيوب-40": ["IiWNWjKfuLQ", "NEeJSAgBe5o"],
  "أيوب-41": ["4S4Mn3xgM5c", "NEeJSAgBe5o", "PNES_SPlg8U"],
  "أيوب-42": "PNES_SPlg8U",

  // ──────────────────────────── أمثال ────────────────────────────
  "أمثال-1":  ["BdxTNGAKy8E", "5CejNgWQkF0", "EQBpfD6s71k"],
  "أمثال-2":  ["EQBpfD6s71k", "z-RxkN4ypbc"],
  "أمثال-3":  ["z-RxkN4ypbc", "NgJIhnLYUmE", "ha_2gdKpqjE"],
  "أمثال-4":  ["ha_2gdKpqjE", "2lINQqimWWU"],
  "أمثال-5":  "Wa137mzu6_k",
  "أمثال-6":  ["kDJB0ZkLa7g", "7BCRQfOx7QI"],
  "أمثال-7":  "HkBqAvjbQTQ",
  "أمثال-8":  ["HkBqAvjbQTQ", "mDjTRjM1m3Y"],
  "أمثال-9":  "9RKk5a0Vgl4",
  "أمثال-10": ["9j5dx7xFMfg", "JeSmPXfO2WY", "nr4So7KwySc"],
  "أمثال-11": ["nr4So7KwySc", "B3E8LzcaZpo", "gcsya1OR0J8", "zz0HafLaz64"],
  "أمثال-12": ["zz0HafLaz64", "o4WEAPzXeCA"],
  "أمثال-13": ["o4WEAPzXeCA", "9fR-G-fFLc8", "1ZYk2XpKrCY"],
  "أمثال-14": ["1ZYk2XpKrCY", "qpnoOShVUmw", "nTbXlGcVkXc", "5xbhJNSWQlQ"],
  "أمثال-15": ["5xbhJNSWQlQ", "li4IJoDMdIg", "X5c5QmRGUck", "L7e37wQJWBw"],
  "أمثال-16": ["UgPpnQwQ6zU", "S_xC-H4kiZs"],
  "أمثال-17": ["S_xC-H4kiZs", "Em8F9trcn54", "ISV2-z05C4o"],
  "أمثال-18": ["ISV2-z05C4o", "bWKGKKNgqyU", "a5Ukgz4zGLA"],
  "أمثال-19": ["a5Ukgz4zGLA", "2dx27mLiyhg"],
  "أمثال-20": ["23Ee5OeQAs8", "QKYv-urMPKo", "RbePd4MnskA"],
  "أمثال-21": ["RbePd4MnskA", "EL_Xya0otww", "skY6Q5mhUGA"],
  "أمثال-22": "skY6Q5mhUGA",

  // ──────────────────────────── نشيد الأنشاد ────────────────────────────
  "نشيد الأنشاد-1": ["_XjOzT574C8", "lPBVYllExrI", "9SyFzmoKBD0"],
  "نشيد الأنشاد-2": ["9SyFzmoKBD0", "NClemO3PF6U", "uHZS8-ZJ8Ko"],
  "نشيد الأنشاد-3": ["uHZS8-ZJ8Ko", "CzirVSXX7f0"],
  "نشيد الأنشاد-4": ["CzirVSXX7f0", "pY_vQr1qJZ8", "os44ihcsOYs"],
  "نشيد الأنشاد-5": ["os44ihcsOYs", "OE-yHzR_EuM", "H33RdU5eOz0"],
  "نشيد الأنشاد-6": ["DWj7ifzdF20", "8Ko27Ar2RWM", "Zk4Utx2DO3Y"],
  "نشيد الأنشاد-7": ["Zk4Utx2DO3Y", "Zsb1_upMe3o", "4SS_3dYzXOs"],
  "نشيد الأنشاد-8": ["4SS_3dYzXOs", "tZ7DDjOsWNk"],

  // ──────────────────────────── حزقيال ────────────────────────────
  "حزقيال-3":  "t2fzp1yrx5w",
  "حزقيال-11": "B4oUMbU4UG0",

  // ──────────────────────────── متى ────────────────────────────
  "متى-1":  ["znT5IMIAPW0", "qTpk3VSna54"],
  "متى-2":  ["P1YJhHI2x88", "yFQ1BjInAHk"],
  "متى-3":  ["ks6xcqQytEw", "ID5Lpmd5RAk"],
  "متى-4":  ["v49yoKufL98", "pdw4mZvmQew"],
  "متى-5":  ["U0feXv_h6pY", "YAI1fwFPuvY", "oQ_Ij_c4d6E"],
  "متى-6":  ["UC1ZN8ybsKA", "YytQFn3R-ks", "5MqqqTBlhZM"],
  "متى-7":  ["M4Bv56CSfIk", "l55tpyE0eHI", "LTnserUuKWQ"],
  "متى-8":  "TZECto9zXUU",
  "متى-9":  ["BTKkGm2NH5E", "c-SWCzaL5Qs", "rNZQ2GboTDw"],
  "متى-10": ["LA1juS18ahw", "QyyWX3vYh3Y"],
  "متى-11": ["8FEDWo2gm_4", "cCxvE2esCo0"],
  "متى-12": ["ce9sPW4Odg0", "ajUGrw4bjp8"],
  "متى-13": ["b6iOZufLO1k", "aONdfEc8Lss", "qy7uyACza2Y"],
  "متى-14": ["rUqjy-9-pGc", "y473ba5rl98"],
  "متى-15": ["zgsvFO3sKdI", "2Mb_A0kv6eI"],
  "متى-16": "INhchVwu7cU",
  "متى-17": "9-t_8MYCd4w",
  "متى-18": ["nZ6PAndCatQ", "KWTRqmSPMSY"],
  "متى-19": ["koY2XIV5104", "0VhhaS0cIQ0"],
  "متى-20": "XvgxLXrtnGw",
  "متى-21": ["6SaCmIT0H6I", "3wI3BE05BBs"],
  "متى-22": ["EgWHIPsOpZc", "7Cu2IUfpyq0"],
  "متى-23": ["f58SSaonfWM", "lFBXYKGkUKc"],
  "متى-24": ["dJjlfKqN044", "Fz5MuRN6pQw"],
  "متى-25": "cegV_BKhd7g",
  "متى-26": ["QVJuhDs3lNY", "7G_U0KsdkMI", "iM4RbCMJ7pw"],
  "متى-27": ["TNpIOpqsFGw", "xPxiuzTmTXc"],

  // ──────────────────────────── لوقا ────────────────────────────
  "لوقا-1":  ["Ix-ZF-LDk-E", "OA8b_qh5vtw", "8CJIMLAdfOE"],
  "لوقا-2":  "XMv3APN_VLY",
  "لوقا-3":  "ZjL5HnfEEvE",
  "لوقا-5":  "5czMFM4DEdo",
  "لوقا-6":  "nX6SLnMdBeI",
  "لوقا-7":  "eje8L77fju4",
  "لوقا-8":  ["Tenq8aJwkLc", "MGs5VidjSZw"],
  "لوقا-9":  ["AjWRWYFCzxM", "29FRBaLN1SA"],
  "لوقا-11": "eqtWlFr9qJ4",
  "لوقا-12": "Zcj77931oeg",
  "لوقا-13": "QcQBrZWZOoY",
  "لوقا-14": "xCoCrg-sStM",
  "لوقا-16": "90wtweg7JxU",
  "لوقا-18": "1wqmBXatDtI",
  "لوقا-19": "V-OyaTIP1FU",

  // ──────────────────────────── يوحنا ────────────────────────────
  "يوحنا-1":  ["DJhIwatChEo", "pSUzBYlmnoc", "1lGVZ2grVqI", "Ug6HF2dfMNQ"],
  "يوحنا-2":  ["0XQstzgDf4E", "KVSacNy6x2k"],
  "يوحنا-3":  ["IwyZewOC-28", "926aDoxaVu4", "axfpDi_gG5o"],
  "يوحنا-4":  ["a-WJLXhgOms", "gFqXBqB2AGk", "5pIaX0RzDF8"],
  "يوحنا-5":  ["ERcpvGInqC8", "K_cODxOCfeE"],
  "يوحنا-6":  ["fA-HzRmL97s", "Tp1vBYlnxa0", "BHTaHgkaaiI"],
  "يوحنا-7":  "ffUR9_WwZZc",
  "يوحنا-8":  ["QPslyNSZMEw", "MPTVYLJqpnw", "C5ITpMqK-Gc"],
  "يوحنا-9":  "Ko6-jSGhNAI",
  "يوحنا-10": ["By1DnIPIk5I", "aPON6WD9fCA"],
  "يوحنا-11": ["5AjX4IXwQ4I", "_I_QoIgpC-c", "KGC2TFkig0I"],
  "يوحنا-12": ["fpA48gVTbWY", "PahHkIO1vV4", "F96G6g_rlgs"],
  "يوحنا-13": "dk8bGPiHruY",
  "يوحنا-14": ["NVnP5j8juA8", "JZz6ATjp86c"],
  "يوحنا-15": ["oQDMnQxEEW4", "ejvZidsvv-o"],
  "يوحنا-16": ["ANxEppK3N50", "wcot4oXQvKs"],
  "يوحنا-17": ["qqxxaxs1rQc", "dVIpTlGVIVo", "BWTqAYBony0", "M3D6AzEjjqI", "SKJmuAx7Avc", "SRg6Dg0Y0NM"],
  "يوحنا-18": ["Z18mZKlydG8", "YxJ4PfBTBqY"],
  "يوحنا-19": "2z2mcyDfbos",
  "يوحنا-20": ["e3ftIm6GU5I", "O2tkjDNmzLs"],
  "يوحنا-21": "pbxXEQ903Ww",

  // ──────────────────────────── أعمال الرسل ────────────────────────────
  "أعمال الرسل-27": "rPPe4yxuPXs",
  "أعمال الرسل-28": "rPPe4yxuPXs",

  // ──────────────────────────── المزامير ────────────────────────────
  "المزامير-1":   ["PQVlq-XcXsk", "o_28aPrbT9g"],
  "المزامير-2":   ["PQVlq-XcXsk", "o_28aPrbT9g"],
  "المزامير-3":   "ZfDenrOnTj0",
  "المزامير-4":   "ZfDenrOnTj0",
  "المزامير-5":   "9VxHOnPHnCM",
  "المزامير-6":   "9VxHOnPHnCM",
  "المزامير-7":   "WRvIEJr5Bhw",
  "المزامير-8":   "WRvIEJr5Bhw",
  "المزامير-9":   "eH9yVHnjdwg",
  "المزامير-10":  "eH9yVHnjdwg",
  "المزامير-11":  "2dfazvaavs8",
  "المزامير-12":  "2dfazvaavs8",
  "المزامير-13":  "3DLkfwxx1dk",
  "المزامير-14":  "3DLkfwxx1dk",
  "المزامير-15":  "rQgUN-sBNe8",
  "المزامير-16":  "rQgUN-sBNe8",
  "المزامير-17":  "eKTrAFx9VvI",
  "المزامير-18":  "4xwbVr_zqxM",
  "المزامير-19":  "x_7qodEEC9M",
  "المزامير-20":  "x_7qodEEC9M",
  "المزامير-21":  "Qy5eM6L6itc",
  "المزامير-22":  "Qy5eM6L6itc",
  "المزامير-23":  "Qz58mHHqHW8",
  "المزامير-24":  "Qz58mHHqHW8",
  "المزامير-25":  "e4uB-mZj_9E",
  "المزامير-26":  "e4uB-mZj_9E",
  "المزامير-27":  "ao5umiasi_0",
  "المزامير-28":  "ao5umiasi_0",
  "المزامير-29":  "64BA5tGtmGo",
  "المزامير-30":  "64BA5tGtmGo",
  "المزامير-31":  "QWKX_xQxQNU",
  "المزامير-32":  "o6dBUsoRFtw",
  "المزامير-33":  "o6dBUsoRFtw",
  "المزامير-34":  "A9dLFi3qm74",
  "المزامير-35":  "ZIvwm3kLxh4",
  "المزامير-36":  "zyDgxbTZWy0",
  "المزامير-37":  "vimBdh4H_P4",
  "المزامير-38":  "wKmvrWtDv_U",
  "المزامير-39":  "wKmvrWtDv_U",
  "المزامير-40":  "SFJJuIWSLc4",
  "المزامير-41":  "SFJJuIWSLc4",
  "المزامير-42":  "WXun5I59GWs",
  "المزامير-43":  "WXun5I59GWs",
  "المزامير-44":  "_HK5VF88-mM",
  "المزامير-45":  "1Jq36iFqrnA",
  "المزامير-46":  "Pu4rxzcYGfw",
  "المزامير-47":  "Pu4rxzcYGfw",
  "المزامير-48":  "oCSXckEtUvI",
  "المزامير-49":  "v-OypUH782E",
  "المزامير-50":  "0_8XrnUbQNw",
  "المزامير-51":  "Oqyx1l9xFmI",
  "المزامير-52":  ["Jplq9RtZD4A", "A3-OHCkPtPg"],
  "المزامير-53":  ["Jplq9RtZD4A", "A3-OHCkPtPg"],
  "المزامير-54":  "rWJylam3Dpk",
  "المزامير-55":  "rWJylam3Dpk",
  "المزامير-56":  "FMiDV8woydM",
  "المزامير-57":  "FMiDV8woydM",
  "المزامير-58":  "DZ7uLbMblms",
  "المزامير-59":  "DZ7uLbMblms",
  "المزامير-60":  "hfwf2Fyz8mw",
  "المزامير-61":  "hfwf2Fyz8mw",
  "المزامير-62":  "tVwKOS3p6fo",
  "المزامير-63":  "tVwKOS3p6fo",
  "المزامير-64":  "tjEjivk9l4w",
  "المزامير-65":  "tjEjivk9l4w",
  "المزامير-66":  "AEVijWThwh8",
  "المزامير-67":  "AEVijWThwh8",
  "المزامير-68":  "85vAzRLNhnc",
  "المزامير-69":  "Gj-1xAC7704",
  "المزامير-70":  "mqYTJ4bqo8A",
  "المزامير-71":  "mqYTJ4bqo8A",
  "المزامير-72":  "G2jM5uMohgA",
  "المزامير-73":  "QGc4bCCftiY",
  "المزامير-74":  "UsRpaCmjb_Q",
  "المزامير-75":  "l6KaV8gN_Bw",
  "المزامير-76":  "l6KaV8gN_Bw",
  "المزامير-77":  "8Edz0XYPk5U",
  "المزامير-78":  "nUH10Xh_uz8",
  "المزامير-79":  "kXuiNXFS6vM",
  "المزامير-80":  "kXuiNXFS6vM",
  "المزامير-81":  "AFXJtJbr9v0",
  "المزامير-82":  "AFXJtJbr9v0",
  "المزامير-83":  "lhPMu3gRyMk",
  "المزامير-84":  "gD1qvnL2-ks",
  "المزامير-85":  "x3O2eKEcJ9c",
  "المزامير-86":  "7_crhsjSeQ0",
  "المزامير-87":  "CE2tMN6Z8ko",
  "المزامير-88":  "CE2tMN6Z8ko",
  "المزامير-89":  "Zzb7ldk2h6k",
  "المزامير-90":  "xLu2wLJ90co",
  "المزامير-91":  "JD3BAXc0j_0",
  "المزامير-92":  "3rhGETkcQSA",
  "المزامير-93":  "3rhGETkcQSA",
  "المزامير-94":  "-qAetgitxWk",
  "المزامير-95":  "YnIwdqerlFE",
  "المزامير-96":  "YnIwdqerlFE",
  "المزامير-97":  "LgE9uF0aFFE",
  "المزامير-98":  "LgE9uF0aFFE",
  "المزامير-99":  "HPJf9GbVPeo",
  "المزامير-100": "HPJf9GbVPeo",
  "المزامير-101": "DbNB09HXMBY",
  "المزامير-102": "DbNB09HXMBY",
  "المزامير-103": "malIKeE9V5M",
  "المزامير-104": "766tEQEDZB0",
  "المزامير-105": "r9II0unibeI",
  "المزامير-106": "ELn0hOqw36k",
  "المزامير-107": "BAk3M9xKnSs",
  "المزامير-108": "Ja173TquJfQ",
  "المزامير-109": "WQbvAyhZEkU",
  "المزامير-111": "GV7I9e84xdM",
  "المزامير-112": "GV7I9e84xdM",
  "المزامير-113": "UAqViABo7vs",
  "المزامير-114": "UAqViABo7vs",
  "المزامير-115": "FQyhkl62Hbs",
  "المزامير-116": "FQyhkl62Hbs",
  "المزامير-117": "k3hBqM6uZ0E",
  "المزامير-118": "k3hBqM6uZ0E",
  "المزامير-119": ["vn-tQN4Z1MM", "IunOC24coqo", "sb06Z1nHSV4", "fqLAZzZLlWo", "e4JxEzPNcA0", "4rc7jFq5usg", "_s0W1Xhealc", "ykRlZmX-aHo"],
  "المزامير-120": "QdrTGQZaSSg",
  "المزامير-121": "QdrTGQZaSSg",
  "المزامير-122": "dKgA1nA9OAU",
  "المزامير-123": "dKgA1nA9OAU",
  "المزامير-124": "fCMRpMCmhU8",
  "المزامير-125": "fCMRpMCmhU8",
  "المزامير-126": "id_y1xKGK2A",
  "المزامير-127": "id_y1xKGK2A",
  "المزامير-128": "WQfmjg6wWok",
  "المزامير-129": "WQfmjg6wWok",
  "المزامير-130": "fsSOC0zogVs",
  "المزامير-131": "fsSOC0zogVs",
  "المزامير-132": "L-T24c53Bxg",
  "المزامير-133": "EAlklx0YcsM",
  "المزامير-134": "EAlklx0YcsM",
  "المزامير-135": "EAlklx0YcsM",
  "المزامير-136": "rIAHhzcPZHA",

  // ──────────────────────────── مرقس ────────────────────────────
  "مرقس-1":  ["PmixD7sEo60", "Tq6HF7PRsNE", "zB0Tz62nW4Y"],
  "مرقس-2":  ["H1LrtcWkpCc", "n4BuqifefkY"],
  "مرقس-3":  "oYf792ikxMo",
  "مرقس-4":  "2CQUQ5jqz80",
  "مرقس-5":  ["0qLf1rRr270", "R5vfSQCNuZ8"],
  "مرقس-6":  ["WTJ6YXtGFVc", "_Mc37kSXPJQ", "b75bykQmBiU"],
  "مرقس-7":  "xoAMFhxiPmI",
  "مرقس-8":  ["1lXKW9OmpoU", "BsP77955K9Y"],
  "مرقس-9":  ["plMnrayQlBA", "BWWsw9YSjwc"],
  "مرقس-10": ["BikW8Z1aNOU", "EwaCMvOmeDU", "YcUBTZFPa7w"],
  "مرقس-11": ["2jL1cwANxdY", "F8QwRIU9M7E"],
  "مرقس-12": ["HxeLNwQyf1o", "GXAC2QN2eB0"],
  "مرقس-13": ["XIjIT_Tt1GI", "BOGuIsL5DuM"],
  "مرقس-14": ["wfeHR18CBsw", "VjbxqZnWIAI", "8U52w0FJGZo"],
  "مرقس-15": ["C8xiJH2s2Ik", "MJb9R-WOCq8", "1nBy97Q6k54"],
  "مرقس-16": "8CfbyAkkA2A",

  // ──────────────────────────── أعمال الرسل (إصحاحات 1-26) ────────────────────────────
  "أعمال الرسل-1":  "_AqAtIxlP9Y",
  "أعمال الرسل-2":  "LnR4hlnkxnU",
  "أعمال الرسل-3":  "sWbLSyojlGc",
  "أعمال الرسل-4":  "mt8UMnVMb3Y",
  "أعمال الرسل-5":  "mt8UMnVMb3Y",
  "أعمال الرسل-6":  "qmupffiUlg0",
  "أعمال الرسل-7":  "qmupffiUlg0",
  "أعمال الرسل-8":  "qmupffiUlg0",
  "أعمال الرسل-9":  "G3m3Kml5vbU",
  "أعمال الرسل-10": "l8o-2aSc670",
  "أعمال الرسل-11": "PLLrnoHTLK8",
  "أعمال الرسل-12": "PLLrnoHTLK8",
  "أعمال الرسل-13": "wIetjV3e6AM",
  "أعمال الرسل-14": "wIetjV3e6AM",
  "أعمال الرسل-15": "q5HZNXEid24",
  "أعمال الرسل-16": "cSYzg2Ekp1A",
  "أعمال الرسل-17": "wSWQKdwx3nA",
  "أعمال الرسل-18": "v4cDPIWtqnY",
  "أعمال الرسل-19": "v4cDPIWtqnY",
  "أعمال الرسل-20": "byTJNgv0R6U",
  "أعمال الرسل-21": "3Tzd2AIlW68",
  "أعمال الرسل-22": "3Tzd2AIlW68",
  "أعمال الرسل-23": "RIgCv4co4kc",
  "أعمال الرسل-24": "RIgCv4co4kc",
  "أعمال الرسل-25": "BJWILvmDMYA",
  "أعمال الرسل-26": "BJWILvmDMYA",

  // ──────────────────────────── رومية ────────────────────────────
  "رومية-1":  ["pZYxBQVLpiI", "j3fFPxtj3do", "nz0SQQ1TeGo"],
  "رومية-3":  ["_DLwJHcQbIA", "k95KC2567Ew"],
  "رومية-4":  "IfjRbtGEYus",
  "رومية-5":  ["X5DajH8Y5ZI", "ltHeFH14_CE"],
  "رومية-6":  "RG1PZh6j9NU",
  "رومية-7":  "G2aROG7sUXY",
  "رومية-8":  ["oXgL4vLiFew", "uKt9tFDuSq8", "nT4VLyLfpDU"],
  "رومية-9":  ["eQz1aJlRSJg", "oJwmhKKf6H0", "kKt__KYoxwU"],
  "رومية-10": ["g9Ggi_Ni9iQ", "21tG_3t5VGs"],
  "رومية-11": ["cpjvj7Wkoho", "ZR9_zyjxlhE"],
  "رومية-12": ["UKmBq4tFQIs", "v1uloqcNwb4", "nQt3-tnsk-k"],
  "رومية-13": "zf_gVoirHcI",
  "رومية-14": ["5GbgNmG4_1Y", "_dDGMVnLBO4"],
  "رومية-15": ["CZKORYTf6k8", "bAJMvuVh_Yw"],
  "رومية-16": "VVyCE1DgyD8",

  // ──────────────────────────── كورنثوس الأولى ────────────────────────────
  "كورنثوس الأولى-1":  ["Xb4_ZWDEGas", "UK3BqCQF_2Q"],
  "كورنثوس الأولى-2":  "I729y69dCGw",
  "كورنثوس الأولى-3":  "z0PSGPUB6Ww",
  "كورنثوس الأولى-4":  "6-5HBB1G2ck",
  "كورنثوس الأولى-5":  "Ka_mGAG4mgA",
  "كورنثوس الأولى-6":  ["9_uVT6PfIis", "dicPrwshXdQ"],
  "كورنثوس الأولى-7":  "3IYy_Il0-wA",
  "كورنثوس الأولى-8":  "hb_ONFbr3js",
  "كورنثوس الأولى-9":  "1w4Jm9maRmc",
  "كورنثوس الأولى-10": ["VceztNPbFCQ", "xWiitR1-43I"],
  "كورنثوس الأولى-11": ["4yBjs5vYIlk", "2xQmMEX6aLc"],
  "كورنثوس الأولى-12": "GQe8JUmdse4",
  "كورنثوس الأولى-13": "uZS9r40PdB4",
  "كورنثوس الأولى-14": ["3LxDdPHD2s4", "HlgwX4YlwQE"],
  "كورنثوس الأولى-15": ["7w5dN8p4opg", "wmkoskTPn6Q", "Ne4gwPaqbd0", "rCOtCcPo_gQ"],

  // ──────────────────────────── كورنثوس الثانية ────────────────────────────
  "كورنثوس الثانية-1":  ["B2unCNqt7jA", "jsm61IRPgQ0"],
  "كورنثوس الثانية-2":  "3GDpwiM8ODo",
  "كورنثوس الثانية-3":  "ye5I1zLtgW4",
  "كورنثوس الثانية-4":  ["A5aA4bNhcLY", "Id7UcqFuHcM"],
  "كورنثوس الثانية-5":  ["7-eod30lJ3I", "cP2edI9QMxk"],
  "كورنثوس الثانية-6":  ["QItV8p6-3xo", "u7VQ2nHC8IQ"],
  "كورنثوس الثانية-7":  "avVR8HxkXSw",
  "كورنثوس الثانية-8":  ["J_6X8MNZSOw", "jKxrWWOdWCA"],
  "كورنثوس الثانية-9":  "S9fjyji8pQU",
  "كورنثوس الثانية-10": "wYEDHo5EQ5Y",
  "كورنثوس الثانية-11": ["Wt3rzgpi3aE", "4AKK4AVGMR8"],
  "كورنثوس الثانية-12": "1uyCkSs3Olc",
  "كورنثوس الثانية-13": "JUQI6AxOOos",

  // ──────────────────────────── غلاطية ────────────────────────────
  "غلاطية-1": ["E68hRZEPx3o", "s1-ntD2-oLo"],
  "غلاطية-2": "rXQSOPniU9Q",
  "غلاطية-3": ["g96r_hFv8GI", "Fc8Jl5QxtUQ"],
  "غلاطية-4": "Ayu6o8C2HFw",
  "غلاطية-5": ["v6borHztKgI", "nQJXZqc91Mo"],
  "غلاطية-6": "hpQXt5_a4HE",

  // ──────────────────────────── أفسس ────────────────────────────
  "أفسس-1": ["5Regh4Uw9UE", "OUeeaIwI5zE", "ZvjI2LOCRGw", "e-PbbMdb-k0"],
  "أفسس-2": ["7yliZrPKcn8", "ad07EdBn7eA"],
  "أفسس-3": ["y5JszfGz01o", "KTTfwiePueM"],
  "أفسس-4": ["DIU-fFL-6Hk", "y5b88fyjyn0"],
  "أفسس-5": ["KBJ8po56jwk", "IxHDmr5MFaw"],
  "أفسس-6": ["829zOfo17CI", "ExtinTK02J0", "QASzoX1UwgY"],

  // ──────────────────────────── فيلبي ────────────────────────────
  "فيلبي-1": ["LgnLTZLPpfA", "5cZpsjBaOEM"],
  "فيلبي-2": "riWOVYhrbf8",
  "فيلبي-3": "UVzccd7JJy0",
  "فيلبي-4": "tzhF6fr-YGQ",

  // ──────────────────────────── كولوسي ────────────────────────────
  "كولوسي-1": ["LlyXauWA0bA", "JJaLXujomOs"],
  "كولوسي-2": "0aw7LB7Uhjs",
  "كولوسي-3": "ix36tzglWkM",
  "كولوسي-4": "3FsJ6ke7gSk",

  // ──────────────────────────── تسالونيكى الأولى ────────────────────────────
  "تسالونيكى الأولى-1": "MB2uv54Wj2o",
  "تسالونيكى الأولى-2": "e3MyJaWkiyM",
  "تسالونيكى الأولى-3": "ed6iLgFWZT8",
  "تسالونيكى الأولى-4": "ed6iLgFWZT8",
  "تسالونيكى الأولى-5": "MKs5NYTLPQo",

  // ──────────────────────────── تسالونيكى الثانية ────────────────────────────
  "تسالونيكى الثانية-1": "Vl8hvN484h8",
  "تسالونيكى الثانية-2": "Vl8hvN484h8",
  "تسالونيكى الثانية-3": "Vl8hvN484h8",

  // ──────────────────────────── تيموثاوس الأولى ────────────────────────────
  "تيموثاوس الأولى-1": ["IK-8OHswyuI", "iIukMU8nGYE"],
  "تيموثاوس الأولى-2": ["os6S94jy4Fw", "0knXa0GNLrk"],
  "تيموثاوس الأولى-3": "Rfk7o5Atp2o",
  "تيموثاوس الأولى-4": ["e2vL3G9Er6M", "VG5soj2Go-8"],
  "تيموثاوس الأولى-5": ["Qot88LDscJs", "pVtE8bvYorU"],

  // ──────────────────────────── تيموثاوس الثانية ────────────────────────────
  "تيموثاوس الثانية-1": ["zE2x1M83dw0", "S3fohYI44sc"],
  "تيموثاوس الثانية-2": ["NiD9uyuEHC0", "jlW7mWEC4fw", "j69_s1NbqZs"],
  "تيموثاوس الثانية-3": "BqGoQxLzPAI",
  "تيموثاوس الثانية-4": "Zi9DeSZHoOQ",

  // ──────────────────────────── تيطس ────────────────────────────
  "تيطس-1": ["6ADsI4k8maA", "c_y6lD1FEvU"],
  "تيطس-2": ["jMzq9BpK1es", "Pa-n-NcpcAk"],
  "تيطس-3": "aEx3YrB3Lzg",

  // ──────────────────────────── فليمون ────────────────────────────
  "فليمون-1": "Q5aj6oy1A5g",

  // ──────────────────────────── عبرانيين ────────────────────────────
  "عبرانيين-1":  ["Sh8Vd3ju_d8", "IACACNgtwkY", "nO0PFh1Jq9c"],
  "عبرانيين-2":  "vDtvXe6O7oc",
  "عبرانيين-3":  ["ms0LWBXEFB8", "rmZ_7iSIae0"],
  "عبرانيين-4":  "JWSDqjodoxw",
  "عبرانيين-5":  "YtGIiDmvPlA",
  "عبرانيين-6":  "WbLEyVKf61g",
  "عبرانيين-7":  "MYO7tCKmgus",
  "عبرانيين-8":  "17RUr7hXZZE",
  "عبرانيين-9":  ["of2OkuhcWl8", "TGN7I2oa1us"],
  "عبرانيين-10": ["H7GkwY-8dXo", "VaVi-iXgQ1w"],
  "عبرانيين-11": ["ujSoKOlFmHc", "aJXiWql7Xxs", "uHPM2XWv4l0", "e3t3UiAYmmQ"],
  "عبرانيين-12": ["p4ZNKKr_xBk", "qZHl3LwkieI"],
  "عبرانيين-13": "pkGsdAog6Mg",

  // ──────────────────────────── يعقوب ────────────────────────────
  "يعقوب-1": ["HkCdUzHO6o4", "YLl2z7dIEW0"],
  "يعقوب-2": ["7P4wiX4pxMQ", "MN-A3RFUdPI"],
  "يعقوب-3": "hANbscanA1Y",
  "يعقوب-4": ["6M0TtSE0i-k", "MuMOXTQWs3I"],
  "يعقوب-5": ["9vOV0j7qsm4", "CDBLjieabhs"],

  // ──────────────────────────── بطرس الأولى ────────────────────────────
  "بطرس الأولى-1": ["516iifB5MOc", "nuQS2tyPlZs", "Uvf1-B-0Hjc"],
  "بطرس الأولى-2": ["BoxsNudIuXs", "9oNV9z-rJQA"],
  "بطرس الأولى-3": ["ZEQqV7wlKV4", "BOt70kxVt20"],
  "بطرس الأولى-4": ["V-BWsTKlDtE", "9vm2ZN8lRTI"],
  "بطرس الأولى-5": "-sMmFpR1utw",

  // ──────────────────────────── بطرس الثانية ────────────────────────────
  "بطرس الثانية-1": ["psSG4dG_UwU", "wX7Z9SXRTrM"],
  "بطرس الثانية-2": ["XsQ4YIKR0Mo", "ALbYos-wWeM"],
  "بطرس الثانية-3": "Vy_tDBBzgCM",

  // ──────────────────────────── يوحنا الأولى ────────────────────────────
  "يوحنا الأولى-1": "tXx12ho1-pA",
  "يوحنا الأولى-2": ["Vo6Eo5eHyCQ", "S-XbsThB2eY"],
  "يوحنا الأولى-3": "UDgg2hNT0nU",
  "يوحنا الأولى-4": "RS-aICywDm4",
  "يوحنا الأولى-5": "wJkHDtT0tQ0",

  // ──────────────────────────── يوحنا الثانية ────────────────────────────
  "يوحنا الثانية-1": "YgDGp768CJI",

  // ──────────────────────────── يوحنا الثالثة ────────────────────────────
  "يوحنا الثالثة-1": "VuyaQsA9QXE",

  // ──────────────────────────── يهوذا ────────────────────────────
  "يهوذا-1": "xdCug0qp9Yk",

  // ──────────────────────────── رؤيا يوحنا ────────────────────────────
  "رؤيا يوحنا-1":  ["76Jr6UNo7Ag", "jCIpyxYrQV0", "gncAXCO1E-M"],
  "رؤيا يوحنا-2":  ["breEPrUotgQ", "ttyOzSZY8c8", "ACGvQuCaZTI"],
  "رؤيا يوحنا-3":  ["OPp9kEnCSGA", "pIbFcML5tfU", "PExyr_c7nDs"],
  "رؤيا يوحنا-4":  ["U-VPFGIelMs", "2bNS1pwxZtU"],
  "رؤيا يوحنا-5":  "MAc3LzXCS1o",
  "رؤيا يوحنا-6":  "09NUxDGW6B8",
  "رؤيا يوحنا-7":  "jGcISNZeRoE",
  "رؤيا يوحنا-8":  "JPgfqkd7wTY",
  "رؤيا يوحنا-9":  "8sh-zbkxBwM",
  "رؤيا يوحنا-10": "ShlQt_LlO_s",
  "رؤيا يوحنا-11": ["WeTeAj_5DS0", "l8leqkBX340"],
  "رؤيا يوحنا-12": "UQvi8YXXCtU",
  "رؤيا يوحنا-13": ["ThxdxPsM09U", "eItZt7rKBMc"],
  "رؤيا يوحنا-14": "4mleH60vGK8",
  "رؤيا يوحنا-15": "aQrYgfsQs_E",
  "رؤيا يوحنا-16": "_7q7myp7fzc",
  "رؤيا يوحنا-17": "Db8e1HILm8Y",
  "رؤيا يوحنا-18": "uzWv2ofQCwk",
  "رؤيا يوحنا-19": ["RaZGLSNXUL0", "5YkKuZ5BVcs"],
  "رؤيا يوحنا-20": "GwC0cQ3Ts3s",
  "رؤيا يوحنا-21": ["ND-heQONFjE", "x5Kn6pqiE2Y"],
  "رؤيا يوحنا-22": "mcwd8f7665Q",

  // ──────────────────────────── الخروج ────────────────────────────
  "الخروج-1":  "X9n-EwMPXbk",
  "الخروج-2":  "0SYxD6vWJR0",
  "الخروج-3":  "hfWpV7Bio00",
  "الخروج-4":  "erzAp4oQRHo",
  "الخروج-5":  "1pre_QcmEEA",
  "الخروج-6":  "Ye9gr-m1Q-c",
  "الخروج-7":  "LLor2VivLvA",
  "الخروج-8":  "gzdR6GYKnsk",
  "الخروج-9":  "igx5Zvp9AoY",
  "الخروج-10": "AsOIkCybK9Q",
  "الخروج-11": "EDyGUYIG1DY",
  "الخروج-12": ["8b0xjwZYFbU", "QqazobNWNL4"],
  "الخروج-13": "keahPQRMpwc",
  "الخروج-14": "4QZhbbscRuw",
  "الخروج-15": "ai9ORXdoVok",
  "الخروج-16": "43Hc-wCZu_0",
  "الخروج-17": "Ma-s-0UiG0Y",
  "الخروج-18": "t-1FY7NEP9g",
  "الخروج-19": "PNR6FBN1X78",
  "الخروج-20": ["fM4y4gFXfJU", "HawJ8YMsVOI"],
  "الخروج-21": ["bcCROx6hKH4", "VNcpxnKHBZE"],
  "الخروج-22": "7nqEdC2JOy8",
  "الخروج-23": "l-6iqT8YWlw",
  "الخروج-24": "oR38TKCu72E",
  "الخروج-25": "3jPxpAlZDe0",
  "الخروج-26": "yiL_dbXDFnM",
  "الخروج-27": "yiL_dbXDFnM",
  "الخروج-28": "yiL_dbXDFnM",
  "الخروج-29": "yiL_dbXDFnM",
  "الخروج-30": "yiL_dbXDFnM",
  "الخروج-31": "yiL_dbXDFnM",
  "الخروج-32": ["yiL_dbXDFnM", "ZFbSX_wusrU"],
  "الخروج-33": "dwx2Fdx4BS4",
  "الخروج-34": ["hF-swXcjjf8", "BxQl1NJjUDM"],
  "الخروج-35": "BxQl1NJjUDM",
  "الخروج-36": "BxQl1NJjUDM",
  "الخروج-37": "BxQl1NJjUDM",
  "الخروج-38": "BxQl1NJjUDM",
  "الخروج-39": "BxQl1NJjUDM",
  "الخروج-40": "BxQl1NJjUDM",

  // ──────────────────────────── راعوث ────────────────────────────
  "راعوث-1": "6TtYxYw8erc",
  "راعوث-2": ["6TtYxYw8erc", "aVx6kkAoIQo"],
  "راعوث-3": "aVx6kkAoIQo",
  "راعوث-4": "aVx6kkAoIQo",

  // ──────────────────────────── صموئيل الثاني ────────────────────────────
  "صموئيل الثاني-1":  "hfle_WchGRA",
  "صموئيل الثاني-2":  "9tFIdzFUano",
  "صموئيل الثاني-3":  "fD3OMd1tnXc",
  "صموئيل الثاني-4":  "fD3OMd1tnXc",
  "صموئيل الثاني-5":  "ePzmCK-6RHs",
  "صموئيل الثاني-6":  "ePzmCK-6RHs",
  "صموئيل الثاني-7":  "SaEvKZCT1tc",
  "صموئيل الثاني-8":  "aMyDGcol3xc",
  "صموئيل الثاني-9":  "Swyl6xoMkfU",
  "صموئيل الثاني-10": "Swyl6xoMkfU",
  "صموئيل الثاني-11": "MkOhYgFqzNU",
  "صموئيل الثاني-12": "MkOhYgFqzNU",
  "صموئيل الثاني-13": "gKbsQJExyzc",
  "صموئيل الثاني-14": "2teZRDMtnIk",
  "صموئيل الثاني-15": "0LaBAV0SMmo",
  "صموئيل الثاني-16": "lf1zjR8m8CI",
  "صموئيل الثاني-17": "lf1zjR8m8CI",
  "صموئيل الثاني-18": "22MsfQSuDH0",
  "صموئيل الثاني-19": "22MsfQSuDH0",
  "صموئيل الثاني-20": ["9P-FY0822E8", "LhFTkeCgUVI"],
  "صموئيل الثاني-21": "cBFsCSzwz_Y",
  "صموئيل الثاني-22": ["rDodK0DAFRQ", "g9VJH5eAsMs"],
  "صموئيل الثاني-23": ["5LlGTD_sxkM", "Axxajryv8B4"],
  "صموئيل الثاني-24": "Y4orvz7_FBQ",

  // ──────────────────────────── الملوك الأول ────────────────────────────
  "الملوك الأول-1":  ["cW2WeZtKnP0", "vD9Cyxmibv0"],
  "الملوك الأول-2":  "Vv9S78XTYOA",
  "الملوك الأول-3":  "vW8R5Yx1Bok",
  "الملوك الأول-4":  "vW8R5Yx1Bok",
  "الملوك الأول-5":  "EbtNUsKfYoc",
  "الملوك الأول-6":  "EbtNUsKfYoc",
  "الملوك الأول-7":  "5jVrvNm-O8w",
  "الملوك الأول-8":  "dCddGeK8MCM",
  "الملوك الأول-9":  "Y0ttlYZVekw",
  "الملوك الأول-10": "MYIqPQu7KdA",
  "الملوك الأول-11": "ci0IrsvXV8Y",
  "الملوك الأول-12": "ci0IrsvXV8Y",
  "الملوك الأول-13": "cgw6WNzQpj8",
  "الملوك الأول-14": "cgw6WNzQpj8",
  "الملوك الأول-15": "5AcV5fsPRKk",
  "الملوك الأول-16": "pN9PcbYhGV0",
  "الملوك الأول-17": "pN9PcbYhGV0",
  "الملوك الأول-18": ["JvZl3VdfxSs", "nBpSR2VvU9o"],
  "الملوك الأول-19": "JefGD-faUp0",
  "الملوك الأول-20": "hxbI8rAjzys",
  "الملوك الأول-21": "QFFtsesgUWs",
  "الملوك الأول-22": "20RqkiJBSqw",

  // ──────────────────────────── الملوك الثاني ────────────────────────────
  "الملوك الثاني-1":  "P6fjHiVtcvE",
  "الملوك الثاني-2":  "nbiHzSnUYsA",
  "الملوك الثاني-3":  "dltklIBuDss",
  "الملوك الثاني-4":  "S_jaZA4lcCA",
  "الملوك الثاني-5":  "ANwhR7oa6Nw",
  "الملوك الثاني-6":  "jVpq3D1Vfm0",
  "الملوك الثاني-7":  "Fgeo4QiHbDA",
  "الملوك الثاني-8":  "Fgeo4QiHbDA",
  "الملوك الثاني-9":  "CRC70AGoFPM",
  "الملوك الثاني-10": "CRC70AGoFPM",
  "الملوك الثاني-11": "bPRCnIA5FJo",
  "الملوك الثاني-12": "bPRCnIA5FJo",
  "الملوك الثاني-13": "8jIFA9IVBh4",
  "الملوك الثاني-14": "8jIFA9IVBh4",
  "الملوك الثاني-15": "8jIFA9IVBh4",
  "الملوك الثاني-16": "8jIFA9IVBh4",
  "الملوك الثاني-17": "8jIFA9IVBh4",
  "الملوك الثاني-18": "Cf5alyqnnrw",
  "الملوك الثاني-19": "4keTVL4YCc0",
  "الملوك الثاني-20": "4keTVL4YCc0",
  "الملوك الثاني-21": "4keTVL4YCc0",
  "الملوك الثاني-22": "fx4QeINWsVQ",
  "الملوك الثاني-23": "fx4QeINWsVQ",
  "الملوك الثاني-24": "fx4QeINWsVQ",
  "الملوك الثاني-25": "fx4QeINWsVQ",

  // ──────────────────────────── عزرا ────────────────────────────
  "عزرا-1":  "n5kIaTNrKtw",
  "عزرا-2":  "n5kIaTNrKtw",
  "عزرا-3":  "AC6TIcETKSI",
  "عزرا-4":  "AC6TIcETKSI",
  "عزرا-5":  "A8_Uelul-n0",
  "عزرا-6":  "A8_Uelul-n0",
  "عزرا-7":  "A8_Uelul-n0",
  "عزرا-8":  "LaugUo4U8jQ",
  "عزرا-9":  "LaugUo4U8jQ",
  "عزرا-10": "LaugUo4U8jQ",

  // ──────────────────────────── نحميا ────────────────────────────
  "نحميا-1":  "m_7_UXXMKNc",
  "نحميا-2":  "m_7_UXXMKNc",
  "نحميا-3":  "m_7_UXXMKNc",
  "نحميا-4":  "m_7_UXXMKNc",
  "نحميا-5":  "QlSWpNQyW9M",
  "نحميا-6":  "QlSWpNQyW9M",
  "نحميا-7":  "QlSWpNQyW9M",
  "نحميا-8":  "QlSWpNQyW9M",
  "نحميا-9":  "QlSWpNQyW9M",
  "نحميا-10": "HwOq7bMQ6dU",
  "نحميا-11": "HwOq7bMQ6dU",
  "نحميا-12": "HwOq7bMQ6dU",
  "نحميا-13": "HwOq7bMQ6dU",

  // ──────────────────────────── أستير ────────────────────────────
  "أستير-1":  "-9BKUY73np0",
  "أستير-2":  "IM4rV6-7iZ0",
  "أستير-3":  "IM4rV6-7iZ0",
  "أستير-4":  "IM4rV6-7iZ0",
  "أستير-5":  "zKN-uvq0XkQ",
  "أستير-6":  "zKN-uvq0XkQ",
  "أستير-7":  "xGNQ-iythWs",
  "أستير-8":  "xGNQ-iythWs",
  "أستير-9":  "wGQbMGvixkc",
  "أستير-10": "wGQbMGvixkc",

  // ──────────────────────────── الجامعة ────────────────────────────
  "الجامعة-1":  "81K5TWUIPB0",
  "الجامعة-2":  "81K5TWUIPB0",
  "الجامعة-3":  "yvHdWrSX0d4",
  "الجامعة-4":  "yvHdWrSX0d4",
  "الجامعة-5":  "yvHdWrSX0d4",
  "الجامعة-6":  "aMSA451ChyU",
  "الجامعة-7":  "aMSA451ChyU",
  "الجامعة-8":  "kyzqgMbLUNk",
  "الجامعة-9":  "kyzqgMbLUNk",
  "الجامعة-10": "0tIeVr2FXVY",
  "الجامعة-11": "jKnScAMhlKs",
  "الجامعة-12": "jKnScAMhlKs",

  // ──────────────────────────── إشعياء ────────────────────────────
  "إشعياء-1":  ["5MsVxTwSFqs", "Gu_FNBNJp20", "lSQWB5j4TU8"],
  "إشعياء-2":  ["dVmayM5LYXg", "VEqbI6FStvU"],
  "إشعياء-3":  ["vD-61Xg7s7w", "iBd-bF_VmN0"],
  "إشعياء-4":  ["iBd-bF_VmN0", "AsQN741lhcE"],
  "إشعياء-5":  ["AsQN741lhcE", "AJpHGyau-Ec", "Ms4IIyJ9THU"],
  "إشعياء-6":  "RnseXAZofkI",
  "إشعياء-7":  ["-b8j4yoQ6_I", "Nayj3OZey6s"],
  "إشعياء-8":  ["Nayj3OZey6s", "kmlmqSi_GYM"],
  "إشعياء-9":  ["kmlmqSi_GYM", "v6cz8oG-CV4"],
  "إشعياء-10": ["v6cz8oG-CV4", "FIpADulBUrQ"],
  "إشعياء-11": ["FIpADulBUrQ", "zwsZ2xNQBXk"],
  "إشعياء-12": ["zwsZ2xNQBXk", "pMU0LbbtbMM"],
  "إشعياء-13": "pMU0LbbtbMM",
  "إشعياء-14": "VjxE3cKbt3E",
  "إشعياء-15": "Etwp9jRhtm8",
  "إشعياء-16": "Etwp9jRhtm8",
  "إشعياء-17": "Z7KZe_kH4-U",
  "إشعياء-18": "Z7KZe_kH4-U",
  "إشعياء-19": "yHkUFSXy5FM",
  "إشعياء-20": "yHkUFSXy5FM",
  "إشعياء-21": "bso5NC1-Xu0",
  "إشعياء-22": "bso5NC1-Xu0",
  "إشعياء-23": "2Opn-UGAiuw",
  "إشعياء-24": ["2Opn-UGAiuw", "ep6X5N9XThM"],
  "إشعياء-25": ["ep6X5N9XThM", "FWlj-A6AxRw"],
  "إشعياء-26": ["FWlj-A6AxRw", "EiPPK6HV_O4", "eokN_OY1wos"],
  "إشعياء-27": "-Hkw51oiH0Q",
  "إشعياء-28": ["-Hkw51oiH0Q", "xli9HCsShyo", "QFgwwtzlOw8", "4MiGTWnGZ2w"],
  "إشعياء-29": ["4MiGTWnGZ2w", "4ENqpLeNVM8"],
  "إشعياء-30": ["4ENqpLeNVM8", "PJ7aCCYH08s", "BRi7SuxjHhA"],
  "إشعياء-31": "BRi7SuxjHhA",
  "إشعياء-32": "lDwmoCrouYE",
  "إشعياء-33": "9JZCjhXIgds",
  "إشعياء-34": "9JZCjhXIgds",
  "إشعياء-35": "8HgdDvrNkO8",
  "إشعياء-36": "8HgdDvrNkO8",
  "إشعياء-37": "BOt02J3ND7Q",
  "إشعياء-38": ["BOt02J3ND7Q", "F8NPkuDIqNE"],
  "إشعياء-39": "F8NPkuDIqNE",
  "إشعياء-40": ["jkjas93jIeY", "dY9WFTudjF4"],
  "إشعياء-41": ["dY9WFTudjF4", "au0cyUOHnmk", "irgILSg1PSY"],
  "إشعياء-42": ["irgILSg1PSY", "WPUGw-LF-jA"],
  "إشعياء-43": ["WPUGw-LF-jA", "gSm-fS64S3Y"],
  "إشعياء-44": ["4eHP_-_aR4g", "rQ2NhWVr4xw"],
  "إشعياء-45": ["rQ2NhWVr4xw", "_9zfNYwHwGk"],
  "إشعياء-46": ["_9zfNYwHwGk", "-rsfznEX6i4"],
  "إشعياء-47": "-rsfznEX6i4",
  "إشعياء-48": "jDrjc4iJGkE",
  "إشعياء-49": ["QHouvnvSPr4", "2DzhtOVyBSo"],
  "إشعياء-50": ["2DzhtOVyBSo", "tq8-wwBTnoU"],
  "إشعياء-51": ["tq8-wwBTnoU", "IBvR3wDt6FU"],
  "إشعياء-52": ["WJjftJF9nSY", "5Xv2DiTxJ_w"],
  "إشعياء-53": ["76NUydk4vOc", "OauQm6yRGT8", "dbHrHrM-4jY"],
  "إشعياء-54": ["dbHrHrM-4jY", "tu95jM_kN78"],
  "إشعياء-55": ["bkETxdxBqHs", "GGBHAquHjDE"],
  "إشعياء-56": ["GGBHAquHjDE", "YwXw7IXWo0I"],
  "إشعياء-57": ["YwXw7IXWo0I", "v9us0gPqmlQ"],
  "إشعياء-58": "v9us0gPqmlQ",
  "إشعياء-59": "x78HcD0sM_4",
  "إشعياء-60": ["x78HcD0sM_4", "PT337XZCBis"],
  "إشعياء-61": "V1RDkWqLgHs",
  "إشعياء-62": "uvPj6eHjUNs",
  "إشعياء-63": ["xmYhMMKSU2Y", "mPtq6fUqu50"],
  "إشعياء-64": ["mPtq6fUqu50", "5w9lDg9na-4"],
  "إشعياء-65": ["5w9lDg9na-4", "90bBXiBe45M"],
  "إشعياء-66": ["90bBXiBe45M", "jtNtV1TRsko"],

  // ──────────────────────────── إرميا ────────────────────────────
  "إرميا-1":  "fG8J3RtIP00",
  "إرميا-2":  "cHa0-uKlIKY",
  "إرميا-3":  "rYC_fLqU8SM",
  "إرميا-4":  "UMBUwvUQu7A",
  "إرميا-5":  "kNc3nIyijUU",
  "إرميا-6":  "bzgqb0E__oo",
  "إرميا-7":  "Hlq7hd-jtj4",
  "إرميا-8":  "DLm8OiR1cUY",
  "إرميا-9":  "0VY3futQLCs",
  "إرميا-10": "0pCcYPuG_h4",
  "إرميا-11": "_TdG-0MrHz4",
  "إرميا-12": "OOPmkKlOuXU",
  "إرميا-13": "LTb2XZ4-QHk",
  "إرميا-14": "RhS3P4lSziE",
  "إرميا-15": "RVgVYJ4zitw",
  "إرميا-16": "ja_QHArNQ8c",
  "إرميا-17": "ecuOYYYU6Z0",
  "إرميا-18": "-5fLksQzd9c",
  "إرميا-19": "5wu7BDsEUfo",
  "إرميا-20": "CGu2PgOFdlM",
  "إرميا-21": "RKNcN_aPBAY",
  "إرميا-22": "sKae-ZCmx6Q",
  "إرميا-23": "FptpCnNeHjk",
  "إرميا-24": "UPtnkJYoQhc",
  "إرميا-25": "4ow2zWDA9K8",
  "إرميا-26": "CEedHv1CrRs",
  "إرميا-27": "ate7aaCDGMM",
  "إرميا-28": "eOj0igYHQ4E",
  "إرميا-29": "wKjFylpclNg",
  "إرميا-30": "Pj9xQsac7dI",
  "إرميا-31": "sE9ChmMDEbM",
  "إرميا-32": "hDY9d3nm3ow",
  "إرميا-33": "-3G7BQ0T-xI",
  "إرميا-34": "bKWs2xdBLdU",
  "إرميا-35": "1Aql5YnyPyg",
  "إرميا-36": "b2Fgu1awbMo",
  "إرميا-37": "H8d2NkXniug",
  "إرميا-38": "FoAWW4IhhQ8",
  "إرميا-39": "TM2ijumbYp4",
  "إرميا-40": "J7PL6a6CZCk",
  "إرميا-41": "rn2SLR6DNaM",
  "إرميا-42": "ZIBVmvsoHPc",
  "إرميا-43": "26Ccli9GLhI",
  "إرميا-44": "ug9BkprE728",
  "إرميا-45": "Ak1e6qo3iFg",
  "إرميا-46": "9fBviJBPkCM",
  "إرميا-47": "RR5mqZI5zFw",
  "إرميا-48": "SQCcbMcMmvM",
  "إرميا-49": "zolmK-9fDZU",
  "إرميا-50": "L4v-1lwrh4U",
  "إرميا-51": "TUtZzj6-2fI",
  "إرميا-52": "Yxq_IFHA0RI",

  // ──────────────────────────── مراثي إرميا ────────────────────────────
  "مراثي إرميا-1": ["EgnZyuDVofY", "uUroQW3i6ZI"],
  "مراثي إرميا-2": ["uUroQW3i6ZI", "Wj0H_Lsdlpw"],
  "مراثي إرميا-3": ["Wj0H_Lsdlpw", "5Lu19AXHH3g", "JHAQbcbSGl8", "w5_Emh3e15I"],
  "مراثي إرميا-4": "w5_Emh3e15I",

  // ──────────────────────────── دانيال ────────────────────────────
  "دانيال-1":  ["nb-mHrsQzwM", "ivojsaLq1c4"],
  "دانيال-2":  ["ivojsaLq1c4", "S9-DUFZOOJk"],
  "دانيال-3":  "S9-DUFZOOJk",
  "دانيال-4":  ["qcnZvfbahtI", "hfE4eRBg-r0"],
  "دانيال-5":  "hfE4eRBg-r0",
  "دانيال-6":  "Bv8COjyyjwI",
  "دانيال-7":  ["hv91zVdFSkI", "bg7ys3RWdoY"],
  "دانيال-8":  ["bg7ys3RWdoY", "hhNl_DaAfoc"],
  "دانيال-9":  ["ZcoFV9BuJGc", "85AKbDMZvs0", "aQyWto992LA"],
  "دانيال-10": ["aQyWto992LA", "XnGZXroOvA0"],
  "دانيال-11": ["XnGZXroOvA0", "w378QXyZpFo"],
  "دانيال-12": "w378QXyZpFo",

};

/**
 * Returns the static video ID(s) for a given book + chapter, or undefined.
 */
export function getStaticLesson(
  bookName: string,
  chapter: number
): string[] | undefined {
  const key = `${bookName}-${chapter}`;
  const val = staticLessonVideos[key];
  if (!val) return undefined;
  return Array.isArray(val) ? val : [val];
}
