/**
 * Static lesson video mapping for Daoud Lamei's Bible explanations.
 * Key format: "BookName-Chapter"  →  YouTube videoId (string) or parts (string[])
 *
 * PRIMARY source — always overrides RSS results.
 * Auto-generated via scripts/fetch-playlist-videos.mjs + manual additions.
 */
export const staticLessonVideos: Record<string, string | string[]> = {

  // ──────────────────────────── يشوع ────────────────────────────
  "يشوع-1":  ["iVomctbKFi0", "PIk-uBXJrXE"],
  "يشوع-2":  ["PIk-uBXJrXE", "BEgM1FCFVD0"],
  "يشوع-3":  ["BEgM1FCFVD0", "zkTEYcfm3Dk"],
  "يشوع-4":  "zkTEYcfm3Dk",
  "يشوع-5":  "2GJxkfiUIDI",
  "يشوع-6":  ["2GJxkfiUIDI", "G6T6U3zCVv4"],
  "يشوع-7":  ["G6T6U3zCVv4", "vaI1EBMkJHg"],
  "يشوع-8":  ["vaI1EBMkJHg", "9TT3tyOSADY"],
  "يشوع-9":  "9TT3tyOSADY",
  "يشوع-10": ["6_peAx9WNTc", "DjTHuni91IU"],
  "يشوع-11": "DjTHuni91IU",
  "يشوع-12": "DjTHuni91IU",
  "يشوع-13": ["DjTHuni91IU", "tZsPd__fQTY"],
  "يشوع-14": "tZsPd__fQTY",
  "يشوع-15": "tZsPd__fQTY",
  "يشوع-16": "g2CbF4HIwqY",
  "يشوع-17": "g2CbF4HIwqY",
  "يشوع-18": "g2CbF4HIwqY",
  "يشوع-19": "g2CbF4HIwqY",
  "يشوع-20": "g2CbF4HIwqY",
  "يشوع-21": "TJGZBYNyXD0",
  "يشوع-22": "TJGZBYNyXD0",
  "يشوع-23": "GQsUuVslFfc",
  "يشوع-24": "GQsUuVslFfc",

  // ──────────────────────────── تكوين ────────────────────────────
  "تكوين-1":  ["YbwZQd7cpjU", "g1eVDttBOO0"],
  "تكوين-2":  "g1eVDttBOO0",
  "تكوين-3":  ["yLiOVybZHUA", "eJmWI5QWpAI", "vtprTE-ZXZ8"],
  "تكوين-4":  ["vtprTE-ZXZ8", "yyABXXSMRo8"],
  "تكوين-5":  ["yyABXXSMRo8", "VGUBB8pqaSM"],
  "تكوين-6":  ["VGUBB8pqaSM", "ma9_Fc6f9lA"],
  "تكوين-7":  ["F_vHHL9m6v4", "j8E8ivvO_EQ"],
  "تكوين-8":  "j8E8ivvO_EQ",
  "تكوين-9":  "j8E8ivvO_EQ",
  "تكوين-10": "x7PzEZ45Y1w",
  "تكوين-11": "x7PzEZ45Y1w",
  "تكوين-12": ["x7PzEZ45Y1w", "X9MJTtD3rO4", "9IcZWBNrxtE"],
  "تكوين-13": "9IcZWBNrxtE",
  "تكوين-14": ["9IcZWBNrxtE", "VripF1UBvYQ"],
  "تكوين-15": ["VripF1UBvYQ", "S-mwSW2zAdo"],
  "تكوين-16": ["S-mwSW2zAdo", "l1Hql6OiFHM"],
  "تكوين-17": "l1Hql6OiFHM",
  "تكوين-18": ["l1Hql6OiFHM", "ycdXACxPlhc"],
  "تكوين-19": ["ycdXACxPlhc", "u8S1Y0Dvk6U"],
  "تكوين-20": "u8S1Y0Dvk6U",
  "تكوين-21": "CNG1VbFOYQs",
  "تكوين-22": ["CNG1VbFOYQs", "_xlTcm0gz4w"],
  "تكوين-23": "_xlTcm0gz4w",
  "تكوين-24": ["_xlTcm0gz4w", "1cRQFnKEdag"],
  "تكوين-25": ["1cRQFnKEdag", "Ns-WrPjCqNk"],
  "تكوين-26": ["Ns-WrPjCqNk", "nlPEqDnwvoI"],
  "تكوين-27": ["nlPEqDnwvoI", "GvgxaoUNlfY"],
  "تكوين-28": "GvgxaoUNlfY",
  "تكوين-29": "pezRmjqzl3o",
  "تكوين-30": ["pezRmjqzl3o", "b-Vq0A2CuMM"],
  "تكوين-31": ["b-Vq0A2CuMM", "WNhC7MN0uhk"],
  "تكوين-32": ["WNhC7MN0uhk", "Vfc8ek7EBGw"],
  "تكوين-33": ["Vfc8ek7EBGw", "DUFv3jmRcjc"],
  "تكوين-34": "DUFv3jmRcjc",
  "تكوين-35": ["DUFv3jmRcjc", "HE3b7yfZkIg"],
  "تكوين-36": "HE3b7yfZkIg",
  "تكوين-37": ["HE3b7yfZkIg", "ICBUC8hnJH0"],
  "تكوين-38": "6VQm7d7J8h8",
  "تكوين-39": ["6VQm7d7J8h8", "q9vchp_D1Kc"],
  "تكوين-40": "q9vchp_D1Kc",
  "تكوين-41": ["gDFuiPxJTz8", "F3arDmAm0t4"],
  "تكوين-42": "F3arDmAm0t4",
  "تكوين-43": ["F3arDmAm0t4", "-Ccvbcaq-GQ"],
  "تكوين-44": "-Ccvbcaq-GQ",
  "تكوين-45": ["-Ccvbcaq-GQ", "6qX6BYkVsKY"],
  "تكوين-46": "6qX6BYkVsKY",
  "تكوين-47": "8lcTEOnauTE",
  "تكوين-48": "LDmcoWsPSb0",
  "تكوين-49": ["LDmcoWsPSb0", "0uHVuRkgM44", "vbFNDhEAcfw"],
  "تكوين-50": "vbFNDhEAcfw",

  // ──────────────────────────── تثنية ────────────────────────────
  "تثنية-1":  ["gbKLgO45ad4", "7BerIBlirnA", "6g13naEN5MA"],
  "تثنية-2":  ["6g13naEN5MA", "5AT0XvGd7D8"],
  "تثنية-3":  "5AT0XvGd7D8",
  "تثنية-4":  ["5AT0XvGd7D8", "lKUzg87TEH4", "J_KuqvTmLas"],
  "تثنية-5":  ["J_KuqvTmLas", "zBoHzfAzrVE"],
  "تثنية-6":  ["zBoHzfAzrVE", "lgSu71Urbvk"],
  "تثنية-7":  ["lgSu71Urbvk", "-3Iu7QSmTUw", "33eg7eMY0Ig"],
  "تثنية-8":  "33eg7eMY0Ig",
  "تثنية-9":  "Mf0-3nnw_dI",
  "تثنية-10": "oXOT9xYzmFI",
  "تثنية-11": "DyAjGc_i6NY",
  "تثنية-12": "aONnZ7BrVPI",
  "تثنية-13": "R1CPv-z1gtk",
  "تثنية-14": "7pSk7rKUqWw",
  "تثنية-15": ["7pSk7rKUqWw", "IyzDbh4M3I0"],
  "تثنية-16": ["IyzDbh4M3I0", "qLZpayoQAlo"],
  "تثنية-17": "qLZpayoQAlo",
  "تثنية-18": "7mkESNKri4U",
  "تثنية-19": "UoIcgRCgv5U",
  "تثنية-20": ["UoIcgRCgv5U", "p0wz9RNmeEw"],
  "تثنية-21": ["p0wz9RNmeEw", "SeHNgUKJiQg"],
  "تثنية-22": ["SeHNgUKJiQg", "4P6zUcmxHSg"],
  "تثنية-23": "4P6zUcmxHSg",
  "تثنية-24": "BXvabKUO69E",
  "تثنية-25": "Fj0AmJGKT_0",
  "تثنية-26": "yjeVMEGiY58",
  "تثنية-27": ["yjeVMEGiY58", "6ayFd-j9eSM"],
  "تثنية-28": ["8uxEl53MvV4", "252oVDveVao"],
  "تثنية-29": "RBz9U5NmWl4",
  "تثنية-30": "050CXqvG-iE",
  "تثنية-31": "tMrm7MBrVbg",
  "تثنية-32": "qQgjxFueNkM",
  "تثنية-33": ["Ryfeh1wHsh4", "QGxXUHpHzpY", "xsEP8xTrEGE", "MEGiAvMDlq4"],

  // ──────────────────────────── صموئيل أول ────────────────────────────
  "صموئيل أول-1":  ["BlidDmGrx-M", "XnhYxye6g6o", "J7aNHIe6aq0"],
  "صموئيل أول-2":  ["XnhYxye6g6o", "MRhKrMGFINg", "YOZzYQXHV5A"],
  "صموئيل أول-3":  ["MRhKrMGFINg", "U2-TyVQKHLM", "4jQDI-om2V8"],
  "صموئيل أول-4":  ["U2-TyVQKHLM", "4jQDI-om2V8"],
  "صموئيل أول-5":  ["U2-TyVQKHLM", "4jQDI-om2V8", "WDfxS52nyTI"],
  "صموئيل أول-6":  ["TSjMy3uGZTI", "WDfxS52nyTI", "d_92GJuUkk4"],
  "صموئيل أول-7":  ["TSjMy3uGZTI", "7oQSKdRXRkA", "d_92GJuUkk4", "YTlN4MtqyL8"],
  "صموئيل أول-8":  ["7oQSKdRXRkA", "YTlN4MtqyL8"],
  "صموئيل أول-9":  ["7oQSKdRXRkA", "N4TXOSknPpE", "1wALnvxTnek"],
  "صموئيل أول-10": ["N4TXOSknPpE", "c9YFeq5nMfk", "1wALnvxTnek"],
  "صموئيل أول-11": ["c9YFeq5nMfk", "wTzwKoXJcxk", "1wALnvxTnek", "8bEl6gcCn4E"],
  "صموئيل أول-12": ["wTzwKoXJcxk", "8bEl6gcCn4E", "3H8pRgE8TOU"],
  "صموئيل أول-13": ["wTzwKoXJcxk", "NMhpgbzM1S0", "3H8pRgE8TOU"],
  "صموئيل أول-14": ["NMhpgbzM1S0", "xaFCrXHAaFA", "ENiiBxU9xu0"],
  "صموئيل أول-15": ["xaFCrXHAaFA", "3x8-Vt_hql8", "ENiiBxU9xu0", "Errfe85ymfk"],
  "صموئيل أول-16": ["3x8-Vt_hql8", "Er43O6Z_byU", "Errfe85ymfk", "v6R-qVCclXg"],
  "صموئيل أول-17": ["Er43O6Z_byU", "qorYmlC7ods", "v6R-qVCclXg"],
  "صموئيل أول-18": ["qorYmlC7ods", "96SeEF_FoPg", "mRjkxoAor4s"],
  "صموئيل أول-19": ["96SeEF_FoPg", "KgqRVhfiIVY", "mRjkxoAor4s", "5UWOzXvKr9o"],
  "صموئيل أول-20": ["KgqRVhfiIVY", "5UWOzXvKr9o", "38rdzkTNok0"],
  "صموئيل أول-21": ["KgqRVhfiIVY", "DhktDB8w-TI", "38rdzkTNok0", "j-6KUE6gv3Y"],
  "صموئيل أول-22": ["DhktDB8w-TI", "gQU553E8hb4", "j-6KUE6gv3Y", "FKxhKqQTfDk", "WjZOWeVSuYs"],
  "صموئيل أول-23": ["gQU553E8hb4", "SxxiAFRi42A", "5x4qEuItp0Q"],
  "صموئيل أول-24": ["OIXnFKDGMn8", "leiqygcU4rQ"],
  "صموئيل أول-25": ["OIXnFKDGMn8", "BOMmPrvgxwQ", "N1mk39k3_UE"],
  "صموئيل أول-26": "N1mk39k3_UE",
  "صموئيل أول-27": "Bfi5TqPMY3w",
  "صموئيل أول-28": "Bfi5TqPMY3w",
  "صموئيل أول-29": "37c-FTyee0g",
  "صموئيل أول-30": "37c-FTyee0g",
  "صموئيل أول-31": "37c-FTyee0g",

  // ──────────────────────────── أيوب ────────────────────────────
  "أيوب-1":  ["In4Tl3KvKq4", "9lCEO-hhxUU", "zCxMqsz1FO4", "ndT58pv5EcE"],
  "أيوب-2":  ["22RphXQ4G94", "ndT58pv5EcE"],
  "أيوب-3":  "U8pO6Rf4kcs",
  "أيوب-5":  "dvrPLMMaKHU",
  "أيوب-6":  "4Ucf8FqNwWc",
  "أيوب-8":  "hzdHSw8FyYo",
  "أيوب-9":  "AwoP1Fsw-Ac",
  "أيوب-10": "LSsxVfzJzXU",
  "أيوب-12": "KWQokCr75zM",
  "أيوب-13": "JDCJ2d1Iou0",
  "أيوب-15": "lK48YvEKCpE",
  "أيوب-16": "JR6gLo0ipGg",
  "أيوب-18": "C6o8fdmyd20",
  "أيوب-20": "F1cUb0olUXk",
  "أيوب-22": "dXujzw0Iugg",
  "أيوب-24": "BUqHGQhFmaM",
  "أيوب-27": "7V0l3YOXmxk",
  "أيوب-29": "qKVaBzN1uO0",
  "أيوب-31": "hFRrNGvnISs",
  "أيوب-33": ["Z6lA1RZqwdU", "7hbY7UJ2oh0"],
  "أيوب-34": ["MmXmN62fA2Q", "7hbY7UJ2oh0", "KqAN3CatXuU"],
  "أيوب-35": ["dAlb59daWjc", "KqAN3CatXuU", "I1_JHA_ylCI"],
  "أيوب-36": "I1_JHA_ylCI",
  "أيوب-37": ["CNo8GjWfI-Q", "YYiG0pcRx5E"],
  "أيوب-38": ["XFscM-f4nBw", "YYiG0pcRx5E"],
  "أيوب-40": ["IiWNWjKfuLQ", "NEeJSAgBe5o"],
  "أيوب-41": ["4S4Mn3xgM5c", "NEeJSAgBe5o", "PNES_SPlg8U"],
  "أيوب-42": "PNES_SPlg8U",

  // ──────────────────────────── أمثال ────────────────────────────
  "أمثال-1":  ["BdxTNGAKy8E", "5CejNgWQkF0", "EQBpfD6s71k"],
  "أمثال-2":  ["EQBpfD6s71k", "z-RxkN4ypbc"],
  "أمثال-3":  ["z-RxkN4ypbc", "NgJIhnLYUmE", "ha_2gdKpqjE"],
  "أمثال-4":  ["ha_2gdKpqjE", "2lINQqimWWU"],
  "أمثال-5":  "Wa137mzu6_k",
  "أمثال-6":  ["kDJB0ZkLa7g", "7BCRQfOx7QI"],
  "أمثال-7":  "HkBqAvjbQTQ",
  "أمثال-8":  ["HkBqAvjbQTQ", "mDjTRjM1m3Y"],
  "أمثال-9":  "9RKk5a0Vgl4",
  "أمثال-10": ["9j5dx7xFMfg", "JeSmPXfO2WY", "nr4So7KwySc"],
  "أمثال-11": ["nr4So7KwySc", "B3E8LzcaZpo", "gcsya1OR0J8", "zz0HafLaz64"],
  "أمثال-12": ["zz0HafLaz64", "o4WEAPzXeCA"],
  "أمثال-13": ["o4WEAPzXeCA", "9fR-G-fFLc8", "1ZYk2XpKrCY"],
  "أمثال-14": ["1ZYk2XpKrCY", "qpnoOShVUmw", "nTbXlGcVkXc", "5xbhJNSWQlQ"],
  "أمثال-15": ["5xbhJNSWQlQ", "li4IJoDMdIg", "X5c5QmRGUck", "L7e37wQJWBw"],
  "أمثال-16": ["UgPpnQwQ6zU", "S_xC-H4kiZs"],
  "أمثال-17": ["S_xC-H4kiZs", "Em8F9trcn54", "ISV2-z05C4o"],
  "أمثال-18": ["ISV2-z05C4o", "bWKGKKNgqyU", "a5Ukgz4zGLA"],
  "أمثال-19": ["a5Ukgz4zGLA", "2dx27mLiyhg"],
  "أمثال-20": ["23Ee5OeQAs8", "QKYv-urMPKo", "RbePd4MnskA"],
  "أمثال-21": ["RbePd4MnskA", "EL_Xya0otww", "skY6Q5mhUGA"],
  "أمثال-22": "skY6Q5mhUGA",

  // ──────────────────────────── نشيد الأنشاد ────────────────────────────
  "نشيد الأنشاد-1": ["_XjOzT574C8", "lPBVYllExrI", "9SyFzmoKBD0"],
  "نشيد الأنشاد-2": ["9SyFzmoKBD0", "NClemO3PF6U", "uHZS8-ZJ8Ko"],
  "نشيد الأنشاد-3": ["uHZS8-ZJ8Ko", "CzirVSXX7f0"],
  "نشيد الأنشاد-4": ["CzirVSXX7f0", "pY_vQr1qJZ8", "os44ihcsOYs"],
  "نشيد الأنشاد-5": ["os44ihcsOYs", "OE-yHzR_EuM", "H33RdU5eOz0"],
  "نشيد الأنشاد-6": ["DWj7ifzdF20", "8Ko27Ar2RWM", "Zk4Utx2DO3Y"],
  "نشيد الأنشاد-7": ["Zk4Utx2DO3Y", "Zsb1_upMe3o", "4SS_3dYzXOs"],
  "نشيد الأنشاد-8": ["4SS_3dYzXOs", "tZ7DDjOsWNk"],

  // ──────────────────────────── حزقيال ────────────────────────────
  "حزقيال-3": "t2fzp1yrx5w",

  // ──────────────────────────── متى ────────────────────────────
  "متى-1":  ["znT5IMIAPW0", "qTpk3VSna54"],
  "متى-2":  ["P1YJhHI2x88", "yFQ1BjInAHk"],
  "متى-3":  ["ks6xcqQytEw", "ID5Lpmd5RAk"],
  "متى-4":  ["v49yoKufL98", "pdw4mZvmQew"],
  "متى-5":  ["U0feXv_h6pY", "YAI1fwFPuvY", "oQ_Ij_c4d6E"],
  "متى-6":  ["UC1ZN8ybsKA", "YytQFn3R-ks", "5MqqqTBlhZM"],
  "متى-7":  ["M4Bv56CSfIk", "l55tpyE0eHI", "LTnserUuKWQ"],
  "متى-8":  "TZECto9zXUU",
  "متى-9":  ["BTKkGm2NH5E", "c-SWCzaL5Qs", "rNZQ2GboTDw"],
  "متى-10": ["LA1juS18ahw", "QyyWX3vYh3Y"],
  "متى-11": ["8FEDWo2gm_4", "cCxvE2esCo0"],
  "متى-12": ["ce9sPW4Odg0", "ajUGrw4bjp8"],
  "متى-13": ["b6iOZufLO1k", "aONdfEc8Lss", "qy7uyACza2Y"],
  "متى-14": ["rUqjy-9-pGc", "y473ba5rl98"],
  "متى-15": ["zgsvFO3sKdI", "2Mb_A0kv6eI"],
  "متى-16": "INhchVwu7cU",
  "متى-17": "9-t_8MYCd4w",
  "متى-18": ["nZ6PAndCatQ", "KWTRqmSPMSY"],
  "متى-19": ["koY2XIV5104", "0VhhaS0cIQ0"],
  "متى-20": "XvgxLXrtnGw",
  "متى-21": ["6SaCmIT0H6I", "3wI3BE05BBs"],
  "متى-22": ["EgWHIPsOpZc", "7Cu2IUfpyq0"],
  "متى-23": ["f58SSaonfWM", "lFBXYKGkUKc"],
  "متى-24": ["dJjlfKqN044", "Fz5MuRN6pQw"],
  "متى-25": "cegV_BKhd7g",
  "متى-26": ["QVJuhDs3lNY", "7G_U0KsdkMI", "iM4RbCMJ7pw"],
  "متى-27": ["TNpIOpqsFGw", "xPxiuzTmTXc"],

  // ──────────────────────────── لوقا ────────────────────────────
  "لوقا-1":  ["Ix-ZF-LDk-E", "OA8b_qh5vtw", "8CJIMLAdfOE"],
  "لوقا-2":  "XMv3APN_VLY",
  "لوقا-3":  "ZjL5HnfEEvE",
  "لوقا-5":  "5czMFM4DEdo",
  "لوقا-6":  "nX6SLnMdBeI",
  "لوقا-7":  "eje8L77fju4",
  "لوقا-8":  ["Tenq8aJwkLc", "MGs5VidjSZw"],
  "لوقا-9":  ["AjWRWYFCzxM", "29FRBaLN1SA"],
  "لوقا-11": "eqtWlFr9qJ4",
  "لوقا-12": "Zcj77931oeg",
  "لوقا-13": "QcQBrZWZOoY",
  "لوقا-14": "xCoCrg-sStM",
  "لوقا-16": "90wtweg7JxU",
  "لوقا-18": "1wqmBXatDtI",
  "لوقا-19": "V-OyaTIP1FU",

  // ──────────────────────────── يوحنا ────────────────────────────
  "يوحنا-1":  ["DJhIwatChEo", "pSUzBYlmnoc", "1lGVZ2grVqI", "Ug6HF2dfMNQ"],
  "يوحنا-2":  ["0XQstzgDf4E", "KVSacNy6x2k"],
  "يوحنا-3":  ["IwyZewOC-28", "926aDoxaVu4", "axfpDi_gG5o"],
  "يوحنا-4":  ["a-WJLXhgOms", "gFqXBqB2AGk", "5pIaX0RzDF8"],
  "يوحنا-5":  ["ERcpvGInqC8", "K_cODxOCfeE"],
  "يوحنا-6":  ["fA-HzRmL97s", "Tp1vBYlnxa0", "BHTaHgkaaiI"],
  "يوحنا-7":  "ffUR9_WwZZc",
  "يوحنا-8":  ["QPslyNSZMEw", "MPTVYLJqpnw", "C5ITpMqK-Gc"],
  "يوحنا-9":  "Ko6-jSGhNAI",
  "يوحنا-10": ["By1DnIPIk5I", "aPON6WD9fCA"],
  "يوحنا-11": ["5AjX4IXwQ4I", "_I_QoIgpC-c", "KGC2TFkig0I"],
  "يوحنا-12": ["fpA48gVTbWY", "PahHkIO1vV4", "F96G6g_rlgs"],
  "يوحنا-13": "dk8bGPiHruY",
  "يوحنا-14": ["NVnP5j8juA8", "JZz6ATjp86c"],
  "يوحنا-15": ["oQDMnQxEEW4", "ejvZidsvv-o"],
  "يوحنا-16": ["ANxEppK3N50", "wcot4oXQvKs"],
  "يوحنا-17": ["qqxxaxs1rQc", "dVIpTlGVIVo", "BWTqAYBony0", "M3D6AzEjjqI", "SKJmuAx7Avc", "SRg6Dg0Y0NM"],
  "يوحنا-18": ["Z18mZKlydG8", "YxJ4PfBTBqY"],
  "يوحنا-19": "2z2mcyDfbos",
  "يوحنا-20": ["e3ftIm6GU5I", "O2tkjDNmzLs"],
  "يوحنا-21": "pbxXEQ903Ww",

  // ──────────────────────────── أعمال الرسل ────────────────────────────
  "أعمال الرسل-27": "rPPe4yxuPXs",
  "أعمال الرسل-28": "rPPe4yxuPXs",

};

/**
 * Returns the static video ID(s) for a given book + chapter, or undefined.
 */
export function getStaticLesson(
  bookName: string,
  chapter: number
): string[] | undefined {
  const key = `${bookName}-${chapter}`;
  const val = staticLessonVideos[key];
  if (!val) return undefined;
  return Array.isArray(val) ? val : [val];
}
