export interface KidsVideo {
  id: string;
  title: string;
  youtubeId: string;
  keywords: string[];
  category: string;
}

const kidsStoriesVideos: KidsVideo[] = [
  {
    id: "adam-eve",
    title: "حكاية آدم وحواء وبداية الخليقة",
    youtubeId: "R2qW0MJlbEI",
    keywords: ["آدم", "حواء", "الخليقة", "البداية", "الله"],
    category: "قصص العهد القديم"
  },
  {
    id: "noah-ark",
    title: "حكاية فلك نوح",
    youtubeId: "s8YQNIJ0tOI",
    keywords: ["نوح", "الفلك", "الطوفان", "الطاعة"],
    category: "قصص العهد القديم"
  },
  {
    id: "cain-abel",
    title: "حكاية قايين وهابيل",
    youtubeId: "i_15QL9gr4k",
    keywords: ["قايين", "هابيل", "المحبة", "الغيرة"],
    category: "قصص العهد القديم"
  },
  {
    id: "abraham-2",
    title: "حكاية إبراهيم أبو الآباء (الجزء الثاني)",
    youtubeId: "LBndqPUDD1Y",
    keywords: ["إبراهيم", "الإيمان", "الطاعة"],
    category: "قصص العهد القديم"
  },
  {
    id: "abraham-3",
    title: "حكاية إبراهيم أبو الآباء (الجزء الثالث)",
    youtubeId: "RbdvcoL6mM8",
    keywords: ["إبراهيم", "الوعد", "البركة"],
    category: "قصص العهد القديم"
  },
  {
    id: "isaac-jacob",
    title: "حكاية أبونا إسحق (ولادة يعقوب وعيسو)",
    youtubeId: "j99239YwVLE",
    keywords: ["إسحق", "يعقوب", "عيسو", "العائلة"],
    category: "قصص العهد القديم"
  },
  {
    id: "joseph-1",
    title: "حكاية يوسف البار (الجزء الأول)",
    youtubeId: "SJh4Mzy9eWs",
    keywords: ["يوسف", "الأمانة", "الصبر"],
    category: "قصص العهد القديم"
  },
  {
    id: "joseph-full",
    title: "فيلم كارتون يوسف الصديق كامل",
    youtubeId: "JWuaAa1_h5U",
    keywords: ["يوسف", "الغفران", "حلم"],
    category: "قصص العهد القديم"
  },
  {
    id: "david-goliath",
    title: "حكاية داود وجليات",
    youtubeId: "V-7KjSTUos8",
    keywords: ["داود", "جليات", "الشجاعة", "الإيمان"],
    category: "قصص العهد القديم"
  },
  {
    id: "jonah-whale",
    title: "حكاية يونان النبي والحوت",
    youtubeId: "Zq3r8FcqL2A",
    keywords: ["يونان", "الحوت", "التوبة"],
    category: "قصص العهد القديم"
  },
  {
    id: "daniel-1",
    title: "دانيال والثلاثة فتية (الجزء الأول)",
    youtubeId: "A8Iy7kuWeUA",
    keywords: ["دانيال", "الإيمان", "الأمانة"],
    category: "سلسلة حكايات دانيال النبي"
  },
  {
    id: "daniel-2",
    title: "الثلاثة فتية في آتون النار (الجزء الثاني)",
    youtubeId: "PxoTqaXXOow",
    keywords: ["آتون النار", "حماية الله"],
    category: "سلسلة حكايات دانيال النبي"
  },
  {
    id: "daniel-4",
    title: "دانيال في جب الأسود (الجزء الرابع)",
    youtubeId: "j4n9NsUh_nw",
    keywords: ["دانيال", "الأسود", "الثقة بالله"],
    category: "سلسلة حكايات دانيال النبي"
  },
  {
    id: "susanna",
    title: "حكاية سوسنة العفيفة (الجزء الخامس)",
    youtubeId: "89aKXVr98D4",
    keywords: ["سوسنة", "الطهارة", "الحق"],
    category: "سلسلة حكايات دانيال النبي"
  },
  {
    id: "bel-dragon",
    title: "حكاية بال والتنين (الجزء السادس)",
    youtubeId: "KlqK8WyvqvA",
    keywords: ["دانيال", "عبادة الله"],
    category: "سلسلة حكايات دانيال النبي"
  },
  {
    id: "christmas",
    title: "حكاية البشارة وميلاد السيد المسيح",
    youtubeId: "v-NU3KQL-MM",
    keywords: ["ميلاد يسوع", "البشارة", "الفرح"],
    category: "حكايات من العهد الجديد وأمثال السيد المسيح"
  },
  {
    id: "zechariah",
    title: "حكاية زكريا وأليصابات ويوحنا المعمدان",
    youtubeId: "WuEZsF1xr24",
    keywords: ["زكريا", "أليصابات", "يوحنا المعمدان"],
    category: "حكايات من العهد الجديد وأمثال السيد المسيح"
  },
  {
    id: "samaritan-woman",
    title: "حكاية المرأة السامرية",
    youtubeId: "7FwucHOtrTU",
    keywords: ["السامرية", "المحبة", "الخلاص"],
    category: "حكايات من العهد الجديد وأمثال السيد المسيح"
  },
  {
    id: "prodigal-son",
    title: "حكاية الابن الضال",
    youtubeId: "QpwDhPGe42Q",
    keywords: ["الابن الضال", "التوبة", "الغفران"],
    category: "حكايات من العهد الجديد وأمثال السيد المسيح"
  },
  {
    id: "lost-sheep",
    title: "حكاية الخروف الضال",
    youtubeId: "fe7XLX0erfk",
    keywords: ["الخروف الضال", "الراعي الصالح"],
    category: "حكايات من العهد الجديد وأمثال السيد المسيح"
  },
  {
    id: "lost-coin",
    title: "حكاية الدرهم المفقود",
    youtubeId: "XfukQUCWwvg",
    keywords: ["الدرهم المفقود", "البحث", "الفرح"],
    category: "حكايات من العهد الجديد وأمثال السيد المسيح"
  },
  {
    id: "parables-collection",
    title: "تجميعة (الابن الضال والخروف الضال والدرهم المفقود)",
    youtubeId: "VED1O-La-xA",
    keywords: ["أمثال المسيح", "التوبة", "المحبة"],
    category: "حكايات من العهد الجديد وأمثال السيد المسيح"
  },
  {
    id: "zacchaeus-tax-collector",
    title: "قصة زكّا العشار - اتغير لما شاف يسوع",
    youtubeId: "bnCtTi9zuo0",
    keywords: ["زكا", "زكّا", "العشار", "يسوع", "التوبة", "التغيير", "الخلاص", "كرتون"],
    category: "حكايات من العهد الجديد وأمثال السيد المسيح"
  },
  {
    id: "lent-sunday-temptation",
    title: "أحد التجربة - كيف نقاوم الشيطان وننتصر؟",
    youtubeId: "WLJr2brdnqg",
    keywords: ["الصوم الكبير", "التجربة", "الشيطان", "الانتصار", "يسوع", "الإيمان"],
    category: "سلسلة آحاد الصوم الكبير"
  },
  {
    id: "lent-sunday-prodigal-son",
    title: "أحد الابن الضال - قصة التوبة والغفران",
    youtubeId: "c6GnSqeOqro",
    keywords: ["الصوم الكبير", "الابن الضال", "التوبة", "الغفران", "الأب", "العودة"],
    category: "سلسلة آحاد الصوم الكبير"
  },
  {
    id: "lent-sunday-samaritan-woman",
    title: "أحد السامرية - قصة المرأة السامرية عند البئر",
    youtubeId: "AyhGAxM-7js",
    keywords: ["الصوم الكبير", "السامرية", "البئر", "يسوع", "الخلاص", "الماء الحي"],
    category: "سلسلة آحاد الصوم الكبير"
  },
  {
    id: "lent-sunday-paralyzed-man",
    title: "أحد المخلع - يسوع يشفي مريض بركة بيت حسدا",
    youtubeId: "9JC_LVWQVmU",
    keywords: ["الصوم الكبير", "المخلع", "الشفاء", "بيت حسدا", "يسوع", "المعجزة"],
    category: "سلسلة آحاد الصوم الكبير"
  },
  {
    id: "lent-sunday-blind-man",
    title: "أحد المولود أعمى - معجزة شفاء المولود أعمى",
    youtubeId: "iQuzUBh37Vs",
    keywords: ["الصوم الكبير", "المولود أعمى", "الشفاء", "يسوع", "المعجزة", "النور"],
    category: "سلسلة آحاد الصوم الكبير"
  },
  {
    id: "lent-sunday-treasures",
    title: "أحد الكنوز - قصة الكنز الحقيقي في الصوم الكبير",
    youtubeId: "9dmp4h8vq8k",
    keywords: ["الصوم الكبير", "الكنز", "السماء", "الأولويات", "القلب"],
    category: "سلسلة آحاد الصوم الكبير"
  },
  {
    id: "lent-sunday-palm-sunday",
    title: "أحد الشعانين - دخول يسوع أورشليم بالتهليل",
    youtubeId: "Rbt8Xrat7Bg",
    keywords: ["الصوم الكبير", "الشعانين", "أورشليم", "يسوع", "الزعف", "التهليل"],
    category: "سلسلة آحاد الصوم الكبير"
  },
  {
    id: "lent-sunday-resurrection",
    title: "المسيح قام! - أحد القيامة المجيد",
    youtubeId: "JI9ZUeQgOrM",
    keywords: ["القيامة", "المسيح قام", "الفصح", "الحياة", "النور", "الانتصار", "الموت اتهزم"],
    category: "سلسلة آحاد الصوم الكبير"
  },
  {
    id: "creation-in-the-beginning",
    title: "في البدء خلق الله! - أيام الخليقة",
    youtubeId: "0V6kHypl99w",
    keywords: ["الخليقة", "في البدء", "الله", "السماء", "الأرض", "الكون", "الأيام السبعة"],
    category: "قصص العهد القديم"
  },
  {
    id: "adam-eve-the-fall",
    title: "قصة آدم وحواء وسر السقوط",
    youtubeId: "1ZwC1GRhPMI",
    keywords: ["آدم", "حواء", "السقوط", "قايين", "هابيل", "الجنة", "الخطية"],
    category: "قصص العهد القديم"
  },
  {
    id: "noah-rainbow",
    title: "قصة نوح وقوس قزح",
    youtubeId: "6Ngitlk-trI",
    keywords: ["نوح", "قوس قزح", "الفلك", "الطوفان", "الوعد", "الله"],
    category: "قصص العهد القديم"
  },
  {
    id: "jonah-whale",
    title: "يونان النبي في بطن الحوت وتوبة أهل نينوى",
    youtubeId: "LVM61hA6a78",
    keywords: ["يونان", "الحوت", "نينوى", "التوبة", "الطاعة", "النبي", "العناية"],
    category: "قصص العهد القديم"
  },
  {
    id: "jonah-song",
    title: "ترنيمة يونان والحوت",
    youtubeId: "QpBise28R6c",
    keywords: ["يونان", "الحوت", "ترنيمة", "أغنية", "نينوى", "أطفال"],
    category: "قصص العهد القديم"
  },
  {
    id: "daniel-lions-den",
    title: "دانيال في جب الأسود - الشجاعة والثقة بالله",
    youtubeId: "hKG81Cq31fY",
    keywords: ["دانيال", "الأسود", "الإيمان", "الشجاعة", "الله", "الحماية", "جب الأسود"],
    category: "سلسلة حكايات دانيال النبي"
  },
  {
    id: "birth-of-jesus",
    title: "ميلاد الرب يسوع المسيح - أول يوم في حياة بابا يسوع",
    youtubeId: "G_JdJv3CgaA",
    keywords: ["ميلاد", "يسوع", "المسيح", "الكريسماس", "المغارة", "المجوس", "الرعاة"],
    category: "حكايات من العهد الجديد وأمثال السيد المسيح"
  },
  {
    id: "healing-lame-beautiful-gate",
    title: "شفاء الأعرج عند باب جميل - معجزة بطرس ويوحنا",
    youtubeId: "dLfk0zsseYE",
    keywords: ["الأعرج", "باب جميل", "بطرس", "يوحنا", "الشفاء", "المعجزة", "الرسل"],
    category: "حكايات من العهد الجديد وأمثال السيد المسيح"
  },
  {
    id: "virgin-mary-ascension",
    title: "قصة اصعاد جسد العذراء وازاي توما شافها",
    youtubeId: "2vmjXE7YBGU",
    keywords: ["العذراء", "مريم", "الاصعاد", "توما", "الرسول", "المعجزة"],
    category: "قصص العذراء والقديسين"
  },
  {
    id: "virgin-mary-childhood",
    title: "طفولة العذراء مريم وسر الطاعة في الهيكل",
    youtubeId: "y9obyQovTkQ",
    keywords: ["العذراء", "مريم", "الطفولة", "الهيكل", "الطاعة", "الله"],
    category: "قصص العذراء والقديسين"
  },
  {
    id: "virgin-mary-matias",
    title: "معجزة حل الحديد - العذراء مريم والقديس متياس الرسول",
    youtubeId: "ydUII1eWT8Q",
    keywords: ["العذراء", "مريم", "متياس", "الرسول", "المعجزة", "الحديد"],
    category: "قصص العذراء والقديسين"
  },
  {
    id: "saints-marina-damiana",
    title: "أسماء الشهيدات القديسات - مارينا ودميانة ومهرائيل",
    youtubeId: "AfDz0OERSmk",
    keywords: ["مارينا", "دميانة", "مهرائيل", "شهيدات", "قديسات", "الإيمان", "الاستشهاد"],
    category: "قصص العذراء والقديسين"
  },
  {
    id: "child-martyrs-heroes",
    title: "أطفال شهداء أبطال - أصغر أبطال الإيمان",
    youtubeId: "H6IH0wXhTnI",
    keywords: ["شهداء", "أطفال", "أبطال", "الإيمان", "الشجاعة", "القديسين"],
    category: "قصص العذراء والقديسين"
  },
  {
    id: "king-constantine-cross",
    title: "الملك قسطنطين وظهور الصليب - كيف عرف المسيح",
    youtubeId: "ErVIRIjy7vc",
    keywords: ["قسطنطين", "الصليب", "المسيحية", "الإيمان", "التاريخ", "الظهور"],
    category: "قصص العذراء والقديسين"
  },
  {
    id: "queen-helena-holy-cross",
    title: "قصة الملكة هيلانة واكتشاف الصليب المقدس",
    youtubeId: "j3ah-89V-Ok",
    keywords: ["هيلانة", "الصليب المقدس", "القدس", "الاكتشاف", "المعجزة", "التاريخ"],
    category: "قصص العذراء والقديسين"
  },
  {
    id: "nayrouz-adventures",
    title: "مغامرات مريم في عيد النيروز مع الشخصيات المسحورة",
    youtubeId: "BO363fOIkFM",
    keywords: ["النيروز", "السنة القبطية", "مريم", "مغامرات", "عيد", "أطفال"],
    category: "قصص وأناشيد متنوعة"
  },
  {
    id: "what-is-bible-keraза",
    title: "ما هو الكتاب المقدس؟ - محفوظات مهرجان الكرازة 2025",
    youtubeId: "CtirGbkt9PY",
    keywords: ["الكتاب المقدس", "الكرازة", "محفوظات", "تعليمي", "الكنيسة", "الكلمة"],
    category: "قصص وأناشيد متنوعة"
  }
];

// ── ترانيم للأطفال ────────────────────────────────────────────────────────
// ترانيم مصرية حديثة مشهورة من قنوات: الحياة الأفضل أطفال وكوجي TV
const kidsHymns: KidsVideo[] = [
  {
    id: "hymn-jesus-loves-me-cartoon",
    title: "ربي يسوع بيحبني (كارتون)",
    youtubeId: "Q4u8LMyEsiI",
    keywords: ["ترنيمة", "يسوع بيحبني", "كارتون", "الحياة الأفضل", "محبة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-if-you-love-jesus",
    title: "إن كنت تحب يسوع قول آمين (كارتون)",
    youtubeId: "a5WrYXgVd9s",
    keywords: ["ترنيمة", "إن كنت تحب يسوع", "آمين", "كارتون", "الحياة الأفضل"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-jesus-teach-me",
    title: "ربي يسوع علمني",
    youtubeId: "8J63MAsoelA",
    keywords: ["ترنيمة", "ربي يسوع علمني", "تعليم", "الحياة الأفضل", "أطفال"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-god-called-me",
    title: "ربنا كلمني - موسى أنا عايزك إنت",
    youtubeId: "-rqW2WQiHBA",
    keywords: ["ترنيمة", "ربنا كلمني", "موسى", "دعوة", "الحياة الأفضل", "أطفال"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-jesus-in-our-home",
    title: "يسوع في بيتنا",
    youtubeId: "G9r0Rd9sZuQ",
    keywords: ["ترنيمة", "يسوع في بيتنا", "البيت", "الحياة الأفضل", "أطفال"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-ana-farhan",
    title: "أنا فرحان (بالحركات)",
    youtubeId: "RHD08VjiooI",
    keywords: ["ترنيمة", "أنا فرحان", "فرح", "حركات", "أطفال"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-khelik-shagara",
    title: "خليك شجرة (كارتون)",
    youtubeId: "wAp76FaQt3o",
    keywords: ["ترنيمة", "خليك شجرة", "كارتون", "نمو", "أطفال", "2024"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-ana-momayaz",
    title: "أنا مميز",
    youtubeId: "eoW3qD_bkOE",
    keywords: ["ترنيمة", "أنا مميز", "هوية", "أطفال", "2023"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-atalammt",
    title: "اتعلمت - كورال الملائكة بنها",
    youtubeId: "WDaHVGM9XOA",
    keywords: ["ترنيمة", "اتعلمت", "كورال", "كوجي", "الملائكة", "بنها"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-ana-shaghal",
    title: "أنا شغال - كورال الملائكة بنها",
    youtubeId: "-uUSU-LVYo0",
    keywords: ["ترنيمة", "أنا شغال", "كورال", "كوجي", "خدمة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-salaamna-elaiky",
    title: "سلامنا اليكِ (كارتون)",
    youtubeId: "cuN_6Jj3Kaw",
    keywords: ["ترنيمة", "سلامنا اليكى", "كارتون", "كوجي", "العذراء"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-oaa-tekol",
    title: "أوعى تقول",
    youtubeId: "bUzUUPVgDng",
    keywords: ["ترنيمة", "أوعى تقول", "كوجي", "أطفال", "إيمان"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-etmasek",
    title: "إتمسك اللي عندك",
    youtubeId: "EigsIr3VNMw",
    keywords: ["ترنيمة", "إتمسك اللي عندك", "كوجي", "ثبات", "إيمان"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-asahsah",
    title: "أصحصح وأكون مستعد - قيثارة كيدز",
    youtubeId: "H6og_wKrF6k",
    keywords: ["ترنيمة", "أصحصح", "مستعد", "قيثارة كيدز", "كوجي", "استعداد"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-sabah-el-kheir",
    title: "صباح الخير يا بابا يسوع",
    youtubeId: "QlcnGtNH7As",
    keywords: ["ترنيمة", "صباح الخير", "يا بابا يسوع", "صباح", "صلاة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-enta-azeem",
    title: "إنت عظيم - فريق بيكوجى أنجيلوس",
    youtubeId: "_tMPWSGEu_U",
    keywords: ["ترنيمة", "إنت عظيم", "كوجي", "تسبيح", "مجد"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-milad-el-masih",
    title: "قصة ميلادك يا يسوع مش أي قصة (بالحركات)",
    youtubeId: "sOxYBvaGi_s",
    keywords: ["ترنيمة", "ميلاد يسوع", "الكريسماس", "بالحركات", "عيد"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-yousef-el-najjar",
    title: "يوسف النجار ده كان نجار (كرتون)",
    youtubeId: "RYu1cvQL9eo",
    keywords: ["ترنيمة", "يوسف النجار", "نجار", "كرتون", "TaranemToon"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-yesoa-zay-el-sokar",
    title: "يسوع زي السكر (كارتون)",
    youtubeId: "zMJNEBXgQkA",
    keywords: ["ترنيمة", "يسوع زي السكر", "كارتون", "الحياة الأفضل", "محبة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-tool-ma-el-shams",
    title: "طول ما الشمس فيها نور (كارتون)",
    youtubeId: "nvg4WKV-9KY",
    keywords: ["ترنيمة", "طول ما الشمس فيها نور", "كارتون", "نور", "شمس"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-hanta-hagga-helwa",
    title: "حنته حاجه حلوه قد البندقه (كارتون)",
    youtubeId: "8Zk560IfbB8",
    keywords: ["ترنيمة", "حنته", "حاجه حلوه", "البندقه", "كارتون"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-keniesty-hiya-beyty",
    title: "كنيستى هى بيتى (كارتون كوجي)",
    youtubeId: "6zkkT6OEP1c",
    keywords: ["ترنيمة", "كنيستى", "بيتى", "كوجي", "كارتون"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-habbet-ash",
    title: "حبة قش (كارتون كوجي)",
    youtubeId: "DqsMQb9VCDw",
    keywords: ["ترنيمة", "حبة قش", "كوجي", "كارتون", "تواضع"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-eid-milad",
    title: "عيد ميلاد",
    youtubeId: "w6tJXV-wWOM",
    keywords: ["ترنيمة", "عيد ميلاد", "ميلاد", "عيد", "أطفال", "أغنية"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-rehla-gamila",
    title: "رحلة جميلة ويا يسوع",
    youtubeId: "jma8AsQb8aM",
    keywords: ["ترنيمة", "رحلة جميلة", "يسوع", "أطفال", "فرح"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-fagr-yeshashsesh",
    title: "فجر يشقشق",
    youtubeId: "LcB2xjK5rYU",
    keywords: ["ترنيمة", "فجر يشقشق", "فجر", "صباح", "أطفال"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-el-masih-kam",
    title: "المسيح قام",
    youtubeId: "TpnJK2KPp5U",
    keywords: ["ترنيمة", "المسيح قام", "قيامة", "فرح", "أطفال"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-asghar-raey-daoud",
    title: "أصغر راعي داود",
    youtubeId: "q28cfZHEWAY",
    keywords: ["ترنيمة", "أصغر راعي", "داود", "شجاعة", "أطفال"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-ana-lazem-ashkor-raby",
    title: "أنا لازم أشكر ربي",
    youtubeId: "eY6txE8obFc",
    keywords: ["ترنيمة", "أنا لازم أشكر ربي", "شكر", "عبادة", "أطفال"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-01",
    title: "يا رسل المسيح",
    youtubeId: "AoDukPmrRBU",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "يا رسل", "المسيح"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-02",
    title: "لو روحت يمين او روحت شمال (كارتون)",
    youtubeId: "RyAa1_5Km7I",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "يمين", "شمال"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-03",
    title: "اتبع خطواتك يا يسوع (كارتون)",
    youtubeId: "EA0WBCadz2U",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "خطوات", "يسوع"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-04",
    title: "كان اصغر راعى داود (كارتون)",
    youtubeId: "-jRksilZNY4",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "داود", "راعى"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-05",
    title: "خمس خبزات و سمكتين (كارتون)",
    youtubeId: "dNFxk_wkuqg",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "خبزات", "سمكتين"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-06",
    title: "راعوث (كارتون)",
    youtubeId: "Ly0J4P2wa3g",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "راعوث", "وفاء"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-07",
    title: "حنة و صموئيل (كارتون)",
    youtubeId: "nKE0bR0-XCg",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "حنة", "صموئيل"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-08",
    title: "احنا جنود (كارتون)",
    youtubeId: "YnOEfv1wm5U",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "جنود", "إيمان"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-09",
    title: "طيرى طيرى يا عصفورة (كارتون)",
    youtubeId: "V-Ze-slxMBQ",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "عصفورة", "طير"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-10",
    title: "حكايات ربنا (كارتون)",
    youtubeId: "8OWkN3XKkw8",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "حكايات", "ربنا"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-11",
    title: "يشهد لك (كارتون)",
    youtubeId: "ROOaBBOVXB8",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "يشهد", "شهادة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-12",
    title: "كان طفل صغير (كارتون)",
    youtubeId: "kNftYWl8Wo4",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "طفل", "صغير"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-13",
    title: "انا مطمن انا متأكد (كارتون)",
    youtubeId: "B4ZEAYrJ9J8",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "مطمن", "متأكد"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-14",
    title: "شوفوا ربنا خلقنى حلو ازاى (كارتون)",
    youtubeId: "80jRxhxHbPU",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "خلقنى", "حلو"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-15",
    title: "قول لأ (كارتون)",
    youtubeId: "SLHBFGBZ61Q",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "قول", "لأ"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-16",
    title: "خلق الله الدنيا (كارتون)",
    youtubeId: "o3LnCeMynhI",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "خلق", "الدنيا"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-17",
    title: "قبل أيدينا تمد أيدك (كارتون)",
    youtubeId: "Q-8Hzm-PDZk",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "أيدينا", "أيدك"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-18",
    title: "يا محلى ايامنا يا يسوع (كارتون)",
    youtubeId: "kFuKjj9wXjE",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "ايامنا", "يسوع"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-19",
    title: "جوة حكايتك (كارتون)",
    youtubeId: "OCyXrH57KMo",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "جوة", "حكايتك"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-20",
    title: "للعذراء مريم ماما العدرا (كارتون)",
    youtubeId: "QMkN3MckJRY",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "العذراء", "مريم"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-21",
    title: "يا رمال الصحراء (كارتون)",
    youtubeId: "jQCWxWeF5ck",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "رمال", "الصحراء"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-22",
    title: "ياللى العصافير (كارتون)",
    youtubeId: "VLcuY8-viF4",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "العصافير", "الله"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-23",
    title: "فيا حته منه (كارتون)",
    youtubeId: "IAODX5mLEzE",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "فيا", "حته"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-24",
    title: "بارك بارك ربنا (كارتون)",
    youtubeId: "Y1Bt_Paem4A",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "بارك", "ربنا"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-25",
    title: "منك نتبارك (كارتون)",
    youtubeId: "srtcfJjgdO0",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "نتبارك", "بركة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-26",
    title: "ماما يا ماما (كارتون)",
    youtubeId: "YuNdsYb0KrU",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "ماما", "عيد الأم"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-27",
    title: "لو سألوني أصحابى (كارتون)",
    youtubeId: "SU5hkmZoCBs",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "سألوني", "أصحابى"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-28",
    title: "فيلومينا زى السكر (كارتون)",
    youtubeId: "oXapA-Q4WHk",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "فيلومينا", "السكر"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-29",
    title: "مش ممكن ينساني (كارتون)",
    youtubeId: "GLGJE-N7KaA",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "ينساني", "محبة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-30",
    title: "جعانة (كارتون)",
    youtubeId: "lOOJZdgCA94",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "جعانة", "خبز"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-31",
    title: "مغامرة جامدة (كارتون)",
    youtubeId: "_2UDuR19lfQ",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "مغامرة", "جامدة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-32",
    title: "ثمار الروح القدس (كارتون)",
    youtubeId: "MKYb_FG6T18",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "ثمار", "الروح القدس"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-33",
    title: "من طفولتي بحبها ماما العدرا (كارتون)",
    youtubeId: "-O4LeRyF1R8",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "العدرا", "طفولتي"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-34",
    title: "إيليا و عمل الخير (كارتون)",
    youtubeId: "qTyL6saB0aQ",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "إيليا", "الخير"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-35",
    title: "زكا (كارتون)",
    youtubeId: "n-E3DdJEjOc",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "زكا", "التوبة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-36",
    title: "انا لسه صغير (كارتون)",
    youtubeId: "u2lq2VRHOUw",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "صغير", "أطفال"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-37",
    title: "دعوا الأولاد (كارتون)",
    youtubeId: "tMUgGqNISck",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "الأولاد", "يسوع"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-38",
    title: "نوح (كارتون)",
    youtubeId: "kH6xb-LtSDs",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "نوح", "الفلك"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-39",
    title: "بإيديك الصغيرة (كارتون)",
    youtubeId: "_fpNy5W8Wvc",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "إيديك", "صغيرة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-40",
    title: "عايز زيت فى اللمبة (كارتون)",
    youtubeId: "KqpZrOXZnJc",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "زيت", "اللمبة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-41",
    title: "الرب معايا (كارتون)",
    youtubeId: "Gh6IeM1YNsg",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "الرب", "معايا"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-42",
    title: "م ر ي م (كارتون)",
    youtubeId: "gkVH5GR5c9I",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "مريم", "العذراء"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-43",
    title: "انا عصفور (كارتون)",
    youtubeId: "0LA32zGOtmY",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "عصفور", "خلق"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-44",
    title: "زى ما أيدنا (كارتون)",
    youtubeId: "eLu95O1B8O8",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "أيدنا", "صلاة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-45",
    title: "لو كنت فراشة (كارتون)",
    youtubeId: "NNwwOhWVw0I",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "فراشة", "خلق"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-46",
    title: "أرض كبيرة (كارتون)",
    youtubeId: "dxlpUajZgEI",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "أرض", "كبيرة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-47",
    title: "شمشون (كارتون)",
    youtubeId: "NhhDflDbZOc",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "شمشون", "قوة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-48",
    title: "يا مريم (كارتون)",
    youtubeId: "nAvs_F4AloI",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "مريم", "العذراء"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-49",
    title: "يا كنيسة الشهداء عيد النيروز (كارتون)",
    youtubeId: "WPcwmX2nFl8",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "النيروز", "الشهداء"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-50",
    title: "خلى بالك يا عينى (كارتون)",
    youtubeId: "0Ow85ZDfjAE",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "خلى بالك", "عينى"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-51",
    title: "أنتى البطلة عيد النيروز (كارتون)",
    youtubeId: "OnMdVPDCo2k",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "النيروز", "البطلة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-52",
    title: "دانيال (كارتون)",
    youtubeId: "S78qsHoTJVA",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "دانيال", "إيمان"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-53",
    title: "يارب احنا عبيدك (كارتون)",
    youtubeId: "HQ1KezpiknU",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "عبيدك", "صلاة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-54",
    title: "زقزق يا عصفوري عيد النيروز (كارتون)",
    youtubeId: "IAk6qAmum0Q",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "النيروز", "عصفوري"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-55",
    title: "صور صور لعيد النيروز (كارتون)",
    youtubeId: "QDYTfVgPj5k",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "النيروز", "صور"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-56",
    title: "أوعى تقول انا (كارتون)",
    youtubeId: "2C9I7nF2TwQ",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "أوعى", "تقول"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-57",
    title: "بحب الرب يسوع (كارتون)",
    youtubeId: "PKoxRnCQ8l8",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "بحب", "يسوع"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-58",
    title: "يا سمكة قوليلي (كارتون)",
    youtubeId: "zA0iGF9T2zs",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "سمكة", "يونان"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-59",
    title: "سألوني لما أكبر (كارتون)",
    youtubeId: "MlQYuCxV2GM",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "سألوني", "أكبر"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-60",
    title: "الاجران الستة (كارتون)",
    youtubeId: "Jmb3rpzFThw",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "الاجران", "عرس"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-61",
    title: "عايز ارنم (كارتون)",
    youtubeId: "ALfSQu4O_Ww",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "ارنم", "تسبيح"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-62",
    title: "احنا الاجران عرس قانا الجليل (كارتون)",
    youtubeId: "r6S7N3HRKjQ",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "قانا", "الجليل"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-63",
    title: "ليونان كان ياما كان (كارتون)",
    youtubeId: "ZO4OzthZmiA",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "يونان", "الحوت"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-64",
    title: "يونان و الطاعة (كارتون)",
    youtubeId: "BiFqtzT-AaQ",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "يونان", "الطاعة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-65",
    title: "احكيلنا بصوت اجراسك نيروز (كارتون)",
    youtubeId: "4Gw8JDQkqpM",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "نيروز", "اجراسك"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-66",
    title: "بالايمان عايش مصدق (كارتون)",
    youtubeId: "GpX1DKt9MSo",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "الايمان", "مصدق"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-67",
    title: "مارجرجس (كارتون)",
    youtubeId: "2FuIcUQA2lk",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "مارجرجس", "الشهيد"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-68",
    title: "عصافير ترانيم القيامة (كارتون)",
    youtubeId: "7P5oWVmkrA8",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "القيامة", "عصافير"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-69",
    title: "امي يا عدرا (كارتون)",
    youtubeId: "EBsdnXdcAUw",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "العدرا", "امي"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-70",
    title: "فوق السحاب (كارتون)",
    youtubeId: "ug-SK5njQzk",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "السحاب", "السماء"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-71",
    title: "بيت علي الصخر (كارتون)",
    youtubeId: "GuQ0sQbf_PY",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "الصخر", "البيت"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-72",
    title: "اتعلم تتسامح (كارتون)",
    youtubeId: "HYSinDlrDDw",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "تتسامح", "التسامح"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-73",
    title: "العدرا في كل مكان (كارتون)",
    youtubeId: "I0cQ5JoKwtg",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "العدرا", "مريم"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-74",
    title: "يسوع علمنا لما نصوم (كارتون)",
    youtubeId: "ZOlot4vesEg",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "نصوم", "الصوم"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-75",
    title: "يحكي تاريخنا (كارتون)",
    youtubeId: "VchWGvmr_ys",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "تاريخنا", "الكنيسة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-76",
    title: "ايوه بحبه (كارتون)",
    youtubeId: "ylib7UBtZaE",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "بحبه", "محبة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-77",
    title: "عنقود عنب (كارتون)",
    youtubeId: "MHX2X832yeY",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "عنقود", "عنب"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-78",
    title: "مثل الزارع (كارتون)",
    youtubeId: "kctV515m4Cw",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "الزارع", "البذرة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-79",
    title: "هخاف من ايه (كارتون)",
    youtubeId: "AKyNZ4RYhzs",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "هخاف", "ثقة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-80",
    title: "مريم تسمع لدعائنا (كارتون)",
    youtubeId: "zfVzJuonTto",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "مريم", "دعاء"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-81",
    title: "حبة حنطة (كارتون)",
    youtubeId: "7aobCJcGQNI",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "حنطة", "بذرة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-82",
    title: "ماشي معايا (كارتون)",
    youtubeId: "FXqv2oTfiH8",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "ماشي", "معايا"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-83",
    title: "اوعي تقول (كارتون)",
    youtubeId: "dKBe7lhadjQ",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "اوعي", "تقول"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-84",
    title: "فتش جوا كتابك (كارتون)",
    youtubeId: "ztgnT9nWGcs",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "كتابك", "الكتاب المقدس"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-85",
    title: "ادينى القوة (كارتون)",
    youtubeId: "4WXbsPQTrPs",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "القوة", "صلاة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-86",
    title: "ذقت سلامك (كارتون)",
    youtubeId: "DBcrF2a1kco",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "سلامك", "سلام"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-87",
    title: "خين ابشاي انتيه نيروز (كارتون)",
    youtubeId: "hpJKG9HXF1o",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "نيروز", "ابشاي"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-88",
    title: "مبني علي الصخر (كارتون)",
    youtubeId: "y4G7PFc8R0I",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "الصخر", "ثبات"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-89",
    title: "عاش ربي (كارتون)",
    youtubeId: "nMUNAoBkuIU",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "عاش", "القيامة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-90",
    title: "قابلوه حبوه (كارتون)",
    youtubeId: "13NNuTgEnc0",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "قابلوه", "حبوه"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-91",
    title: "أعظم خادم (كارتون)",
    youtubeId: "Ob7uRUhi36g",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "خادم", "خدمة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-92",
    title: "أجدع صاحب (كارتون)",
    youtubeId: "zcX6RT0FpO8",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "صاحب", "صداقة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-93",
    title: "كوجي لكن جوري (كارتون)",
    youtubeId: "dohoXWmItqg",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "كوجي", "جوري"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-94",
    title: "جمع الشعب (كارتون)",
    youtubeId: "YOKa24nFBVo",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "الشعب", "جمع"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-95",
    title: "من بالليل بصلي وأصوم (كارتون)",
    youtubeId: "T-MfiFEcuoU",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "بصلي", "أصوم"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-96",
    title: "اوعي تكشر (كارتون)",
    youtubeId: "bmUVrM6R3Ec",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "تكشر", "فرح"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-97",
    title: "ربي خلقني (كارتون)",
    youtubeId: "kBvJJ6YhnHg",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "خلقني", "الخلق"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-98",
    title: "قصة الخلاص (كارتون)",
    youtubeId: "nhiSs6tAaWs",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "الخلاص", "يسوع"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-99",
    title: "عقيدة قبطية أرثوذكسية",
    youtubeId: "rZOHL2v3Qjg",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "عقيدة", "قبطية"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-100",
    title: "بالامثال كلمنا (كارتون)",
    youtubeId: "p-ipbpo-rV8",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "الامثال", "الأمثال"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-101",
    title: "من قبل ما ابقي نونو (كارتون)",
    youtubeId: "K2BJG1sNjLI",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "نونو", "طفل"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-102",
    title: "الاطفال الابطال (كارتون)",
    youtubeId: "bCCmmyre_qg",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "الابطال", "أطفال"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-103",
    title: "ميدلي ثمار الروح القدس (كارتون)",
    youtubeId: "85mPpm3rnQQ",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "الروح القدس", "ميدلي"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-104",
    title: "زهرة الوادى للشهيدة دميانة (كارتون)",
    youtubeId: "M25kM34VmjE",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "دميانة", "زهرة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-105",
    title: "امير و فارس (كارتون)",
    youtubeId: "FtB1FHi9NTk",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "امير", "فارس"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-106",
    title: "لما يسوع بيكون موجود (كارتون)",
    youtubeId: "nySFmcgJKaw",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "يسوع", "موجود"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-107",
    title: "انت عظيم (كارتون)",
    youtubeId: "hq6bgv9wdyk",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "عظيم", "تسبيح"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-108",
    title: "انا بحبك ياربى (كارتون)",
    youtubeId: "TO5bdGjDfYQ",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "بحبك", "ربى"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-109",
    title: "انا عاوز اتغير (كارتون)",
    youtubeId: "fwGvOtqWOMk",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "اتغير", "تغيير"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-110",
    title: "كنز و مجد (كارتون)",
    youtubeId: "IRI3azPTV2E",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "كنز", "مجد"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-111",
    title: "٣ مجامع مسكونية (كارتون)",
    youtubeId: "_N28n_U5fC8",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "مجامع", "مسكونية"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-112",
    title: "عقيدة الثالوث (كارتون)",
    youtubeId: "aJWZFVISDuk",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "الثالوث", "عقيدة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-113",
    title: "داود الراعى (كارتون)",
    youtubeId: "EHx0oSuO9EY",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "داود", "الراعى"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-114",
    title: "انا نفسى اكون انسان نافع سلوكيات (كارتون)",
    youtubeId: "DGC4Zql4nPQ",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "نافع", "سلوكيات"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-115",
    title: "٧٠ كارز صوم و عيد الرسل (كارتون)",
    youtubeId: "W3X38Ywf8KQ",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "الرسل", "الصوم"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-116",
    title: "لينا صحاب ترنيمة تراثية عيد النيروز (كارتون)",
    youtubeId: "GriOmToG1zE",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "النيروز", "تراثية"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-117",
    title: "المسيح هو ابن الله (كارتون)",
    youtubeId: "JWR7BR1tKBE",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "المسيح", "ابن الله"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-118",
    title: "توتة ترانيم العدرا للاطفال (كارتون)",
    youtubeId: "twohAU3PS-8",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "العدرا", "توتة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-119",
    title: "قلب فريش (كارتون)",
    youtubeId: "AGh354A7VIU",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "قلب", "فريش"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-120",
    title: "المحبة (كارتون)",
    youtubeId: "NpG8iRomerQ",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "المحبة", "حب"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-121",
    title: "إله قادر (كارتون)",
    youtubeId: "xoChjV6a7nQ",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "قادر", "إله"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-122",
    title: "طوباكى طوباكى ترانيم العدرا للاطفال (كارتون)",
    youtubeId: "CCLpoKgusdA",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "طوباكى", "العدرا"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-123",
    title: "من بين القديسين ترانيم العدرا للاطفال (كارتون)",
    youtubeId: "Qr3d5xIIq1o",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "القديسين", "العدرا"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-124",
    title: "لما الرب بيدخل قلب (كارتون)",
    youtubeId: "qRPHHc9WuiM",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "الرب", "القلب"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-125",
    title: "انا فرحان لأنى مسيحى (كارتون)",
    youtubeId: "E32DdP0ktjY",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "فرحان", "مسيحى"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-126",
    title: "جرس كنيستنا دق (كارتون)",
    youtubeId: "gpEKd-3sKTo",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "جرس", "كنيسة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-127",
    title: "انا قبطى مسيحى ترانيم النيروز (كارتون)",
    youtubeId: "v32GXWjHGeU",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "قبطى", "النيروز"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-128",
    title: "سامع صلاتى (كارتون)",
    youtubeId: "lG46DGpzy30",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "سامع", "صلاتى"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-129",
    title: "صوت صارخ (كارتون)",
    youtubeId: "mmuDM5qjSsY",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "صوت", "صارخ"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-130",
    title: "و تعدى سنين و سنين للارشيذياكون حبيب جرجس (كارتون)",
    youtubeId: "LFc26Fe97DI",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "حبيب جرجس", "تراثية"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-131",
    title: "يلا يا مصر دخول الرب يسوع ارض مصر (كارتون)",
    youtubeId: "ikBYRjg3mIA",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "مصر", "يسوع"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-132",
    title: "بذرة ترانيم النيروز (كارتون)",
    youtubeId: "RZPkS_G2F0k",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "النيروز", "بذرة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-133",
    title: "إيليا النبى وأليشع تلميذه (كارتون)",
    youtubeId: "HQZ1I7KJiVs",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "إيليا", "أليشع"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-134",
    title: "نلتم الامجاد ترانيم نيروز (كارتون)",
    youtubeId: "SM6LqDU2Vks",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "نيروز", "الامجاد"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-135",
    title: "حبه حبه ترانيم المحبة (كارتون)",
    youtubeId: "t_uKe3ab1wc",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "المحبة", "حبه"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-136",
    title: "إلهنا حنين (كارتون)",
    youtubeId: "x9_kIC8lNlE",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "حنين", "إلهنا"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-137",
    title: "بنت مطيعة للعذراء مريم (كارتون)",
    youtubeId: "hPPMoo4GNos",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "مطيعة", "العذراء"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-138",
    title: "املا الدنيا فرح و سلام (كارتون)",
    youtubeId: "5L4w3gv5NeQ",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "فرح", "سلام"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-139",
    title: "اشكر ربك (كارتون)",
    youtubeId: "2QXYOyblcVQ",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "اشكر", "شكر"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-140",
    title: "اتفضل يا بابا يسوع (كارتون)",
    youtubeId: "nK-XHQ18tco",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "يسوع", "دعوة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-141",
    title: "لو قلبك مليان ايمان (كارتون)",
    youtubeId: "cgeHKwR4lRU",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "ايمان", "قلبك"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-142",
    title: "بغمض عيني (كارتون)",
    youtubeId: "i5xLWNU6ArE",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "عيني", "ثقة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-143",
    title: "بحبك (كارتون)",
    youtubeId: "xLurMfRIarE",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "بحبك", "محبة"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-144",
    title: "شفت النملة ترنيمة عن النظام (كارتون)",
    youtubeId: "AFeEff0AS_Q",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "النملة", "النظام"],
    category: "ترانيم للأطفال",
  },
  {
    id: "hymn-taranem-145",
    title: "قصة السمكة والكنيسة",
    youtubeId: "elnLLgLxM_Q",
    keywords: ["ترنيمة", "كارتون", "TaranemToon", "السمكة", "الكنيسة"],
    category: "ترانيم للأطفال",
  },
];

// Combined list: hymns first, then stories/videos
export const kidsBibleVideos: KidsVideo[] = [...kidsHymns, ...kidsStoriesVideos];

// Export hymns separately for playlist feature
export const kidsHymnsPlaylist: KidsVideo[] = kidsHymns;

export const videoCategories = [
  "قصص العهد القديم",
  "سلسلة حكايات دانيال النبي",
  "حكايات من العهد الجديد وأمثال السيد المسيح",
  "سلسلة آحاد الصوم الكبير",
  "قصص العذراء والقديسين",
  "قصص وأناشيد متنوعة",
  "ترانيم للأطفال",
];

export function getYouTubeThumbnail(youtubeId: string): string {
  return `https://img.youtube.com/vi/${youtubeId}/mqdefault.jpg`;
}

export function searchVideos(query: string): KidsVideo[] {
  if (!query.trim()) return kidsBibleVideos;
  const lowerQuery = query.toLowerCase();
  return kidsBibleVideos.filter(video =>
    video.title.toLowerCase().includes(lowerQuery) ||
    video.keywords.some(kw => kw.toLowerCase().includes(lowerQuery))
  );
}
