export const DAILY_VERSES_366 = [
  { dayIndex: 1, month: 1, day: 1, verseText: `لا تخف لأني معك، لا تتلفت لأني إلهك. قد أيدتك وأعنتك وعضدتك بيمين بري.`, verseReference: `إشعياء 41:10`, theme: `تعزية` },
  { dayIndex: 2, month: 1, day: 2, verseText: `سلامي أترك لكم، سلامي أعطيكم. ليس كما يعطي العالم أعطيكم أنا. لا تضطرب قلوبكم ولا ترهب.`, verseReference: `يوحنا 14:27`, theme: `سلام` },
  { dayIndex: 3, month: 1, day: 3, verseText: `الرب نوري وخلاصي ممن أخاف؟ الرب حصن حياتي ممن أرتعب؟`, verseReference: `مزمور 27:1`, theme: `إيمان` },
  { dayIndex: 4, month: 1, day: 4, verseText: `قريب هو الرب من المنكسري القلوب، ويخلص المنسحقي الروح.`, verseReference: `مزمور 34:18`, theme: `تعزية` },
  { dayIndex: 5, month: 1, day: 5, verseText: `في يوم خوفي عليك توكلت.`, verseReference: `مزمور 56:3`, theme: `إيمان` },
  { dayIndex: 6, month: 1, day: 6, verseText: `تعالوا إليّ يا جميع المتعبين والثقيلي الأحمال وأنا أريحكم.`, verseReference: `متى 11:28`, theme: `تعزية` },
  { dayIndex: 7, month: 1, day: 7, verseText: `طوبى للحزانى لأنهم يتعزون.`, verseReference: `متى 5:4`, theme: `تعزية` },
  { dayIndex: 8, month: 1, day: 8, verseText: `الرب راعيّ فلا يعوزني شيء.`, verseReference: `مزمور 23:1`, theme: `تعزية` },
  { dayIndex: 9, month: 1, day: 9, verseText: `تشدد وتشجع، لا ترهب ولا ترتعب لأن الرب إلهك معك حيثما تذهب.`, verseReference: `يشوع 1:9`, theme: `قوة` },
  { dayIndex: 10, month: 1, day: 10, verseText: `الرب يقاتل عنكم وأنتم تصمتون.`, verseReference: `خروج 14:14`, theme: `إيمان` },
  { dayIndex: 11, month: 1, day: 11, verseText: `لأنك أنت يا رب رجائي، جعلت العلي ملجأك.`, verseReference: `مزمور 91:9`, theme: `رجاء` },
  { dayIndex: 12, month: 1, day: 12, verseText: `الذين ينتظرون الرب يجددون قوة، يرفعون أجنحة كالنسور.`, verseReference: `إشعياء 40:31`, theme: `قوة` },
  { dayIndex: 13, month: 1, day: 13, verseText: `ها أنا معكم كل الأيام إلى انقضاء الدهر.`, verseReference: `متى 28:20`, theme: `تعزية` },
  { dayIndex: 14, month: 1, day: 14, verseText: `لا تهتموا بشيء، بل في كل شيء بالصلاة والدعاء مع الشكر لتعلم طلباتكم لدى الله.`, verseReference: `فيلبي 4:6`, theme: `صلاة` },
  { dayIndex: 15, month: 1, day: 15, verseText: `إله الرجاء يملأكم كل سرور وسلام في الإيمان.`, verseReference: `رومية 15:13`, theme: `رجاء` },
  { dayIndex: 16, month: 1, day: 16, verseText: `لأن الله لم يعطنا روح الفشل بل روح القوة والمحبة والنصح.`, verseReference: `2 تيموثاوس 1:7`, theme: `قوة` },
  { dayIndex: 17, month: 1, day: 17, verseText: `لأن لي الأفكار التي أنا مفتكر بها عنكم، يقول الرب، أفكار سلام لا شر.`, verseReference: `إرميا 29:11`, theme: `رجاء` },
  { dayIndex: 18, month: 1, day: 18, verseText: `الرب قريب لكل الذين يدعونه، لكل الذين يدعونه بالحق.`, verseReference: `مزمور 145:18`, theme: `صلاة` },
  { dayIndex: 19, month: 1, day: 19, verseText: `أما المتوكلون على الرب فمثل جبل صهيون لا يتزعزع.`, verseReference: `مزمور 125:1`, theme: `إيمان` },
  { dayIndex: 20, month: 1, day: 20, verseText: `اطرح على الرب همك فهو يعولك. لا يدع الصديق يتزعزع إلى الأبد.`, verseReference: `مزمور 55:22`, theme: `تعزية` },
  { dayIndex: 21, month: 1, day: 21, verseText: `لأنه هكذا أحب الله العالم حتى بذل ابنه الوحيد لكي لا يهلك كل من يؤمن به بل تكون له الحياة الأبدية.`, verseReference: `يوحنا 3:16`, theme: `محبة` },
  { dayIndex: 22, month: 1, day: 22, verseText: `الله ملجأنا وقوتنا، معيناً في الضيقات وُجد أكثر جداً.`, verseReference: `مزمور 46:1`, theme: `قوة` },
  { dayIndex: 23, month: 1, day: 23, verseText: `ونعلم أن كل الأشياء تعمل معاً للخير للذين يحبون الله.`, verseReference: `رومية 8:28`, theme: `رجاء` },
  { dayIndex: 24, month: 1, day: 24, verseText: `فرّح بالرب وهو يعطيك سؤال قلبك.`, verseReference: `مزمور 37:4`, theme: `فرح` },
  { dayIndex: 25, month: 1, day: 25, verseText: `توكل على الرب بكل قلبك وعلى فهمك لا تعتمد.`, verseReference: `أمثال 3:5`, theme: `إيمان` },
  { dayIndex: 26, month: 1, day: 26, verseText: `أستطيع كل شيء في المسيح الذي يقويني.`, verseReference: `فيلبي 4:13`, theme: `قوة` },
  { dayIndex: 27, month: 1, day: 27, verseText: `أرفع عيني إلى الجبال. من أين يأتي عوني؟ عوني من عند الرب صانع السماء والأرض.`, verseReference: `مزمور 121:1`, theme: `إيمان` },
  { dayIndex: 28, month: 1, day: 28, verseText: `حين تعبر في المياه أنا معك، وفي الأنهار فلا تطغى عليك.`, verseReference: `إشعياء 43:2`, theme: `تعزية` },
  { dayIndex: 29, month: 1, day: 29, verseText: `لأن رضاه في الحياة. عند المساء يبيت البكاء وفي الصباح ترنم.`, verseReference: `مزمور 30:5`, theme: `رجاء` },
  { dayIndex: 30, month: 1, day: 30, verseText: `كل عطية صالحة وكل موهبة تامة هي من فوق، نازلة من عند أبي الأنوار.`, verseReference: `يعقوب 1:17`, theme: `شكر` },
  { dayIndex: 31, month: 1, day: 31, verseText: `أعلمك وأرشدك في الطريق التي تسلك فيها. أنصحك عيني عليك.`, verseReference: `مزمور 32:8`, theme: `حكمة` },
  { dayIndex: 32, month: 2, day: 1, verseText: `من لا يحب لم يعرف الله لأن الله محبة.`, verseReference: `1 يوحنا 4:8`, theme: `محبة` },
  { dayIndex: 33, month: 2, day: 2, verseText: `المحبة تتأنى وترفق. المحبة لا تحسد. المحبة لا تتفاخر ولا تنتفخ.`, verseReference: `1 كورنثوس 13:4`, theme: `محبة` },
  { dayIndex: 34, month: 2, day: 3, verseText: `لأني متيقن أن لا موت ولا حياة ولا ملائكة ولا رياسات ولا قوات لا حاضر ولا مستقبل يستطيع أن يفصلنا عن محبة الله.`, verseReference: `رومية 8:38`, theme: `محبة` },
  { dayIndex: 35, month: 2, day: 4, verseText: `وصية جديدة أعطيكم: أن تحبوا بعضكم. كما أحببتكم أنا تحبون أنتم أيضاً بعضكم.`, verseReference: `يوحنا 13:34`, theme: `محبة` },
  { dayIndex: 36, month: 2, day: 5, verseText: `قبل كل شيء كونوا مخلصين في محبتكم بعضكم لبعض، لأن المحبة تستر كثيراً من الخطايا.`, verseReference: `1 بطرس 4:8`, theme: `محبة` },
  { dayIndex: 37, month: 2, day: 6, verseText: `بمحبة أبدية أحببتك، من أجل ذلك أدمت لك الإحسان.`, verseReference: `إرميا 31:3`, theme: `محبة` },
  { dayIndex: 38, month: 2, day: 7, verseText: `الرب إلهك في وسطك، قادر يخلص. يبتهج بك بفرح. يسكت في محبته. يتهلل عليك بترنم.`, verseReference: `صفنيا 3:17`, theme: `محبة` },
  { dayIndex: 39, month: 2, day: 8, verseText: `الرب رحيم وحنون، بطيء الغضب وكثير الرحمة.`, verseReference: `مزمور 103:8`, theme: `رحمة` },
  { dayIndex: 40, month: 2, day: 9, verseText: `إن رحمات الرب لم تنقطع، إن مراحمه لا تفنى، كل صباح تتجدد. عظمت أمانتك.`, verseReference: `مراثي 3:22`, theme: `رحمة` },
  { dayIndex: 41, month: 2, day: 10, verseText: `أما ثمر الروح فهو المحبة والفرح والسلام والطول الأناة واللطف والصلاح.`, verseReference: `غلاطية 5:22`, theme: `محبة` },
  { dayIndex: 42, month: 2, day: 11, verseText: `كما أحبني الآب أنا أيضاً أحببتكم. اثبتوا في محبتي.`, verseReference: `يوحنا 15:9`, theme: `محبة` },
  { dayIndex: 43, month: 2, day: 12, verseText: `انظروا أي محبة أعطانا الآب حتى ندعى أولاد الله.`, verseReference: `1 يوحنا 3:1`, theme: `محبة` },
  { dayIndex: 44, month: 2, day: 13, verseText: `لكن الله بيّن محبته لنا لأنه ونحن بعد خطاة مات المسيح عنا.`, verseReference: `رومية 5:8`, theme: `محبة` },
  { dayIndex: 45, month: 2, day: 14, verseText: `ليس لأحد حب أعظم من هذا: أن يضع أحد نفسه لأجل أحبائه.`, verseReference: `يوحنا 15:13`, theme: `محبة` },
  { dayIndex: 46, month: 2, day: 15, verseText: `في كل وقت يحب الخليل وكالأخ يولد للضيقة.`, verseReference: `أمثال 17:17`, theme: `محبة` },
  { dayIndex: 47, month: 2, day: 16, verseText: `وعلى هذا كله البسوا المحبة التي هي رباط الكمال.`, verseReference: `كولوسي 3:14`, theme: `محبة` },
  { dayIndex: 48, month: 2, day: 17, verseText: `احمدوا الرب لأنه صالح، لأن إلى الأبد رحمته.`, verseReference: `مزمور 136:1`, theme: `شكر` },
  { dayIndex: 49, month: 2, day: 18, verseText: `أما أنا فقد علمت أن وليّي حي، وأنه سيقوم أخيراً على التراب.`, verseReference: `أيوب 19:25`, theme: `إيمان` },
  { dayIndex: 50, month: 2, day: 19, verseText: `مبتهجين في الرجاء، صابرين في الضيق، مواظبين على الصلاة.`, verseReference: `رومية 12:12`, theme: `رجاء` },
  { dayIndex: 51, month: 2, day: 20, verseText: `وأنت يا رب إله رحيم وحنون، بطيء الغضب وكثير الرحمة والحق.`, verseReference: `مزمور 86:15`, theme: `رحمة` },
  { dayIndex: 52, month: 2, day: 21, verseText: `فلنتقدم بثقة إلى عرش النعمة لكي ننال رحمة ونجد نعمة عوناً في حينه.`, verseReference: `عبرانيين 4:16`, theme: `صلاة` },
  { dayIndex: 53, month: 2, day: 22, verseText: `لله الذي يقدر أن يفعل فوق كل شيء أكثر جداً مما نطلب أو نفتكر بحسب القوة التي تعمل فينا.`, verseReference: `أفسس 3:20`, theme: `إيمان` },
  { dayIndex: 54, month: 2, day: 23, verseText: `يشفي المنكسري القلوب ويعصب أوجاعهم.`, verseReference: `مزمور 147:3`, theme: `تعزية` },
  { dayIndex: 55, month: 2, day: 24, verseText: `الرب صالح، ملجأ في يوم الضيق، وعارف المتوكلين عليه.`, verseReference: `ناحوم 1:7`, theme: `تعزية` },
  { dayIndex: 56, month: 2, day: 25, verseText: `مبارك الله أبو ربنا يسوع المسيح، أبو الرأفة وإله كل تعزية.`, verseReference: `2 كورنثوس 1:3`, theme: `تعزية` },
  { dayIndex: 57, month: 2, day: 26, verseText: `لله وحده تستريح نفسي. منه خلاصي.`, verseReference: `مزمور 62:1`, theme: `إيمان` },
  { dayIndex: 58, month: 2, day: 27, verseText: `اطلبوا تجدوا. اقرعوا يفتح لكم.`, verseReference: `لوقا 11:9`, theme: `صلاة` },
  { dayIndex: 59, month: 2, day: 28, verseText: `طوبى للجياع والعطاش إلى البر لأنهم يشبعون.`, verseReference: `متى 5:6`, theme: `بركة` },
  { dayIndex: 366, month: 2, day: 29, verseText: `افرحوا في كل حين. صلوا بلا انقطاع. في كل شيء اشكروا.`, verseReference: `1 تسالونيكي 5:16`, theme: `فرح` },
  { dayIndex: 60, month: 3, day: 1, verseText: `الإيمان هو جوهر ما يُرجى وبرهان ما لا يُرى.`, verseReference: `عبرانيين 11:1`, theme: `إيمان` },
  { dayIndex: 61, month: 3, day: 2, verseText: `كل شيء مستطاع للمؤمن.`, verseReference: `مرقس 9:23`, theme: `إيمان` },
  { dayIndex: 62, month: 3, day: 3, verseText: `فالإيمان من الإخبار والإخبار بكلمة الله.`, verseReference: `رومية 10:17`, theme: `إيمان` },
  { dayIndex: 63, month: 3, day: 4, verseText: `احسبوه كل فرح يا إخوتي حين تقعون في تجارب متنوعة، عالمين أن امتحان إيمانكم ينشئ صبراً.`, verseReference: `يعقوب 1:2`, theme: `صبر` },
  { dayIndex: 64, month: 3, day: 5, verseText: `نفتخر أيضاً في الضيقات، عالمين أن الضيقة تنشئ صبراً، والصبر تزكية، والتزكية رجاء.`, verseReference: `رومية 5:3`, theme: `صبر` },
  { dayIndex: 65, month: 3, day: 6, verseText: `انتظرت الرب فأمال إليّ وسمع صراخي.`, verseReference: `مزمور 40:1`, theme: `صبر` },
  { dayIndex: 66, month: 3, day: 7, verseText: `في الرجوع والراحة تخلصون، في الهدوء والطمأنينة تكون قوتكم.`, verseReference: `إشعياء 30:15`, theme: `سلام` },
  { dayIndex: 67, month: 3, day: 8, verseText: `انتظر الرب. تشدد وليتشجع قلبك وانتظر الرب.`, verseReference: `مزمور 27:14`, theme: `صبر` },
  { dayIndex: 68, month: 3, day: 9, verseText: `لا نفشل في عمل الخير لأننا سنحصد في وقته إن كنا لا نكل.`, verseReference: `غلاطية 6:9`, theme: `صبر` },
  { dayIndex: 69, month: 3, day: 10, verseText: `لأن خفة ضيقتنا الوقتية تنشئ لنا أكثر فأكثر ثقل مجد أبدي.`, verseReference: `2 كورنثوس 4:17`, theme: `رجاء` },
  { dayIndex: 70, month: 3, day: 11, verseText: `لأني أحسب أن آلام الزمان الحاضر لا تستحق أن تقاس بالمجد العتيد أن يستعلن فينا.`, verseReference: `رومية 8:18`, theme: `رجاء` },
  { dayIndex: 71, month: 3, day: 12, verseText: `الرب الإله شمس وترس. الرب يعطي نعمة ومجداً. لن يمنع خيراً عن السالكين في الاستقامة.`, verseReference: `مزمور 84:11`, theme: `بركة` },
  { dayIndex: 72, month: 3, day: 13, verseText: `وكان يكلمهم بمثل في أنه ينبغي أن يصلوا في كل حين ولا يملّوا.`, verseReference: `لوقا 18:1`, theme: `صلاة` },
  { dayIndex: 73, month: 3, day: 14, verseText: `وسلام الله الذي يفوق كل عقل سيحفظ قلوبكم وأفكاركم في المسيح يسوع.`, verseReference: `فيلبي 4:7`, theme: `سلام` },
  { dayIndex: 74, month: 3, day: 15, verseText: `في كل طرقك اعرفه وهو يقوّم سبلك.`, verseReference: `أمثال 3:6`, theme: `حكمة` },
  { dayIndex: 75, month: 3, day: 16, verseText: `قلبي وجسمي قد يفنيان لكن الله صخرة قلبي ونصيبي إلى الأبد.`, verseReference: `مزمور 73:26`, theme: `إيمان` },
  { dayIndex: 76, month: 3, day: 17, verseText: `أنا هو القيامة والحياة. من آمن بي ولو مات سيحيا.`, verseReference: `يوحنا 11:25`, theme: `رجاء` },
  { dayIndex: 77, month: 3, day: 18, verseText: `إذاً لا شيء من الدينونة الآن على الذين هم في المسيح يسوع.`, verseReference: `رومية 8:1`, theme: `نعمة` },
  { dayIndex: 78, month: 3, day: 19, verseText: `لكنكم ستقبلون قوة متى حل الروح القدس عليكم وتكونون لي شهوداً.`, verseReference: `أعمال 1:8`, theme: `قوة` },
  { dayIndex: 79, month: 3, day: 20, verseText: `كلامك سراج لرجلي ونور لسبيلي.`, verseReference: `مزمور 119:105`, theme: `حكمة` },
  { dayIndex: 80, month: 3, day: 21, verseText: `المتكل عليك بأفكار مستقيمة تحفظه سالماً سالماً.`, verseReference: `إشعياء 26:3`, theme: `سلام` },
  { dayIndex: 81, month: 3, day: 22, verseText: `تشدد وتشجع لا تخف ولا ترتعب منهم لأن الرب إلهك هو الذي يسير معك.`, verseReference: `تثنية 31:6`, theme: `قوة` },
  { dayIndex: 82, month: 3, day: 23, verseText: `أحمدك على أني قد جبلت بصورة مخيفة عجيبة. عجيبة أعمالك وأنا أعلم ذلك علماً.`, verseReference: `مزمور 139:14`, theme: `شكر` },
  { dayIndex: 83, month: 3, day: 24, verseText: `أما أنا فإلى الرب أنظر وأنتظر إله خلاصي. إلهي يسمعني.`, verseReference: `ميخا 7:7`, theme: `صلاة` },
  { dayIndex: 84, month: 3, day: 25, verseText: `قلب الإنسان يفكر في طريقه، لكن الرب يثبّت خطوته.`, verseReference: `أمثال 16:9`, theme: `حكمة` },
  { dayIndex: 85, month: 3, day: 26, verseText: `أنا قد جئت لتكون لهم حياة وليكون لهم أفضل.`, verseReference: `يوحنا 10:10`, theme: `نعمة` },
  { dayIndex: 86, month: 3, day: 27, verseText: `تعرفني سبيل الحياة. أمامك حبور تام. في يمينك نعيم إلى الأبد.`, verseReference: `مزمور 16:11`, theme: `فرح` },
  { dayIndex: 87, month: 3, day: 28, verseText: `لأن كل ما سبق فكُتب كتب لتعليمنا، حتى بالصبر والتعزية من الكتب يكون لنا رجاء.`, verseReference: `رومية 15:4`, theme: `رجاء` },
  { dayIndex: 88, month: 3, day: 29, verseText: `وهو مجروح لأجل معاصينا مسحوق لأجل آثامنا، تأديب سلامنا عليه وبحبره شُفينا.`, verseReference: `إشعياء 53:5`, theme: `فداء` },
  { dayIndex: 89, month: 3, day: 30, verseText: `وأما هذه فقد كتبت لتؤمنوا أن يسوع هو المسيح ابن الله، ولكي تكون لكم إذا آمنتم حياة باسمه.`, verseReference: `يوحنا 20:31`, theme: `إيمان` },
  { dayIndex: 90, month: 3, day: 31, verseText: `فتوبوا وارجعوا لكي تمحى خطاياكم، حتى تأتي أوقات الفرج من وجه الرب.`, verseReference: `أعمال 3:19`, theme: `توبة` },
  { dayIndex: 91, month: 4, day: 1, verseText: `لا تندهشوا. أنتم تطلبون يسوع الناصري المصلوب. قد قام. ليس هو ها هنا.`, verseReference: `مرقس 16:6`, theme: `قيامة` },
  { dayIndex: 92, month: 4, day: 2, verseText: `لكن المسيح قد قام من الأموات وصار باكورة الراقدين.`, verseReference: `1 كورنثوس 15:20`, theme: `قيامة` },
  { dayIndex: 93, month: 4, day: 3, verseText: `فدُفنّا معه بالمعمودية للموت، حتى كما أُقيم المسيح من الأموات بمجد الآب، هكذا نسلك نحن أيضاً في جدة الحياة.`, verseReference: `رومية 6:4`, theme: `قيامة` },
  { dayIndex: 94, month: 4, day: 4, verseText: `في بيت أبي منازل كثيرة. وإن كان غير ذلك لكنت قد قلت لكم. أنا أمضي لأعدّ لكم مكاناً.`, verseReference: `يوحنا 14:2`, theme: `رجاء` },
  { dayIndex: 95, month: 4, day: 5, verseText: `أيها الموت أين شوكتك؟ أيها الهاوية أين غلبتك؟`, verseReference: `1 كورنثوس 15:55`, theme: `قيامة` },
  { dayIndex: 96, month: 4, day: 6, verseText: `وإن كان روح الذي أقام يسوع من الأموات ساكناً فيكم فالذي أقام المسيح من الأموات سيحيي أجسادكم أيضاً.`, verseReference: `رومية 8:11`, theme: `قيامة` },
  { dayIndex: 97, month: 4, day: 7, verseText: `الحق الحق أقول لكم إن لم تقع حبة الحنطة في الأرض وتمت فهي تبقى وحدها، ولكن إن ماتت تأتي بثمر كثير.`, verseReference: `يوحنا 12:24`, theme: `حياة` },
  { dayIndex: 98, month: 4, day: 8, verseText: `إن كان أحد في المسيح فهو خليقة جديدة. الأشياء العتيقة قد مضت. ها قد صارت جديدة.`, verseReference: `2 كورنثوس 5:17`, theme: `حياة جديدة` },
  { dayIndex: 99, month: 4, day: 9, verseText: `ها أنا أجدد كل شيء.`, verseReference: `رؤيا 21:5`, theme: `حياة جديدة` },
  { dayIndex: 100, month: 4, day: 10, verseText: `لأني هأنذا خالق سماوات جديدة وأرضاً جديدة فلا تُذكر الأوليات ولا تخطر على بال.`, verseReference: `إشعياء 65:17`, theme: `رجاء` },
  { dayIndex: 101, month: 4, day: 11, verseText: `أنا هو خبز الحياة. من يُقبل إليّ فلا يجوع، ومن يؤمن بي فلا يعطش أبداً.`, verseReference: `يوحنا 6:35`, theme: `حياة` },
  { dayIndex: 102, month: 4, day: 12, verseText: `أنا هو نور العالم. من يتبعني فلا يمشي في الظلمة بل يكون له نور الحياة.`, verseReference: `يوحنا 8:12`, theme: `حياة` },
  { dayIndex: 103, month: 4, day: 13, verseText: `أنا هو الطريق والحق والحياة. ليس أحد يأتي إلى الآب إلا بي.`, verseReference: `يوحنا 14:6`, theme: `حياة` },
  { dayIndex: 104, month: 4, day: 14, verseText: `هذا هو اليوم الذي صنعه الرب فلنبتهج ونفرح فيه.`, verseReference: `مزمور 118:24`, theme: `فرح` },
  { dayIndex: 105, month: 4, day: 15, verseText: `لكن في هذا كله نحن نغلب بالذي أحبنا.`, verseReference: `رومية 8:37`, theme: `قوة` },
  { dayIndex: 106, month: 4, day: 16, verseText: `لا بأعمال في بر صنعناها نحن بل بمقتضى رحمته خلّصنا بغسل الميلاد الثاني وتجديد الروح القدس.`, verseReference: `تيطس 3:5`, theme: `نعمة` },
  { dayIndex: 107, month: 4, day: 17, verseText: `لأنكم بالنعمة مخلّصون بالإيمان، وذلك ليس منكم هو عطية الله.`, verseReference: `أفسس 2:8`, theme: `نعمة` },
  { dayIndex: 108, month: 4, day: 18, verseText: `الذي فيه لنا الفداء بدمه غفران الخطايا حسب غنى نعمته.`, verseReference: `أفسس 1:7`, theme: `فداء` },
  { dayIndex: 109, month: 4, day: 19, verseText: `أما كل الذين قبلوه فأعطاهم سلطاناً أن يصيروا أولاد الله أي المؤمنون باسمه.`, verseReference: `يوحنا 1:12`, theme: `نعمة` },
  { dayIndex: 110, month: 4, day: 20, verseText: `مبارك الله أبو ربنا يسوع المسيح الذي أولدنا ثانية حسب رحمته الكثيرة لرجاء حي بقيامة يسوع المسيح من الأموات.`, verseReference: `1 بطرس 1:3`, theme: `قيامة` },
  { dayIndex: 111, month: 4, day: 21, verseText: `ادخلوا أبوابه بالحمد دياره بالتسبيح. احمدوه باركوا اسمه.`, verseReference: `مزمور 100:4`, theme: `تسبيح` },
  { dayIndex: 112, month: 4, day: 22, verseText: `إن اعترفنا بخطايانا فهو أمين وعادل حتى يغفر لنا خطايانا ويطهرنا من كل إثم.`, verseReference: `1 يوحنا 1:9`, theme: `توبة` },
  { dayIndex: 113, month: 4, day: 23, verseText: `ارحمني يا الله كمحبتك. كعظيم مراحمك امحُ معاصيّ.`, verseReference: `مزمور 51:1`, theme: `توبة` },
  { dayIndex: 114, month: 4, day: 24, verseText: `تعالوا فتحاججوا يقول الرب. إن كانت خطاياكم كالقرمز تبيض كالثلج.`, verseReference: `إشعياء 1:18`, theme: `توبة` },
  { dayIndex: 115, month: 4, day: 25, verseText: `لأن ابني هذا كان ميتاً فعاش، وكان ضالاً فوُجد.`, verseReference: `لوقا 15:24`, theme: `توبة` },
  { dayIndex: 116, month: 4, day: 26, verseText: `لأن التوبة للحياة قد أعطاها الله أيضاً للأمم.`, verseReference: `أعمال 11:18`, theme: `توبة` },
  { dayIndex: 117, month: 4, day: 27, verseText: `بقدر ما بعد الشرق من الغرب بعَّد عنا معاصينا.`, verseReference: `مزمور 103:12`, theme: `رحمة` },
  { dayIndex: 118, month: 4, day: 28, verseText: `ارجعوا أيها البنون المرتدون فأشفي ارتداداتكم.`, verseReference: `إرميا 3:22`, theme: `رحمة` },
  { dayIndex: 119, month: 4, day: 29, verseText: `إن تواضع شعبي الذين دُعوا باسمي وصلوا وطلبوا وجهي ورجعوا عن طرقهم الردية فأنا أسمع من السماء وأغفر خطيتهم.`, verseReference: `2 أخبار 7:14`, theme: `توبة` },
  { dayIndex: 120, month: 4, day: 30, verseText: `ذوقوا وانظروا ما أطيب الرب. طوبى للإنسان الذي يتكل عليه.`, verseReference: `مزمور 34:8`, theme: `إيمان` },
  { dayIndex: 121, month: 5, day: 1, verseText: `قلت لكم هذا لكي يكون لكم في سلام. في العالم سيكون لكم ضيق. لكن ثقوا. أنا قد غلبت العالم.`, verseReference: `يوحنا 16:33`, theme: `سلام` },
  { dayIndex: 122, month: 5, day: 2, verseText: `لا تحزنوا لأن بهجة الرب هي قوتكم.`, verseReference: `نحميا 8:10`, theme: `فرح` },
  { dayIndex: 123, month: 5, day: 3, verseText: `وضعت الرب أمامي في كل حين. لأنه عن يميني فلا أتزعزع.`, verseReference: `مزمور 16:8`, theme: `إيمان` },
  { dayIndex: 124, month: 5, day: 4, verseText: `افرحوا في الرب كل حين. وأقول أيضاً افرحوا.`, verseReference: `فيلبي 4:4`, theme: `فرح` },
  { dayIndex: 125, month: 5, day: 5, verseText: `هذا كلمتكم به لكي يثبت فرحي فيكم ويكون فرحكم كاملاً.`, verseReference: `يوحنا 15:11`, theme: `فرح` },
  { dayIndex: 126, month: 5, day: 6, verseText: `قد جعلت الفرح في قلبي أعظم مما كان لديهم حين كثر قمحهم وخمرهم.`, verseReference: `مزمور 4:7`, theme: `فرح` },
  { dayIndex: 127, month: 5, day: 7, verseText: `لأعطيهم إكليلاً عوضاً عن الرماد وزيت الابتهاج عوضاً عن النوح ورداء التسبيح عوضاً عن الروح اليائسة.`, verseReference: `إشعياء 61:3`, theme: `فرح` },
  { dayIndex: 128, month: 5, day: 8, verseText: `الرب قوتي وترسي. عليه اتكل قلبي فأُعِنت وابتهج قلبي وبأغنيتي أحمده.`, verseReference: `مزمور 28:7`, theme: `تسبيح` },
  { dayIndex: 129, month: 5, day: 9, verseText: `لأن ملكوت الله ليس أكلاً وشرباً بل هو بر وسلام وفرح في الروح القدس.`, verseReference: `رومية 14:17`, theme: `فرح` },
  { dayIndex: 130, month: 5, day: 10, verseText: `رنموا للرب أغنية جديدة لأنه صنع عجائب.`, verseReference: `مزمور 98:1`, theme: `تسبيح` },
  { dayIndex: 131, month: 5, day: 11, verseText: `يا الله أنت إلهي. إليك أبكر. تظمأ إليك نفسي.`, verseReference: `مزمور 63:1`, theme: `شوق` },
  { dayIndex: 132, month: 5, day: 12, verseText: `كما يشتاق الإيل إلى جداول المياه هكذا تشتاق نفسي إليك يا الله.`, verseReference: `مزمور 42:1`, theme: `شوق` },
  { dayIndex: 133, month: 5, day: 13, verseText: `تشتاق بل تشتاق نفسي إلى ديار الرب. قلبي وجسمي يهتفان بالله الحي.`, verseReference: `مزمور 84:2`, theme: `شوق` },
  { dayIndex: 134, month: 5, day: 14, verseText: `لأن عندك ينبوع الحياة. بنورك نرى نوراً.`, verseReference: `مزمور 36:9`, theme: `حياة` },
  { dayIndex: 135, month: 5, day: 15, verseText: `جاهد جهاد الإيمان الحسن وتمسك بالحياة الأبدية التي إليها دُعيت.`, verseReference: `1 تيموثاوس 6:12`, theme: `إيمان` },
  { dayIndex: 136, month: 5, day: 16, verseText: `ونحن إذ يحيط بنا سحاب من الشهود مثل هذا لنطرح عنا كل ثقل والخطية المحيطة بنا ولنُحضر بالصبر في الجهاد الموضوع أمامنا.`, verseReference: `عبرانيين 12:1`, theme: `صبر` },
  { dayIndex: 137, month: 5, day: 17, verseText: `ناظرين إلى رئيس الإيمان ومكمله يسوع، الذي من أجل السرور الموضوع أمامه احتمل الصليب مستهيناً بالخزي.`, verseReference: `عبرانيين 12:2`, theme: `إيمان` },
  { dayIndex: 138, month: 5, day: 18, verseText: `يعطي المعيا قوة ويزيد التعب شدة.`, verseReference: `إشعياء 40:29`, theme: `قوة` },
  { dayIndex: 139, month: 5, day: 19, verseText: `الرب يسند كل الساقطين ويقيم كل المنحنين.`, verseReference: `مزمور 145:14`, theme: `تعزية` },
  { dayIndex: 140, month: 5, day: 20, verseText: `إن كان الله معنا فمن علينا؟`, verseReference: `رومية 8:31`, theme: `إيمان` },
  { dayIndex: 141, month: 5, day: 21, verseText: `لأنه لم يحتقر ولم يكره مذلة المتألم ولم يخفِ عنه وجهه بل حين صرخ إليه سمع.`, verseReference: `مزمور 22:24`, theme: `تعزية` },
  { dayIndex: 142, month: 5, day: 22, verseText: `في الرفيع والمقدس أسكن ومع المتحطم والمتواضع الروح لأحيي روح المتواضعين.`, verseReference: `إشعياء 57:15`, theme: `تعزية` },
  { dayIndex: 143, month: 5, day: 23, verseText: `الرب صخرتي وحصني ومنقذي. إلهي صخرتي الذي أتوكل عليه. ترسي وقرن خلاصي وملجئي.`, verseReference: `مزمور 18:2`, theme: `قوة` },
  { dayIndex: 144, month: 5, day: 24, verseText: `طوبى لأنقياء القلب لأنهم يعاينون الله.`, verseReference: `متى 5:8`, theme: `بركة` },
  { dayIndex: 145, month: 5, day: 25, verseText: `طوبى للصانعي السلام لأنهم أبناء الله يدعون.`, verseReference: `متى 5:9`, theme: `سلام` },
  { dayIndex: 146, month: 5, day: 26, verseText: `وإن كان أحدكم يعوزه حكمة فليطلب من الله الذي يعطي الجميع ببسط وبلا عتاب فسيُعطى له.`, verseReference: `يعقوب 1:5`, theme: `حكمة` },
  { dayIndex: 147, month: 5, day: 27, verseText: `اسم الرب برج حصين يركض إليه الصديق ويتمنع.`, verseReference: `أمثال 18:10`, theme: `قوة` },
  { dayIndex: 148, month: 5, day: 28, verseText: `عزوا عزوا شعبي يقول إلهكم.`, verseReference: `إشعياء 40:1`, theme: `تعزية` },
  { dayIndex: 149, month: 5, day: 29, verseText: `الرب يعطي شعبه قوة. الرب يبارك شعبه بالسلام.`, verseReference: `مزمور 29:11`, theme: `سلام` },
  { dayIndex: 150, month: 5, day: 30, verseText: `قدّسهم في حقك. كلامك هو حق.`, verseReference: `يوحنا 17:17`, theme: `قداسة` },
  { dayIndex: 151, month: 5, day: 31, verseText: `طوبى للرجل الذي لم يسلك في مشورة الأشرار وفي طريق الخطاة لم يقف وفي مجلس المستهزئين لم يجلس.`, verseReference: `مزمور 1:1`, theme: `حكمة` },
  { dayIndex: 152, month: 6, day: 1, verseText: `لا يُفلح كل سلاح صُنع عليك. وكل لسان يقوم عليك في الحكم تحكم عليه أنت. هذا هو ميراث عبيد الرب.`, verseReference: `إشعياء 54:17`, theme: `قوة` },
  { dayIndex: 153, month: 6, day: 2, verseText: `الساكن في ستر العلي يبيت في ظل القدير.`, verseReference: `مزمور 91:1`, theme: `حماية` },
  { dayIndex: 154, month: 6, day: 3, verseText: `بريشه يسترك وتحت أجنحته تحتمي. درع وجُنّة أمانته.`, verseReference: `مزمور 91:4`, theme: `حماية` },
  { dayIndex: 155, month: 6, day: 4, verseText: `ملاك الرب حال حول خائفيه ومنقذهم.`, verseReference: `مزمور 34:7`, theme: `حماية` },
  { dayIndex: 156, month: 6, day: 5, verseText: `كذلك الروح أيضاً يعين ضعفاتنا لأننا لا نعلم ما نصلي به كما ينبغي، لكن الروح نفسه يشفع فينا بأنات لا يُنطق بها.`, verseReference: `رومية 8:26`, theme: `صلاة` },
  { dayIndex: 157, month: 6, day: 6, verseText: `بكل محافظة احفظ قلبك لأن منه مخارج الحياة.`, verseReference: `أمثال 4:23`, theme: `حكمة` },
  { dayIndex: 158, month: 6, day: 7, verseText: `أنا الكرمة وأنتم الأغصان. من يثبت فيّ وأنا فيه هذا يأتي بثمر كثير لأنكم بدوني لا تستطيعون أن تفعلوا شيئاً.`, verseReference: `يوحنا 15:5`, theme: `ثبات` },
  { dayIndex: 159, month: 6, day: 8, verseText: `من يستر معاصيه لا ينجح، أما من يُقرّ بها ويتركها فيُرحم.`, verseReference: `أمثال 28:13`, theme: `توبة` },
  { dayIndex: 160, month: 6, day: 9, verseText: `وتعرفون الحق والحق يحرركم.`, verseReference: `يوحنا 8:32`, theme: `حرية` },
  { dayIndex: 161, month: 6, day: 10, verseText: `قد أعتقنا المسيح للحرية. فاثبتوا إذاً ولا تعودوا ثانية تحت نير العبودية.`, verseReference: `غلاطية 5:1`, theme: `حرية` },
  { dayIndex: 162, month: 6, day: 11, verseText: `والرب هو الروح وحيثما روح الرب هناك حرية.`, verseReference: `2 كورنثوس 3:17`, theme: `حرية` },
  { dayIndex: 163, month: 6, day: 12, verseText: `فلتكن كلمات فمي ولتكن أفكار قلبي مرضية أمامك يا رب صخرتي وجاليّ.`, verseReference: `مزمور 19:14`, theme: `صلاة` },
  { dayIndex: 164, month: 6, day: 13, verseText: `ولا تتشكلوا بهيئة هذا الدهر بل تحوّلوا عن طريق تجديد أذهانكم لتختبروا ما هي إرادة الله الصالحة المرضية الكاملة.`, verseReference: `رومية 12:2`, theme: `تجديد` },
  { dayIndex: 165, month: 6, day: 14, verseText: `اخلق فيّ يا الله قلباً نقياً وجدد في روحاً مستقيماً.`, verseReference: `مزمور 51:10`, theme: `تجديد` },
  { dayIndex: 166, month: 6, day: 15, verseText: `طوبى للمساكين بالروح لأن لهم ملكوت السماوات.`, verseReference: `متى 5:3`, theme: `بركة` },
  { dayIndex: 167, month: 6, day: 16, verseText: `كل نسمة فلتسبح الرب. هللويا.`, verseReference: `مزمور 150:6`, theme: `تسبيح` },
  { dayIndex: 168, month: 6, day: 17, verseText: `أن تقدموا أجسادكم ذبيحة حية مقدسة مرضية عند الله. عبادتكم العقلية.`, verseReference: `رومية 12:1`, theme: `تقديس` },
  { dayIndex: 169, month: 6, day: 18, verseText: `وكونوا لطيفين بعضكم نحو بعض، شفوقين، متسامحين بعضكم بعضاً، كما غفر لكم الله أيضاً في المسيح.`, verseReference: `أفسس 4:32`, theme: `محبة` },
  { dayIndex: 170, month: 6, day: 19, verseText: `اطلبوا أولاً ملكوت الله وبره وهذه كلها تُزاد لكم.`, verseReference: `متى 6:33`, theme: `إيمان` },
  { dayIndex: 171, month: 6, day: 20, verseText: `باركي يا نفسي الرب ولا تنسي كل حسناته.`, verseReference: `مزمور 103:2`, theme: `شكر` },
  { dayIndex: 172, month: 6, day: 21, verseText: `لأن كل مولود من الله يغلب العالم. وهذه هي الغلبة التي تغلب العالم: إيمانكم.`, verseReference: `1 يوحنا 5:4`, theme: `إيمان` },
  { dayIndex: 173, month: 6, day: 22, verseText: `لا تأخذكم تجربة إلا بشرية. والله أمين الذي لن يدعكم تُجرّبون فوق ما تستطيعون.`, verseReference: `1 كورنثوس 10:13`, theme: `إيمان` },
  { dayIndex: 174, month: 6, day: 23, verseText: `أكرم الرب من مالك ومن أول كل غلاتك.`, verseReference: `أمثال 3:9`, theme: `عطاء` },
  { dayIndex: 175, month: 6, day: 24, verseText: `أعطوا يُعط لكم. كيلاً جيداً ملضوماً مهزوزاً فائضاً يعطون في أحضانكم.`, verseReference: `لوقا 6:38`, theme: `عطاء` },
  { dayIndex: 176, month: 6, day: 25, verseText: `كل واحد كما ينوي في قلبه لا عن حزن أو اضطرار. لأن المعطي المسرور يحبه الله.`, verseReference: `2 كورنثوس 9:7`, theme: `عطاء` },
  { dayIndex: 177, month: 6, day: 26, verseText: `ثمة من يفرق ويزيد أيضاً ومن يمسك أكثر مما ينبغي فيؤدي إلى الاحتياج.`, verseReference: `أمثال 11:24`, theme: `عطاء` },
  { dayIndex: 178, month: 6, day: 27, verseText: `جيئوا بجميع العشور إلى البيت الخزانة حتى يكون طعام في بيتي وجربوني بهذا يقول رب الجنود.`, verseReference: `ملاخي 3:10`, theme: `إيمان` },
  { dayIndex: 179, month: 6, day: 28, verseText: `من يرحم الفقير يُقرض الرب وهو يجازيه بعطائه.`, verseReference: `أمثال 19:17`, theme: `رحمة` },
  { dayIndex: 180, month: 6, day: 29, verseText: `الحق أقول لكم بما أنكم فعلتموه بأحد إخوتي هؤلاء الأصاغر فبي فعلتم.`, verseReference: `متى 25:40`, theme: `محبة` },
  { dayIndex: 181, month: 6, day: 30, verseText: `لا تخف لأني فديتك. دعوتك باسمك فأنت لي.`, verseReference: `إشعياء 43:1`, theme: `تعزية` },
  { dayIndex: 182, month: 7, day: 1, verseText: `هلّلوا للرب يا جميع الأرض. اعبدوا الرب بفرح. ادخلوا إلى حضرته بترنم.`, verseReference: `مزمور 100:1`, theme: `تسبيح` },
  { dayIndex: 183, month: 7, day: 2, verseText: `هلموا نترنم للرب. نهتف بصخرة خلاصنا.`, verseReference: `مزمور 95:1`, theme: `تسبيح` },
  { dayIndex: 184, month: 7, day: 3, verseText: `سبحوا الرب من السماوات. سبحوه في الأعالي.`, verseReference: `مزمور 148:1`, theme: `تسبيح` },
  { dayIndex: 185, month: 7, day: 4, verseText: `رنموا للرب أغنية جديدة، تسبيحه في جماعة الأتقياء.`, verseReference: `مزمور 149:1`, theme: `تسبيح` },
  { dayIndex: 186, month: 7, day: 5, verseText: `باركي يا نفسي الرب وكل ما في داخلي بارك اسمه القدوس.`, verseReference: `مزمور 103:1`, theme: `تسبيح` },
  { dayIndex: 187, month: 7, day: 6, verseText: `مستحق أنت يا ربنا وإلهنا أن تقبل المجد والإكرام والقدرة لأنك أنت خلقت كل شيء.`, verseReference: `رؤيا 4:11`, theme: `تسبيح` },
  { dayIndex: 188, month: 7, day: 7, verseText: `سبحوا الرب يا جميع الأمم. هللوه يا سائر الشعوب.`, verseReference: `مزمور 117:1`, theme: `تسبيح` },
  { dayIndex: 189, month: 7, day: 8, verseText: `الله روح والذين يسجدون له فبالروح والحق ينبغي أن يسجدوا.`, verseReference: `يوحنا 4:24`, theme: `عبادة` },
  { dayIndex: 190, month: 7, day: 9, verseText: `يا ربنا يا ربنا ما أعظم اسمك في كل الأرض الذي جعلت بهاءك فوق السماوات.`, verseReference: `مزمور 8:1`, theme: `تسبيح` },
  { dayIndex: 191, month: 7, day: 10, verseText: `يا جميع الأمم صفقوا بالأيدي. اهتفوا لله بصوت الابتهاج.`, verseReference: `مزمور 47:1`, theme: `تسبيح` },
  { dayIndex: 192, month: 7, day: 11, verseText: `احمدوا الرب وادعوا باسمه. عرّفوا بأعماله في الشعوب.`, verseReference: `1 أيام 16:8`, theme: `تسبيح` },
  { dayIndex: 193, month: 7, day: 12, verseText: `هتفوا لله يا جميع الأرض. رنموا لمجد اسمه. اجعلوا تسبيحه مجيداً.`, verseReference: `مزمور 66:1`, theme: `تسبيح` },
  { dayIndex: 194, month: 7, day: 13, verseText: `أخبروا بين الأمم بمجده بين جميع الشعوب بعجائبه.`, verseReference: `مزمور 96:3`, theme: `تسبيح` },
  { dayIndex: 195, month: 7, day: 14, verseText: `احمدوا الرب لأنه صالح لأن إلى الأبد رحمته.`, verseReference: `مزمور 107:1`, theme: `شكر` },
  { dayIndex: 196, month: 7, day: 15, verseText: `حسن الحمد للرب والترنيم لاسمك أيها العلي.`, verseReference: `مزمور 92:1`, theme: `تسبيح` },
  { dayIndex: 197, month: 7, day: 16, verseText: `مع ذلك أبتهج بالرب وأفرح بإله خلاصي.`, verseReference: `حبقوق 3:17`, theme: `فرح` },
  { dayIndex: 198, month: 7, day: 17, verseText: `رأس الحكمة مخافة الرب. عقل صالح لكل العاملين بها. تسبيحه قائم إلى الأبد.`, verseReference: `مزمور 111:10`, theme: `حكمة` },
  { dayIndex: 199, month: 7, day: 18, verseText: `بداءة الحكمة مخافة الرب ومعرفة القدوس فهم.`, verseReference: `أمثال 9:10`, theme: `حكمة` },
  { dayIndex: 200, month: 7, day: 19, verseText: `احملوا نيري عليكم وتعلموا مني لأني وديع ومتواضع القلب فتجدوا راحة لنفوسكم.`, verseReference: `متى 11:29`, theme: `سلام` },
  { dayIndex: 201, month: 7, day: 20, verseText: `يا رب لم يتشامخ قلبي ولم ترتفع عيناي. ولم أتمشَّ في عظائم في أمور معجزة عني.`, verseReference: `مزمور 131:1`, theme: `تواضع` },
  { dayIndex: 202, month: 7, day: 21, verseText: `قد أعلمك يا إنسان ما هو الخير وماذا يطلب منك الرب إلا أن تصنع الحق وتحب الرحمة وتتواضع في السيرة مع إلهك.`, verseReference: `ميخا 6:8`, theme: `قداسة` },
  { dayIndex: 203, month: 7, day: 22, verseText: `ليس بالجيش ولا بالقوة بل بروحي يقول رب الجنود.`, verseReference: `زكريا 4:6`, theme: `قوة` },
  { dayIndex: 204, month: 7, day: 23, verseText: `طلبت الرب فأجابني ومن كل مخاوفي أنقذني.`, verseReference: `مزمور 34:4`, theme: `صلاة` },
  { dayIndex: 205, month: 7, day: 24, verseText: `وهذه هي الثقة التي لنا عنده أنه إن طلبنا شيئاً حسب مشيئته يسمع منا.`, verseReference: `1 يوحنا 5:14`, theme: `صلاة` },
  { dayIndex: 206, month: 7, day: 25, verseText: `اسألوا تعطوا. اطلبوا تجدوا. اقرعوا يفتح لكم.`, verseReference: `متى 7:7`, theme: `صلاة` },
  { dayIndex: 207, month: 7, day: 26, verseText: `إن ثبتم فيّ وثبت كلامي فيكم فاطلبوا ما تريدون فسيكون لكم.`, verseReference: `يوحنا 15:7`, theme: `صلاة` },
  { dayIndex: 208, month: 7, day: 27, verseText: `قبل أن يدعوا أنا أجيب. وبينما هم لا يزالون يتكلمون أسمع.`, verseReference: `إشعياء 65:24`, theme: `صلاة` },
  { dayIndex: 209, month: 7, day: 28, verseText: `يا رب صباحاً تسمع صوتي. صباحاً أُعرض لك وأراقب.`, verseReference: `مزمور 5:3`, theme: `صلاة` },
  { dayIndex: 210, month: 7, day: 29, verseText: `وكان يجثو على ركبتيه ثلاث مرات في اليوم ويصلي ويحمد أمام إلهه.`, verseReference: `دانيال 6:10`, theme: `صلاة` },
  { dayIndex: 211, month: 7, day: 30, verseText: `مساء وصباحاً وعند الظهر أشكو وأصرخ فيسمع صوتي.`, verseReference: `مزمور 55:17`, theme: `صلاة` },
  { dayIndex: 212, month: 7, day: 31, verseText: `وكانوا يواظبون على تعليم الرسل والشركة وكسر الخبز والصلوات.`, verseReference: `أعمال 2:42`, theme: `صلاة` },
  { dayIndex: 213, month: 8, day: 1, verseText: `وإلهي سيكمّل كل احتياجاتكم بحسب غناه في المجد في المسيح يسوع.`, verseReference: `فيلبي 4:19`, theme: `بركة` },
  { dayIndex: 214, month: 8, day: 2, verseText: `ترتب قدامي مائدة تجاه مضايقيّ. دهنت بالدهن رأسي. كأسي ريّا.`, verseReference: `مزمور 23:5`, theme: `بركة` },
  { dayIndex: 215, month: 8, day: 3, verseText: `فتمتلئ أهراؤك شبعاً وتفيض معاصرك خمراً.`, verseReference: `أمثال 3:10`, theme: `بركة` },
  { dayIndex: 216, month: 8, day: 4, verseText: `أبي الذي أعطاني إياهم هو أعظم من الكل ولا أحد يقدر أن يخطف من يد أبي.`, verseReference: `يوحنا 10:29`, theme: `حماية` },
  { dayIndex: 217, month: 8, day: 5, verseText: `لأنه يوصي ملائكته بك لكي يحفظوك في جميع طرقك.`, verseReference: `مزمور 91:11`, theme: `حماية` },
  { dayIndex: 218, month: 8, day: 6, verseText: `الذي لم يشفق على ابنه بل أسلمه لأجلنا جميعاً كيف لا يهبنا أيضاً معه كل شيء.`, verseReference: `رومية 8:32`, theme: `بركة` },
  { dayIndex: 219, month: 8, day: 7, verseText: `مبارك الله أبو ربنا يسوع المسيح الذي باركنا بكل بركة روحية في السماويات في المسيح.`, verseReference: `أفسس 1:3`, theme: `بركة` },
  { dayIndex: 220, month: 8, day: 8, verseText: `وأجعلك أمة عظيمة وأباركك وأعظم اسمك وكن بركة.`, verseReference: `تكوين 12:2`, theme: `بركة` },
  { dayIndex: 221, month: 8, day: 9, verseText: `يباركك الرب ويحفظك. يضيء الرب بوجهه عليك ويتراءف عليك. يرفع الرب وجهه إليك ويمنحك سلاماً.`, verseReference: `عدد 6:24`, theme: `بركة` },
  { dayIndex: 222, month: 8, day: 10, verseText: `الله يترأف بنا ويباركنا يشرق وجهه علينا.`, verseReference: `مزمور 67:1`, theme: `بركة` },
  { dayIndex: 223, month: 8, day: 11, verseText: `اقتربوا من الله فيقترب منكم.`, verseReference: `يعقوب 4:8`, theme: `صلاة` },
  { dayIndex: 224, month: 8, day: 12, verseText: `يا ابني لا ترفض تأديب الرب ولا تقبح توبيخه.`, verseReference: `أمثال 3:11`, theme: `حكمة` },
  { dayIndex: 225, month: 8, day: 13, verseText: `لأن الرب من يحبه يؤدبه ويجلد كل ابن يقبله.`, verseReference: `عبرانيين 12:6`, theme: `حكمة` },
  { dayIndex: 226, month: 8, day: 14, verseText: `طوبى للإنسان الذي تؤدبه يا رب وتعلمه من شريعتك.`, verseReference: `مزمور 94:12`, theme: `حكمة` },
  { dayIndex: 227, month: 8, day: 15, verseText: `كل الكتاب هو موحى به من الله ونافع للتعليم والتوبيخ للتقويم والتأديب الذي في البر.`, verseReference: `2 تيموثاوس 3:16`, theme: `حكمة` },
  { dayIndex: 228, month: 8, day: 16, verseText: `بماذا يزكو الشاب طريقه؟ بالتحفظ حسب كلامك.`, verseReference: `مزمور 119:9`, theme: `قداسة` },
  { dayIndex: 229, month: 8, day: 17, verseText: `في قلبي خبأت كلامك لكي لا أخطئ إليك.`, verseReference: `مزمور 119:11`, theme: `قداسة` },
  { dayIndex: 230, month: 8, day: 18, verseText: `لتسكن فيكم كلمة المسيح بغنى بكل حكمة وأنتم تعلمون وتعظون بعضكم بعضاً.`, verseReference: `كولوسي 3:16`, theme: `حكمة` },
  { dayIndex: 231, month: 8, day: 19, verseText: `لا يبرح سفر هذه الشريعة من فيك بل تلهج فيه نهاراً وليلاً لتتحفظ للعمل حسب كل ما هو مكتوب فيه.`, verseReference: `يشوع 1:8`, theme: `حكمة` },
  { dayIndex: 232, month: 8, day: 20, verseText: `لأن الرب يعطي الحكمة. من فمه المعرفة والفهم.`, verseReference: `أمثال 2:6`, theme: `حكمة` },
  { dayIndex: 233, month: 8, day: 21, verseText: `مبارك اسم الله من الأزل وإلى الأبد لأن له الحكمة والجبروت.`, verseReference: `دانيال 2:20`, theme: `تسبيح` },
  { dayIndex: 234, month: 8, day: 22, verseText: `عرّفني يا رب طرقك علّمني سبلك.`, verseReference: `مزمور 25:4`, theme: `حكمة` },
  { dayIndex: 235, month: 8, day: 23, verseText: `بالحكمة يُبنى البيت وبالفهم يثبت.`, verseReference: `أمثال 24:3`, theme: `حكمة` },
  { dayIndex: 236, month: 8, day: 24, verseText: `يسلك المساكين في الحق ويعلم المساكين طريقه.`, verseReference: `مزمور 25:9`, theme: `حكمة` },
  { dayIndex: 237, month: 8, day: 25, verseText: `وأما المعزّي الروح القدس الذي سيرسله الآب باسمي فهو يعلمكم كل شيء ويذكركم بكل ما قلته لكم.`, verseReference: `يوحنا 14:26`, theme: `روح القدس` },
  { dayIndex: 238, month: 8, day: 26, verseText: `وأما متى جاء ذاك روح الحق فهو يرشدكم إلى جميع الحق.`, verseReference: `يوحنا 16:13`, theme: `روح القدس` },
  { dayIndex: 239, month: 8, day: 27, verseText: `لأن كل الذين ينقادون بروح الله فأولئك هم أبناء الله.`, verseReference: `رومية 8:14`, theme: `روح القدس` },
  { dayIndex: 240, month: 8, day: 28, verseText: `ستقبلون قوة متى حل الروح القدس عليكم وتكونون لي شهوداً في أورشليم.`, verseReference: `أعمال 1:8-ب`, theme: `روح القدس` },
  { dayIndex: 241, month: 8, day: 29, verseText: `أم لستم تعلمون أن جسمكم هو هيكل للروح القدس الذي فيكم الذي لكم من الله.`, verseReference: `1 كورنثوس 6:19`, theme: `قداسة` },
  { dayIndex: 242, month: 8, day: 30, verseText: `امتلئوا بالروح متكلمين بعضكم بعضاً بمزامير وتسابيح وأغاني روحية.`, verseReference: `أفسس 5:18`, theme: `روح القدس` },
  { dayIndex: 243, month: 8, day: 31, verseText: `إن كنا نعيش بالروح فلنسلك أيضاً بالروح.`, verseReference: `غلاطية 5:25`, theme: `روح القدس` },
  { dayIndex: 244, month: 9, day: 1, verseText: `مخافة الرب رأس المعرفة. الحمق يحتقر الحكمة والتأديب.`, verseReference: `أمثال 1:7`, theme: `حكمة` },
  { dayIndex: 245, month: 9, day: 2, verseText: `أنا الذين يحبونني أحبهم والذين يبكرون إليّ يجدونني.`, verseReference: `أمثال 8:17`, theme: `محبة` },
  { dayIndex: 246, month: 9, day: 3, verseText: `بدون المشورات تخيب المقاصد وبكثرة المشيرين تثبت.`, verseReference: `أمثال 15:22`, theme: `حكمة` },
  { dayIndex: 247, month: 9, day: 4, verseText: `لا حكمة ولا فهم ولا مشورة في مقابلة الرب.`, verseReference: `أمثال 21:30`, theme: `حكمة` },
  { dayIndex: 248, month: 9, day: 5, verseText: `من كيّل روح الرب ومن هداه مشيراً وعلّمه.`, verseReference: `إشعياء 40:13`, theme: `عظمة الله` },
  { dayIndex: 249, month: 9, day: 6, verseText: `يا لعمق غنى الله وحكمته وعلمه. ما أصعب أحكامه وما أعمق طرقه.`, verseReference: `رومية 11:33`, theme: `عظمة الله` },
  { dayIndex: 250, month: 9, day: 7, verseText: `عنده الحكمة والقوة. له المشورة والفهم.`, verseReference: `أيوب 12:13`, theme: `عظمة الله` },
  { dayIndex: 251, month: 9, day: 8, verseText: `فأحب الرب إلهك من كل قلبك ومن كل نفسك ومن كل قوتك.`, verseReference: `تثنية 6:5`, theme: `محبة` },
  { dayIndex: 252, month: 9, day: 9, verseText: `فتحب الرب إلهك من كل قلبك ومن كل نفسك ومن كل فكرك ومن كل قدرتك. هذه هي الوصية الأولى.`, verseReference: `مرقس 12:30`, theme: `محبة` },
  { dayIndex: 253, month: 9, day: 10, verseText: `الإنسان ينظر إلى العينين لكن الرب ينظر إلى القلب.`, verseReference: `1 صموئيل 16:7`, theme: `حكمة` },
  { dayIndex: 254, month: 9, day: 11, verseText: `لأن أفكاري ليست أفكاركم ولا طرقكم طرقي يقول الرب.`, verseReference: `إشعياء 55:8`, theme: `عظمة الله` },
  { dayIndex: 255, month: 9, day: 12, verseText: `كما علت السماوات عن الأرض هكذا علت طرقي عن طرقكم وأفكاري عن أفكاركم.`, verseReference: `إشعياء 55:9`, theme: `عظمة الله` },
  { dayIndex: 256, month: 9, day: 13, verseText: `هذا الله إلهنا إلى الأبد والأبد. هو يدلنا حتى الموت.`, verseReference: `مزمور 48:14`, theme: `إيمان` },
  { dayIndex: 257, month: 9, day: 14, verseText: `أيضاً إذا سلكت في وادي ظل الموت لا أخاف شراً لأنك أنت معي.`, verseReference: `مزمور 23:4`, theme: `تعزية` },
  { dayIndex: 258, month: 9, day: 15, verseText: `فأنتم الآن لكم حزن لكنني سأراكم أيضاً فيفرح قلبكم وليس أحد يرفع فرحكم عنكم.`, verseReference: `يوحنا 16:22`, theme: `فرح` },
  { dayIndex: 259, month: 9, day: 16, verseText: `قد حوّلت نوحي إلى رقص وحللت مسحي وشددتني فرحاً.`, verseReference: `مزمور 30:11`, theme: `فرح` },
  { dayIndex: 260, month: 9, day: 17, verseText: `مبارك الرجل الذي يتكل على الرب وكان الرب متكله.`, verseReference: `إرميا 17:7`, theme: `إيمان` },
  { dayIndex: 261, month: 9, day: 18, verseText: `كل أعمالك إلى الرب وتثبت أفكارك.`, verseReference: `أمثال 16:3`, theme: `إيمان` },
  { dayIndex: 262, month: 9, day: 19, verseText: `لأني أنا الرب إلهك ممسك يمينك القائل لك لا تخف أنا عنتك.`, verseReference: `إشعياء 41:13`, theme: `تعزية` },
  { dayIndex: 263, month: 9, day: 20, verseText: `لأنك أنت رجائي يا رب. منذ حداثتي إيّاك اتكلت.`, verseReference: `مزمور 71:5`, theme: `رجاء` },
  { dayIndex: 264, month: 9, day: 21, verseText: `ملقين كل همكم عليه لأنه هو يعتني بكم.`, verseReference: `1 بطرس 5:7`, theme: `تعزية` },
  { dayIndex: 265, month: 9, day: 22, verseText: `أوقاتي بيدك.`, verseReference: `مزمور 31:15`, theme: `إيمان` },
  { dayIndex: 266, month: 9, day: 23, verseText: `يا ابني أعطني قلبك ولتراقب عيناك طرقي.`, verseReference: `أمثال 23:26`, theme: `قداسة` },
  { dayIndex: 267, month: 9, day: 24, verseText: `الرب يكمل لي. يا رب رحمتك إلى الأبد. ولا تترك عمل يديك.`, verseReference: `مزمور 138:8`, theme: `إيمان` },
  { dayIndex: 268, month: 9, day: 25, verseText: `والعالم يمضي وشهوته وأما من يصنع مشيئة الله فيثبت إلى الأبد.`, verseReference: `1 يوحنا 2:17`, theme: `ثبات` },
  { dayIndex: 269, month: 9, day: 26, verseText: `ها أنا واقف على الباب وأقرع. إن سمع أحد صوتي وفتح الباب أدخل إليه وأتعشى معه وهو معي.`, verseReference: `رؤيا 3:20`, theme: `محبة` },
  { dayIndex: 270, month: 9, day: 27, verseText: `الرب صالح للكل ومراحمه على كل أعماله.`, verseReference: `مزمور 145:9`, theme: `رحمة` },
  { dayIndex: 271, month: 9, day: 28, verseText: `هل تنسى المرأة رضيعها فلا ترحم ابن بطنها؟ حتى هؤلاء تنسين وأنا لا أنساك.`, verseReference: `إشعياء 49:15`, theme: `تعزية` },
  { dayIndex: 272, month: 9, day: 29, verseText: `ها على كفّيّ نقشتك. أسوارك أمامي دائماً.`, verseReference: `إشعياء 49:16`, theme: `تعزية` },
  { dayIndex: 273, month: 9, day: 30, verseText: `اطلبوا تأخذوا ليكون فرحكم كاملاً.`, verseReference: `يوحنا 16:24`, theme: `فرح` },
  { dayIndex: 274, month: 10, day: 1, verseText: `في ما يختص بمحبة الإخوة كونوا متحابين. في الكرامة مقدمين بعضكم بعضاً.`, verseReference: `رومية 12:10`, theme: `محبة` },
  { dayIndex: 275, month: 10, day: 2, verseText: `لنتمسك بإقرار الرجاء راسخاً لأن الذي وعد أمين.`, verseReference: `عبرانيين 10:23`, theme: `رجاء` },
  { dayIndex: 276, month: 10, day: 3, verseText: `البغضة تثير خصومات والمحبة تغطي كل الذنوب.`, verseReference: `أمثال 10:12`, theme: `محبة` },
  { dayIndex: 277, month: 10, day: 4, verseText: `لا تحبوا المال بل اكتفوا بما لديكم لأن الله قال لا أتركك ولا أهجرك.`, verseReference: `عبرانيين 13:5`, theme: `إيمان` },
  { dayIndex: 278, month: 10, day: 5, verseText: `خطوات الإنسان الصالح يثبتها الرب وطريقه يسره.`, verseReference: `مزمور 37:23`, theme: `إيمان` },
  { dayIndex: 279, month: 10, day: 6, verseText: `كنت شاباً وقد شخت ولم أرَ صديقاً متروكاً ولا نسله يطلب خبزاً.`, verseReference: `مزمور 37:25`, theme: `إيمان` },
  { dayIndex: 280, month: 10, day: 7, verseText: `في مخافة الرب اتكاء قوي وللأبناء يكون ملجأ.`, verseReference: `أمثال 14:26`, theme: `حماية` },
  { dayIndex: 281, month: 10, day: 8, verseText: `تعطّلوا واعلموا أني أنا الله. أتعالى في الأمم أتعالى في الأرض.`, verseReference: `مزمور 46:10`, theme: `إيمان` },
  { dayIndex: 282, month: 10, day: 9, verseText: `إني لست أستحي بإنجيل المسيح لأنه قوة الله للخلاص لكل من يؤمن.`, verseReference: `رومية 1:16`, theme: `إيمان` },
  { dayIndex: 283, month: 10, day: 10, verseText: `المسيح فيكم رجاء المجد.`, verseReference: `كولوسي 1:27`, theme: `رجاء` },
  { dayIndex: 284, month: 10, day: 11, verseText: `لأن ناموس روح الحياة في المسيح يسوع قد أعتقني من ناموس الخطية والموت.`, verseReference: `رومية 8:2`, theme: `حرية` },
  { dayIndex: 285, month: 10, day: 12, verseText: `كل أمرك على الرب. توكل عليه وهو يفعل.`, verseReference: `مزمور 37:5`, theme: `إيمان` },
  { dayIndex: 286, month: 10, day: 13, verseText: `اسكت للرب وتوقّع له. لا تحتدم على من ينجح في طريقه على الإنسان الصانع المكائد.`, verseReference: `مزمور 37:7`, theme: `صبر` },
  { dayIndex: 287, month: 10, day: 14, verseText: `أنا أنا هو الماحي ذنوبك لأجل نفسي ولا أذكر خطاياك.`, verseReference: `إشعياء 43:25`, theme: `رحمة` },
  { dayIndex: 288, month: 10, day: 15, verseText: `أما رحمة الرب فمن الأزل وإلى الأبد على خائفيه وعدله لبني البنين.`, verseReference: `مزمور 103:17`, theme: `رحمة` },
  { dayIndex: 289, month: 10, day: 16, verseText: `واثق من هذا بعينه أن الذي ابتدأ فيكم عملاً صالحاً سيكمّله حتى يوم يسوع المسيح.`, verseReference: `فيلبي 1:6`, theme: `رجاء` },
  { dayIndex: 290, month: 10, day: 17, verseText: `الجمال باطل والحسن زائل أما المرأة التي تتقي الرب فهي تُمدح.`, verseReference: `أمثال 31:30`, theme: `قداسة` },
  { dayIndex: 291, month: 10, day: 18, verseText: `ليس قدوس مثل الرب لأنه ليس غيرك. وليس صخرة مثل إلهنا.`, verseReference: `1 صموئيل 2:2`, theme: `تسبيح` },
  { dayIndex: 292, month: 10, day: 19, verseText: `لا لنا يا رب لا لنا بل لاسمك أعط المجد من أجل رحمتك وأجل حقك.`, verseReference: `مزمور 115:1`, theme: `تسبيح` },
  { dayIndex: 293, month: 10, day: 20, verseText: `ينبغي أن ذلك يزيد وأنا أنقص.`, verseReference: `يوحنا 3:30`, theme: `تواضع` },
  { dayIndex: 294, month: 10, day: 21, verseText: `بلا شيء من الخصومة أو العجب بل بالتواضع إذ يحسب كل واحد الآخر أفضل من نفسه.`, verseReference: `فيلبي 2:3`, theme: `تواضع` },
  { dayIndex: 295, month: 10, day: 22, verseText: `تواضعوا أمام الرب فيرفعكم.`, verseReference: `يعقوب 4:10`, theme: `تواضع` },
  { dayIndex: 296, month: 10, day: 23, verseText: `كبرياء الإنسان تضعه والمتواضع الروح ينال الكرامة.`, verseReference: `أمثال 29:23`, theme: `تواضع` },
  { dayIndex: 297, month: 10, day: 24, verseText: `لأن كل من يرفع نفسه يتضع ومن يضع نفسه يرتفع.`, verseReference: `لوقا 14:11`, theme: `تواضع` },
  { dayIndex: 298, month: 10, day: 25, verseText: `كل من وضع نفسه مثل هذا الطفل فهو الأعظم في ملكوت السماوات.`, verseReference: `متى 18:4`, theme: `تواضع` },
  { dayIndex: 299, month: 10, day: 26, verseText: `اهدني في حقك وعلّمني لأنك أنت إله خلاصي. إياك انتظرت كل اليوم.`, verseReference: `مزمور 25:5`, theme: `حكمة` },
  { dayIndex: 300, month: 10, day: 27, verseText: `ادعني فأجيبك وأخبرك بعظائم وعقائد لم تعرفها.`, verseReference: `إرميا 33:3`, theme: `صلاة` },
  { dayIndex: 301, month: 10, day: 28, verseText: `لأن فيه نحيا ونتحرك وبه نكون.`, verseReference: `أعمال 17:28`, theme: `إيمان` },
  { dayIndex: 302, month: 10, day: 29, verseText: `لأنك صخرتي وحصني لاسمك تقودني وترشدني.`, verseReference: `مزمور 31:3`, theme: `إيمان` },
  { dayIndex: 303, month: 10, day: 30, verseText: `إذ كنت ثميناً في عيني كنت محترماً وأنا أحببتك.`, verseReference: `إشعياء 43:4`, theme: `محبة` },
  { dayIndex: 304, month: 10, day: 31, verseText: `لأننا نحن عمله مخلوقين في المسيح يسوع لأعمال صالحة.`, verseReference: `أفسس 2:10`, theme: `هوية` },
  { dayIndex: 305, month: 11, day: 1, verseText: `ليحمدوا الرب على رحمته وعلى عجائبه لبني البشر.`, verseReference: `مزمور 107:8`, theme: `شكر` },
  { dayIndex: 306, month: 11, day: 2, verseText: `في كل شيء اشكروا لأن هذه هي إرادة الله في المسيح يسوع نحوكم.`, verseReference: `1 تسالونيكي 5:18`, theme: `شكر` },
  { dayIndex: 307, month: 11, day: 3, verseText: `وكل ما فعلتم بقول أو بفعل فافعلوا كل شيء باسم الرب يسوع شاكرين الله الآب به.`, verseReference: `كولوسي 3:17`, theme: `شكر` },
  { dayIndex: 308, month: 11, day: 4, verseText: `لكي يرنم لك كبودي ولا أسكت. يا رب إلهي إلى الأبد أحمدك.`, verseReference: `مزمور 30:12`, theme: `شكر` },
  { dayIndex: 309, month: 11, day: 5, verseText: `أحمدك يا رب بكل قلبي وأحدث بجميع عجائبك.`, verseReference: `مزمور 9:1`, theme: `شكر` },
  { dayIndex: 310, month: 11, day: 6, verseText: `شاكرين الله الآب دائماً على كل شيء باسم ربنا يسوع المسيح.`, verseReference: `أفسس 5:20`, theme: `شكر` },
  { dayIndex: 311, month: 11, day: 7, verseText: `فرجع أحدهم وهو يمجد الله بصوت عظيم.`, verseReference: `لوقا 17:15`, theme: `شكر` },
  { dayIndex: 312, month: 11, day: 8, verseText: `اذبح لله شكراً وأوفِ للعلي نذورك.`, verseReference: `مزمور 50:14`, theme: `شكر` },
  { dayIndex: 313, month: 11, day: 9, verseText: `أسبّح اسم الله بأغنية وأعظّمه بحمد.`, verseReference: `مزمور 69:30`, theme: `شكر` },
  { dayIndex: 314, month: 11, day: 10, verseText: `لكي تكثر النعمة بالشكر الأكثر من أناس أكثر لمجد الله.`, verseReference: `2 كورنثوس 4:15`, theme: `شكر` },
  { dayIndex: 315, month: 11, day: 11, verseText: `رنموا للرب يا أيتها الأرض كلها. اخدموا الرب بفرح. ادخلوا إلى حضرته بالترنيم.`, verseReference: `مزمور 100:2`, theme: `تسبيح` },
  { dayIndex: 316, month: 11, day: 12, verseText: `احمدوا الرب لأنه صالح لأن إلى الأبد رحمته.`, verseReference: `مزمور 118:1`, theme: `شكر` },
  { dayIndex: 317, month: 11, day: 13, verseText: `لأن منه وبه وله كل شيء. له المجد إلى الأبد.`, verseReference: `رومية 11:36`, theme: `تسبيح` },
  { dayIndex: 318, month: 11, day: 14, verseText: `رنموا للرب أيها الصديقون. بالمستقيمين يليق التسبيح.`, verseReference: `مزمور 33:1`, theme: `تسبيح` },
  { dayIndex: 319, month: 11, day: 15, verseText: `أبارك الرب في كل وقت. تسبيحه دائماً في فمي.`, verseReference: `مزمور 34:1`, theme: `تسبيح` },
  { dayIndex: 320, month: 11, day: 16, verseText: `عظيم الرب وجديرٌ بالتسبيح جداً وعظمته لا تُفحص.`, verseReference: `مزمور 145:3`, theme: `تسبيح` },
  { dayIndex: 321, month: 11, day: 17, verseText: `الرب السيد قوتي وهو يجعل رجليّ كرجلي الأيائل ويمشي بي على مرتفعاتي.`, verseReference: `حبقوق 3:19`, theme: `قوة` },
  { dayIndex: 322, month: 11, day: 18, verseText: `لماذا انحنيت يا نفسي وتئنين؟ انتظري الله لأني سأحمده بعد ذلك. خلاص وجهي وإلهي.`, verseReference: `مزمور 43:5`, theme: `رجاء` },
  { dayIndex: 323, month: 11, day: 19, verseText: `وأما إن كنا نرجو ما لا نراه فنتوقعه بصبر.`, verseReference: `رومية 8:25`, theme: `صبر` },
  { dayIndex: 324, month: 11, day: 20, verseText: `لكي تجد تزكية إيمانكم وهي أكثر قيمة من الذهب الفاني الذي يُجرّب بالنار موجودة للمدح والكرامة والمجد.`, verseReference: `1 بطرس 1:7`, theme: `إيمان` },
  { dayIndex: 325, month: 11, day: 21, verseText: `بالله أمدح كلامه. على الله توكلت لا أخاف. ماذا يصنع بي بشر.`, verseReference: `مزمور 56:4`, theme: `إيمان` },
  { dayIndex: 326, month: 11, day: 22, verseText: `الجبال تزول والتلال تتقلقل أما رحمتي فلا تزول عنك وعهد سلامي لا يتقلقل يقول مترئفك الرب.`, verseReference: `إشعياء 54:10`, theme: `رحمة` },
  { dayIndex: 327, month: 11, day: 23, verseText: `يسوع المسيح هو هو أمساً واليوم وإلى الأبد.`, verseReference: `عبرانيين 13:8`, theme: `ثبات` },
  { dayIndex: 328, month: 11, day: 24, verseText: `ولم تبطل كلمة واحدة من جميع كلماته الصالحة.`, verseReference: `يشوع 23:14`, theme: `ثبات` },
  { dayIndex: 329, month: 11, day: 25, verseText: `لا أنقض عهدي ولا أغير ما خرج من شفتيّ.`, verseReference: `مزمور 89:34`, theme: `ثبات` },
  { dayIndex: 330, month: 11, day: 26, verseText: `منذ الابتداء مخبر بالنهاية ومنذ القديم بما لم يُفعل قائلاً رأيي يقوم وكل مسرتي أفعل.`, verseReference: `إشعياء 46:10`, theme: `ثبات` },
  { dayIndex: 331, month: 11, day: 27, verseText: `لا يتوانى الرب عن وعده كما يظن قوم أن في ذلك إبطاء بل يتأنى علينا وهو لا يشاء أن يهلك أناس بل أن يُقبل الجميع إلى التوبة.`, verseReference: `2 بطرس 3:9`, theme: `رحمة` },
  { dayIndex: 332, month: 11, day: 28, verseText: `إلى الأبد يا رب كلامك ثابت في السماء.`, verseReference: `مزمور 119:89`, theme: `ثبات` },
  { dayIndex: 333, month: 11, day: 29, verseText: `يبست العشب وذبل الزهر وأما كلمة إلهنا فتثبت إلى الأبد.`, verseReference: `إشعياء 40:8`, theme: `ثبات` },
  { dayIndex: 334, month: 11, day: 30, verseText: `الحق الحق أقول لكم من يسمع كلامي ويؤمن بالذي أرسلني فله حياة أبدية.`, verseReference: `يوحنا 5:24`, theme: `حياة` },
  { dayIndex: 335, month: 12, day: 1, verseText: `ها العذراء تحبل وتلد ابناً وتدعو اسمه عمانوئيل.`, verseReference: `إشعياء 7:14`, theme: `ميلاد` },
  { dayIndex: 336, month: 12, day: 2, verseText: `أما أنت يا بيت لحم أفراتة وأنت صغيرة أن تكوني في أُلوف يهوذا فمنك يخرج لي الذي يكون متسلطاً على إسرائيل.`, verseReference: `ميخا 5:2`, theme: `ميلاد` },
  { dayIndex: 337, month: 12, day: 3, verseText: `الشعب السالك في الظلمة أبصر نوراً عظيماً. الجالسون في أرض ظلال الموت أشرق عليهم نور.`, verseReference: `إشعياء 9:2`, theme: `ميلاد` },
  { dayIndex: 338, month: 12, day: 4, verseText: `لأنه ليس شيء غير ممكن لدى الله.`, verseReference: `لوقا 1:37`, theme: `إيمان` },
  { dayIndex: 339, month: 12, day: 5, verseText: `تعظّم نفسي الرب وتبتهج روحي بالله مخلّصي.`, verseReference: `لوقا 1:46`, theme: `تسبيح` },
  { dayIndex: 340, month: 12, day: 6, verseText: `والكلمة صار جسداً وحلّ بيننا ورأينا مجده مجداً كما لوحيد من الآب مملوءاً نعمة وحقاً.`, verseReference: `يوحنا 1:14`, theme: `ميلاد` },
  { dayIndex: 341, month: 12, day: 7, verseText: `هوذا العذراء تحبل وتلد ابناً ويدعون اسمه عمانوئيل الذي تفسيره الله معنا.`, verseReference: `متى 1:23`, theme: `ميلاد` },
  { dayIndex: 342, month: 12, day: 8, verseText: `بأحشاء رحمة إلهنا التي بها افتقدنا الشرق من العلاء.`, verseReference: `لوقا 1:78`, theme: `رحمة` },
  { dayIndex: 343, month: 12, day: 9, verseText: `لأن أجرة الخطية موت وأما موهبة الله فهي حياة أبدية بالمسيح يسوع ربنا.`, verseReference: `رومية 6:23`, theme: `نعمة` },
  { dayIndex: 344, month: 12, day: 10, verseText: `لأن الله لم يرسل ابنه إلى العالم ليدين العالم بل ليخلص به العالم.`, verseReference: `يوحنا 3:17`, theme: `خلاص` },
  { dayIndex: 345, month: 12, day: 11, verseText: `وليس بأحد غيره الخلاص لأنه ليس اسم آخر تحت السماء قد أُعطي بين الناس به ينبغي أن نخلص.`, verseReference: `أعمال 4:12`, theme: `خلاص` },
  { dayIndex: 346, month: 12, day: 12, verseText: `أمين هو القول ومستحق كل قبول أن المسيح يسوع جاء إلى العالم ليخلص الخطاة.`, verseReference: `1 تيموثاوس 1:15`, theme: `خلاص` },
  { dayIndex: 347, month: 12, day: 13, verseText: `إذ قد تبررنا بالإيمان فلنا سلام مع الله بربنا يسوع المسيح.`, verseReference: `رومية 5:1`, theme: `سلام` },
  { dayIndex: 348, month: 12, day: 14, verseText: `لأنه هو سلامنا الذي جعل الاثنين واحداً وهدم حائط السياج المتوسط وهو العداوة.`, verseReference: `أفسس 2:14`, theme: `سلام` },
  { dayIndex: 349, month: 12, day: 15, verseText: `لنمو رياسته وللسلام لا نهاية على كرسي داود وعلى مملكته.`, verseReference: `إشعياء 9:7`, theme: `سلام` },
  { dayIndex: 350, month: 12, day: 16, verseText: `فقال لهم الملاك لا تخافوا فها أنا أبشركم بفرح عظيم يكون لجميع الشعب.`, verseReference: `لوقا 2:10`, theme: `فرح` },
  { dayIndex: 351, month: 12, day: 17, verseText: `أنه وُلد لكم اليوم في مدينة داود مخلص هو المسيح الرب.`, verseReference: `لوقا 2:11`, theme: `ميلاد` },
  { dayIndex: 352, month: 12, day: 18, verseText: `فلنعرف. لنسعَ لنعرف الرب. خروجه مستعد كالفجر ويأتي علينا كالمطر.`, verseReference: `هوشع 6:3`, theme: `إيمان` },
  { dayIndex: 353, month: 12, day: 19, verseText: `لا تضطرب قلوبكم أنتم تؤمنون بالله فآمنوا بي أيضاً.`, verseReference: `يوحنا 14:1`, theme: `سلام` },
  { dayIndex: 354, month: 12, day: 20, verseText: `ومبارك اسم مجده إلى الأبد ولتمتلئ مجده كل الأرض. آمين وآمين.`, verseReference: `مزمور 72:19`, theme: `تسبيح` },
  { dayIndex: 355, month: 12, day: 21, verseText: `انتظر إسرائيل الرب من الآن وإلى الأبد.`, verseReference: `مزمور 131:3`, theme: `رجاء` },
  { dayIndex: 356, month: 12, day: 22, verseText: `لأن خلاصنا أقرب الآن مما كان حين آمنا.`, verseReference: `رومية 13:11`, theme: `رجاء` },
  { dayIndex: 357, month: 12, day: 23, verseText: `منه أنتم في المسيح يسوع الذي صار لنا حكمة من الله وبراً وقداسة وفداء.`, verseReference: `1 كورنثوس 1:30`, theme: `نعمة` },
  { dayIndex: 358, month: 12, day: 24, verseText: `وكل لسان يعترف أن يسوع المسيح هو رب لمجد الله الآب.`, verseReference: `فيلبي 2:11`, theme: `ميلاد` },
  { dayIndex: 359, month: 12, day: 25, verseText: `لأنه يولد لنا ولد ونعطى ابناً وتكون الرياسة على كتفه ويدعى اسمه عجيباً مشيراً إلهاً قديراً أباً أبدياً رئيس السلام.`, verseReference: `إشعياء 9:6`, theme: `ميلاد` },
  { dayIndex: 360, month: 12, day: 26, verseText: `المجد لله في الأعالي وعلى الأرض السلام وبالناس المسرة.`, verseReference: `لوقا 2:14`, theme: `ميلاد` },
  { dayIndex: 361, month: 12, day: 27, verseText: `والنور يضيء في الظلمة والظلمة لم تدركه.`, verseReference: `يوحنا 1:5`, theme: `نور` },
  { dayIndex: 362, month: 12, day: 28, verseText: `رأينا نجمه في المشرق وجئنا لنسجد له.`, verseReference: `متى 2:2`, theme: `ميلاد` },
  { dayIndex: 363, month: 12, day: 29, verseText: `فيه كانت الحياة والحياة كانت نور الناس.`, verseReference: `يوحنا 1:4`, theme: `نور` },
  { dayIndex: 364, month: 12, day: 30, verseText: `أنا الألف والياء البداية والنهاية الأول والآخر.`, verseReference: `رؤيا 22:13`, theme: `عظمة الله` },
  { dayIndex: 365, month: 12, day: 31, verseText: `يقول الذي يشهد بهذا نعم أنا آتي سريعاً آمين نعم تعال أيها الرب يسوع.`, verseReference: `رؤيا 22:20`, theme: `رجاء` },
] as const;